### ISSUE TITLE
Codex: Shadow Mend does not drop

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1787] opened 2022-08-01 20:20 UTC
Codex: Shadow Mend does not drop  

https://database.turtle-wow.org/?item=83571

**Comment by ratkosrb** [comment] 2022-08-02 01:49
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1788

**Closed by ratkosrb** 2022-08-02 01:49 UTC
