### ISSUE TITLE
Danonzo's Tel'Abim Medley does not increase spell haste.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#3630] opened 2023-06-05 11:36 UTC
**Please, provide a clear description what the bug is:**
The food description for Danonzo's Tel'Abim Medley states that it increases haste. Not melee haste, haste. I assumed this meant it increased spell haste too but it does not. It's a very expensive food buff that takes an essence of air to make so I was pretty disappointed it didn't work.

Assuming this is a bug like a lot of the other haste bugs on this server atm that haven't been fixed yet (glove enchant) or it's just a bad choice of wording. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Eat Medely
2. Observe spell to see that its speed hasn't increased.
3. Profit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=60978

**Comment by TatkaS1** [comment] 2023-06-07 09:49
It's probably an unclear choice of wording for which is vanilla wow famous. They should either change the effect or the description, agreed.

**Comment by testening** [comment] 2023-06-08 17:34
It isn't just wording, many haste effects aren't affecting spells even when they should, see:
#3357
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3357#issuecomment-1528936307

**Comment by twowTurtReynolds** [comment] 2023-12-09 03:01
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4372

**Closed by twowTurtReynolds** 2023-12-09 03:01 UTC
