### ISSUE TITLE
Bloodring LOS abuse before match even starts.

### ISSUE THREAD

**Issue by welpenhund** [slowtorta/turtlewow-bug-tracker#5345] opened 2023-11-22 21:31 UTC
**Please, provide a clear description what the bug is:**
Some people found a way to send their pets/demons through the gates in blood ring before the fight even starts.
This makes it impossible for some classes to drink/eat - Mount up or go stealth (example rogue would be forced to vanish before fight even starts to get the pet off...)

**Steps to reproduce the behavior with as much detail as possible:**

1. Join arena
2.  Be a warlock or hunter...
3.  ... send pet through gets on your targets i suppose? I don't know how they do it...

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Would appreciate a fix to prevent that.

**Comment by twowTurtReynolds** [comment] 2023-12-06 20:15
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3985

**Closed by twowTurtReynolds** 2023-12-06 20:15 UTC
Labels: PvP, Needs Replication
