### ISSUE TITLE
Spawn in Chillwind Camp

### ISSUE THREAD

**Issue by KliffKyle** [slowtorta/turtlewow-bug-tracker#4346] opened 2023-09-17 18:11 UTC
**Please, provide a clear description what the bug is:**
Multiple time after teleporting to Alah'thalas from stormwind I would fly to Chillwind Camp to run Scholo or other things. After hearthing back to Stormwind from vaious locations in EPL, WPL, and Tirisfal Glades, whenever I would relog soon after I would be randomly in Chillwind Camp. My hearth was still on cooldown since it was so soon. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Portal to Alah'Thalas
2. Flew to Chillwind Camp
3.  Hearthed back to Stormwind. 
4.  Relog after 10 min (never account logged).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment] 2023-09-18 09:04
I am not able to reproduce the issue. I flew from Alah'thalas to Chillwind camp, then used Hearthstone and logged out. When I log back in I'm still at my Hearthstone location.

**Comment by cyaohiri** [comment] 2023-09-19 10:50
Duplicate of #968.

**Comment by slowtorta** [comment] 2023-10-18 20:46
Fixed with the 1.17.0 release.

**Closed by slowtorta** 2023-10-18 20:46 UTC
Labels: Couldn't reproduce
