### ISSUE TITLE
Equipment mode issue

### ISSUE THREAD

**Issue by Spookeagle** [slowtorta/turtlewow-bug-tracker#5596] opened 2023-12-14 03:18 UTC
**Please, provide a clear description what the bug is:**
Equipment: Crystal sword of blossom
Issue: mode doesn't display out of battle
![in battle](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153789779/520892d2-c123-4743-94d2-fe6e2b07f6c3)
![out of battle](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153789779/d86ba18e-9dc3-47e7-b587-145ada971574)

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item ID:32439
https://database.turtle-wow.org/?item=61523

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-14 13:21
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5153

**Closed by twowTurtReynolds** 2023-12-14 13:21 UTC
