### ISSUE TITLE
Vagrants Endeavor

### ISSUE THREAD

**Issue by ylfek** [slowtorta/turtlewow-bug-tracker#5042] opened 2023-11-03 10:53 UTC
**Please, provide a clear description what the bug is:**
on lvl 60 its still in my spell book, im pretty sure thats reason i cant get enchants properly, pls investigate

Character name Polano
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment] 2023-11-03 11:04
Duplicate of #4829.

**Comment by ylfek** [comment] 2023-11-03 11:19
y, sry, so many issues here

**Closed** 2023-11-19 18:16 UTC
