### ISSUE TITLE
lesser wind stone

### ISSUE THREAD

**Issue by farun963** [slowtorta/turtlewow-bug-tracker#6438] opened 2024-03-05 17:45 UTC
**Please, provide a clear description what the bug is:**
The lesser wind stones in silithus doesnt work, it is used to summon elites for multiple quests. you need to wear cultist set and click the stones to activate em

**Steps to reproduce the behavior with as much detail as possible:**

1. put the custist set on
2. trying to click the stone, doesnt work. log off and on, still no action.
3.  sadness

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: [Earthen Templar] [Abyssal Contacts]
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
you should put the set on and click the stone and voilá
![asd](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139180618/f49c7d6d-fedc-49ed-b7d9-ba8ed688f1da)

**Comment by akzeitions** [comment] 2024-03-05 17:51
Same here, yesterday it was normal, today i've been trying for 3 hours.
Some other small ones respawned the elemental position locked yesterday.

**Comment by ratkosrb** [comment] 2024-03-05 17:56
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/d57d88f5-1074-4172-a48b-76cbf16a5794

I'm not able to reproduce the issue :/

**Comment by akzeitions** [comment] 2024-03-05 17:59
I just can't interact with the smaller stone, it doesn't show anything, with or without the set equipped.

**Comment by ratkosrb** [comment] 2024-03-05 18:02
Have you tried deleting the WDB folder?

**Comment by ratkosrb** [comment] 2024-03-05 18:14
So the stones spawn but you can't click on them at all?

**Comment by ratkosrb** [comment] 2024-03-05 18:19
I think I found out what causes it. Two people clicking the gossip option at the same time seems to bug it.

**Comment by akzeitions** [comment] 2024-03-05 18:32
It makes sense, they're really contested.

**Comment by ratkosrb** [comment] 2024-03-05 19:21
It should be fixed after the next update.

**Closed by ratkosrb** 2024-03-05 19:21 UTC

**Comment by Muigin** [comment] 2024-03-05 19:22
A reminder to consider having the script not spawn these creatures inside the gameobjects that summon them.

**Comment by ratkosrb** [comment] 2024-03-05 22:42
I think they spawn there in sniffs from classic.
