### ISSUE TITLE
Unable to apply Invocation of Shattering to Darkflame Helm

### ISSUE THREAD

**Issue by Quackmandan** [slowtorta/turtlewow-bug-tracker#5070] opened 2023-11-04 17:55 UTC
**Please, provide a clear description what the bug is:**
"Invocation of Shattering" Helm/Leg enchant cannot be applied to Darkflame Helm.  An error message pops up saying "That item is not a valid target."
**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire Invocation of Shattering and  Darkflame Helm
2.  Right click the invocation.  Left click Darkflame Helm.
3. Admire the lovely error message.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=
https://database.turtle-wow.org/?item=92005
https://database.turtle-wow.org/?item=61291

**Expected behavior. Describe how it should work:**
Invocation of Shattering should be appliable to Darkflame Helm as an enchant since it is... a helmet.

**Comment by Zebouski** [comment] 2023-11-07 14:13
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4705 

Use the workaround provided in that ticket.

**Comment by Muigin** [comment] 2023-11-13 11:37
Duplicate of #4788

**Closed by Muigin** 2023-11-13 11:37 UTC
