### ISSUE TITLE
Range of spells and shooting

### ISSUE THREAD

**Issue by Esqariote** [slowtorta/turtlewow-bug-tracker#5358] opened 2023-11-23 17:35 UTC
A warrior's charge has a minimum range of 8 yards like a bow shot, but approaching this minimum range the demoralizing shout does not reach the target, although it has a range of 10 yards. Is there a mistake here somewhere?

**Steps to reproduce the behavior with as much detail as possible:**

1. Be a warrior.
2. Fill up with rage and stand close to the training dummy.
3. Move to shot or charge range from dummy (8yd).
5. Use a demoralizing shout (its range is 10yd according to the tooltip).
6. See that the debuff has not applied to dummy. If you approach about a step, it will begin to be applied to the target.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=11578   warrior charge
https://database.turtle-wow.org/?spell=27579   warrior  demoralizing  shout

**Expected behavior. Describe how it should work:**
either it should shoot and charge closer, or the demoshout should reach farther

**Comment by twowTurtReynolds** [comment] 2023-12-04 20:06
As I understand it, the range of charge is the central point of the mob, plus its hitbox raidius, plus the 8yds, to the radius of your hitbox, and finally to your center point. 

The range of demo shout is purely center point to center point. No radiuses are calculated.

I replicated your findings on big mobs with big hitboxes. With small mobs, see how I hit the rat with demo shout while also being in charge range?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e3aedcfa-ea96-4471-878c-497bf69b77f6)

Closing as not a bug.

**Closed by twowTurtReynolds** 2023-12-04 20:06 UTC
