### ISSUE TITLE
Bug: Quest To Save A Soul 

### ISSUE THREAD

**Issue by Suween** [slowtorta/turtlewow-bug-tracker#4955] opened 2023-10-29 15:07 UTC
**Please, provide a clear description what the bug is:**
The quest [To Save a Soul](https://database.turtle-wow.org/?quest=4112) doesn't spawn the NPC for which to get the follow up quest [To Save a Soul](https://database.turtle-wow.org/?quest=41124) on completion.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the quest [To Save a Soul](https://database.turtle-wow.org/?quest=4112) at the totem.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=4112
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=2010969

**Expected behavior. Describe how it should work:**

Given a completed objective, When you turn the quest in, then the npc with the follow up question should spawn.

**Comment by twowTurtReynolds** [comment] 2023-11-20 05:14
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4931

**Closed by twowTurtReynolds** 2023-11-20 05:14 UTC
Labels: Quest
