### ISSUE TITLE
Quest "Rise, Obsidion!" bugged. Can't be completed

### ISSUE THREAD

**Issue by MadLitrus** [slowtorta/turtlewow-bug-tracker#1249] opened 2022-03-30 18:32 UTC
**Please, provide a clear description what the bug is:**

After you pick up the quest "Rise, Obsidion!" an NPC named Dorius appears. He appears with red nameplate but you can't attack him or interact with him in any form nor does he say anything. From this point on nothing happens in regards to this quest. If abandon and reaccept the quest a few times the NPC will eventually despawn and does not appear back.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=8421
Quest: https://database.turtle-wow.org/?quest=3566

**Expected behavior. Describe how it should work:**

Like in the video linked below:
https://www.youtube.com/watch?v=leraa1Dtzng&t=14s&ab_channel=Bue

**Comment by Tinyfin-github** [comment] 2022-03-30 19:01
Thank you for the report!

Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/507

**Closed by Tinyfin-github** 2022-03-30 19:01 UTC
