### ISSUE TITLE
Lord Valthalak summon is bugged; denying completion of dungeon set quest chain

### ISSUE THREAD

**Issue by kendog0013** [slowtorta/turtlewow-bug-tracker#5905] opened 2024-01-05 12:18 UTC
**Please, provide a clear description what the bug is:**

It seems that whenever you try to right click the brazier of summoning (summon lord valthalak) in the beast's room of UBRS in the proper spot doesnt work - the game just gives the message 'invalid target' - WDB was cleared and a relog was attempted to no avail; also, another in the group also had their brazier of summoning to try and help and also got the message 'invalid target.' 

I have dropped the quest and am currently awaiting another UBRS group to form before i re-accept the quest and see if that 'fixes' it, but I am almost certain it will not - If that does however fix it, i will update this post with the relevant info on HOW to get the summon to work.

very obnoxious bug: I could've been done with UBRS on that run, but now i have to wait hours of trying to find another UBRS group... Going through 3 months for this quest chain just to be greeted with that at the LAST part of the entire series is a massive buzzkill and until I know it's fixed, I don't think I can continue playing.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Accept quest [Mea Culpa, Lord Valthalak] from Bodley outside of LBRS (extra-dimensional ghost revealer needed to see him)
2.  slog through UBRS until youre at the beasts room, kill him
3.  right click quest item: brazier of beckoning (summon lord valthalak) 
4.  observe that, when in the right area, the game doesn't summon and instead just gives the message 'invalid target.'

5. weep because you spent months just to find out that the 30th quest in the series is bugged; 2 short of full completion...

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=16042 (npc) 
https://database.turtle-wow.org/?npc=16048 (trigger) 
https://database.turtle-wow.org/?npc=16073 (spirit quest turn in after death)

Item: https://database.turtle-wow.org/?item=22056 (Brazier of Beckoning(summon lord valthalak))

Quest: https://database.turtle-wow.org/?quest=8995 (Mea Culpa, Lord Valthalak)

Spell: https://database.turtle-wow.org/?spell=27202 (summon Lord Valthalak DND)
https://database.turtle-wow.org/?spell=27360 (instill amulet with spirit after death)

Object: https://database.turtle-wow.org/?object=181050 (lord valthalak brazier spell focus)

**Expected behavior. Describe how it should work:**

*Right clicking the quest item 'Brazier of beckoning: Summon Lord Valthalak' should spawn 'Lord Valthalak' in the beast's room of UBRS but instead just gives the message 'invalid target'; quest is needed to complete last part of dungeon set quest series...*

**Comment by ratkosrb** [comment] 2024-01-05 13:50
I already fixed this internally yesterday but you have to wait for the server to be updated.

**Comment by twowTurtReynolds** [comment] 2024-01-05 13:59
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5892

**Closed by twowTurtReynolds** 2024-01-05 13:59 UTC
