### ISSUE TITLE
Beastmaster's Gloves ["Use: Improves your chance to hit by 1%".]

### ISSUE THREAD

**Issue by MenelauGC** [slowtorta/turtlewow-bug-tracker#5357] opened 2023-11-23 17:05 UTC
**Please, provide a clear description what the bug is:**
The bonus from item should be passive,but is active and you don't benefit from the bonus in anyway.On the items says "on use" but can't be used and dont give the passive bonus either.In game bonus is "Use: Improves your chance to hit by 1%".
**Steps to reproduce the behavior with as much detail as possible:**

1.No passive benefit from item.
2. No use of the item "on use"
3. No benefit from the item bonus.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
34650
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment] 2023-11-24 13:48
Duplicate of #5225.

**Comment by Muigin** [comment] 2023-11-24 14:36
I've pushed a fix, and this should be cleared up on the next Tuesday maintenance. At that time, please delete your cache (WDB folder).

**Closed by Muigin** 2023-11-24 14:36 UTC
