### ISSUE TITLE
The Hardcore channel from chat-tabs turns itself on.

### ISSUE THREAD

**Issue by ImRainlog** [slowtorta/turtlewow-bug-tracker#5293] opened 2023-11-20 13:38 UTC
**Please, provide a clear description what the bug is:**

When trying to make a new chat-tab, it automatically toggles on the Hardcore channel option. When trying to disable the Hardcore channel, it will automatically check itself on after 5 seconds or so. By disabling the hardcore chat with `.hcchat leaves` it will disable it entirely, which is a solution, but, you will see that the same happens again. People like me want to have a HC chat-tab where it only displays those messages and another one, lest say GUILD where I want only GUILD messages to show.

**Steps to reproduce the behavior with as much detail as possible:**

1.Create a new chat-tab
2.Right-click the newly created tab and go to channel
3.Uncheck the Hardcore channel
4.Wait 5 seconds
5.Check the channel section on that chat-tab and the Hardcore option is checked again.

**Expected behavior. Describe how it should work:**
This should work normally, like it does with every other channel option and not turn itself on.

**Comment by cyaohiri** [comment] 2023-11-20 13:42
This is a known issue. As a temporary solution, you can use https://github.com/Lexiebean/TurtleHCFilter.

**Comment by twowTurtReynolds** [comment] 2023-11-21 03:25
Thanks cyao. Closing as dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5293

**Closed by twowTurtReynolds** 2023-11-21 03:25 UTC
