### ISSUE TITLE
Buggy transmogrification on Rod of Resuscitation

### ISSUE THREAD

**Issue by Floralys23** [slowtorta/turtlewow-bug-tracker#5966] opened 2024-01-10 18:05 UTC
**Please, provide a clear description what the bug is:**

Transmogrified Rod of Resuscitation ignores the sheathed behaviour of the staff it is transmogrified into.
![faulty mog](https://github.com/slowtorta/turtlewow-bug-tracker/assets/93597799/09d22d04-357b-4b59-8589-c8c52883c73e)

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire Rod of Resuscitation from Moroes in Lower Karazhan Halls.
2. Equip Rod of Resuscitation.
3. Speak to the Fashionista NPC and transmogrify Rod of Resuscitation to any other staff, such as Crescent Staff (reward from Leaders of the Fang).
4. Observe as your newly transmogrified staff hangs upside down from your back when in sheathed mode.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61454
Item: https://database.turtle-wow.org/?item=6505

**Expected behavior. Describe how it should work:**
The item should be in an upright position on your back when sheathed.

**Comment by twowTurtReynolds** [comment] 2024-01-10 18:06
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4932

**Closed by twowTurtReynolds** 2024-01-10 18:06 UTC
