### ISSUE TITLE
Engineering schematic thorium widget should be infinite supply

### ISSUE THREAD

**Issue by gabor-varga** [slowtorta/turtlewow-bug-tracker#5314] opened 2023-11-21 08:37 UTC
**Please, provide a clear description what the bug is:**

Hello there,

The [Schematic: Thorium Widget](https://database.turtle-wow.org/?item=16042) is supposed to be infinite supply (according to twow database) at [these ](https://database.turtle-wow.org/?npc=61439) [vendors](https://database.turtle-wow.org/?npc=5175). However, both of them seem to stock only one, and are constantly out of stock.

Some players are buying them out and putting them on AH with 20-50x markup. Although this is allowed, but I think it is detrimental to a healthy server, where players are supposed to not be blocked to progress through leveling professions.

The database labels these correctly to be infinite supply, so I can only assume this is a bug with the vendors. If it is supposed to be limited supply, please do consider making them infinite.

**Steps to reproduce the behavior with as much detail as possible:**

1. Try to buy Schematic: Thorium Widget
2. Should be infinite supply, but it sold out
3. Big sadge

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61439
Item: https://database.turtle-wow.org/?item=16042
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

The schematic should be infinite supply, as per turtle wow database.

**Comment by twowTurtReynolds** [comment] 2023-11-21 14:31
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e1579ee2-91e8-4d65-a221-74581e60ed78)
According to the database, and wowhead, these are indeed meant to be only stocked to 1 in vanilla.

I would suggest taking this post to the suggestion forums. I agree that these limited stock recipes can work fine on a server of 500 population, as Turtle was in the past, but the design breaks down with this many players.

Closing as not a bug.

**Closed by twowTurtReynolds** 2023-11-21 14:31 UTC
