### ISSUE TITLE
grounding totem can absorb 2 spells

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3106] opened 2023-03-28 19:34 UTC
**Steps to reproduce the behavior with as much detail as possible:**

1. shaman put down grounding totem
2. paladin use the paladin stum ability
3. it gets absorbed
4. because it doesnt do dmg, the totem does not die
5. now paladin uses holy schock
6. it also gets absored
7. becuase holy shock deals dmg the totem dies
8. would probably also work for other ccs like mage polymorth or warlock fear that dont kill the totem

**Expected behavior. Describe how it should work:**
the totem should absorb 1 spell then die, even if the spell dealt no damage

**Comment by Dragunovi** [comment] 2023-03-29 08:20
https://database.turtle-wow.org/?spell=8177
Spell description for clarity, closing for intended behavior.

**Closed by Dragunovi** 2023-03-29 08:20 UTC

**Comment by burner1024** [comment] 2023-03-30 14:33
Would be good to support with videos.
I suspect it pulsates to give the buff once per 10 secs, so depending on when the first spell was fired, the delay to getting the buff pulse could be 0-10 secs, but that shouldn't give unlimited suppression anyway, max would be 2 in a row.
How it worked in vanilla is another question, could be the same.
How it should work on Turtle is yet another question.
