### ISSUE TITLE
Quest: Removing Leper Leadership: choose from... one option

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#5565] opened 2023-12-11 19:37 UTC
**Please, provide a clear description what the bug is:**

When you complete the quest. NPC offers you to choose your reward. But offers only one option.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/be012607-0b74-4f3b-8e7e-4ce2ee96325d)

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete "Removing Leper Leadership"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61435
Quest: https://database.turtle-wow.org/?quest=40857

**Expected behavior. Describe how it should work:**

Offer al least 2 choices, or dont offer at all, just give Gubblewire Shield.

**Comment by twowTurtReynolds** [comment] 2023-12-11 19:59
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4785

**Closed by twowTurtReynolds** 2023-12-11 19:59 UTC
