### ISSUE TITLE
Sentinel's Glaive -- Possible Bug Fix.

### ISSUE THREAD

**Issue by Hearthshield** [slowtorta/turtlewow-bug-tracker#6330] opened 2024-02-22 04:53 UTC
**Please, provide a clear description what the bug is:**

The Sentinel's Glaive that you can purchase from Anisalah Starcaller in Darnassus. The weapon you can purchase so long as you have revered reputation. The off-hand is bugged to where it rests on the inside of the palm instead of the outside like the main hand, which ultimately causes clipping issues and looks silly overall. Is there a way to fix the off-hand version so that both main hand and offhand can look properly placed on the hand when drawn? Thanks.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip the weapon or something that uses the same or similar model model in the off-hand.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=60752

**Expected behavior. Describe how it should work:**

The model appears on the inside of the palm while equipped in the off-hand, whilst the weapon in the main-hand appears on the outside. The glaive regardless of main-hand or off-hand equipped should both appear on the outside portion of the hand.

**Comment by twowTurtReynolds** [comment] 2024-02-22 04:53
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5575

**Closed by twowTurtReynolds** 2024-02-22 04:53 UTC
