### ISSUE TITLE
Vagrants endeaor challenge for enchantment 

### ISSUE THREAD

**Issue by Zihuataneijo** [slowtorta/turtlewow-bug-tracker#5263] opened 2023-11-18 04:03 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. I am level 60
2. My enchantment cannot run because of Vagrants endeaor challenge
3. My enchanted weapon Agility material is gone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-18 04:24
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4829

watch that ticket and wait for it to be fixed before attempting this again, for the sake of your materials.

**Closed by twowTurtReynolds** 2023-11-18 04:24 UTC
