### ISSUE TITLE
Quest: Removing Leper Leadership: absurd reward dialog

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#6219] opened 2024-02-10 08:18 UTC
**Please, provide a clear description what the bug is:**

NPC offers one reward item twice.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/8eaaef9f-e962-47be-bc9c-05d766b9b350)

Quest: https://database.turtle-wow.org/?quest=40857

**Comment by twowTurtReynolds** [comment] 2024-02-10 09:37
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6207

**Closed by twowTurtReynolds** 2024-02-10 09:37 UTC
