### ISSUE TITLE
invocation of shattering 

### ISSUE THREAD

**Issue by gyytt123** [slowtorta/turtlewow-bug-tracker#5091] opened 2023-11-06 02:04 UTC
**Please, provide a clear description what the bug is:**
"invocation of shattering" lkh enchants have some problem.
**Steps to reproduce the behavior with as much detail as possible:**

1."invocation of shattering" cant enchant to my head or leg. 
2. it  shows"the items is a valid target". 
3.  but i can enchant to my shoulder. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zebouski** [comment] 2023-11-07 14:13
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4705 

Use the workaround provided in that ticket.

**Comment by Muigin** [comment] 2023-11-13 11:37
Duplicate of #4788

**Closed by Muigin** 2023-11-13 11:37 UTC
