### ISSUE TITLE
Paladin PvP glove Equip bonus not working

### ISSUE THREAD

**Issue by Rykenwolf** [slowtorta/turtlewow-bug-tracker#2114] opened 2022-09-13 08:39 UTC
**Please, provide a clear description what the bug is:**

The Paladin PvP set glove bonus is not working as described: "Equip: Increases Holy damage bonus of your Judgement of Crusader and Crusader Strike by 20". This has been tested for both Crusader Strike and Crusader Strike, no damage bonus is applied at all.

**Steps to reproduce the behavior with as much detail as possible:**

0. Start with no gloves equipped
1. Cast Seal of Righteousness
2. Attack target, note damage amount of Seal of Righteousness
3. Cast Seal of the Crusader
4. Cast Judgement on target
5. Cast Seal of Righteousness
6. Attack target, note increased damage of Seal of Righteousness due to Judgement of the Crusader on target
7. Equip "Knight-Lieutenant's Lamellar Gauntlets"
8. Repeat steps 3-5, then attack target. Observe as the Seal of Righteousness damage has not increased compared to wearing no gloves
9. Repeat process but apply Crusader Strike to target instead of Judgement of the Crusader. Observe that there is no increase in Holy damage with gloves equipped

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=16410

**Expected behavior. Describe how it should work:**

There should be a Holy bonus damage increase of 20 when the gloves are equipped andJudgement of the Crusader or Crusader Strike are applied.

**Comment by ratkosrb** [comment] 2022-11-18 08:00
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1990

**Closed by ratkosrb** 2022-11-18 08:00 UTC
