### ISSUE TITLE
Alliance - Suspicous Hoofprints Chain

### ISSUE THREAD

**Issue by Jadeypants** [slowtorta/turtlewow-bug-tracker#4045] opened 2023-07-29 01:37 UTC
**Please, provide a clear description what the bug is: Garran Vimes not offering "Report From Falgran" - this is the alliance side follow up to "Suspicious Hoofprints". I am 30 and friendly with Theramore meeting requirements on database, yes I did attempt clearing cache prior to making report**

**Steps to reproduce the behavior with as much detail as possible:**

1. complete Suspicious Hoofprints
2. be 30 and friendly with Theramore
3. attempt to acquire Report from Falgran

**IDs of affected creatures, items, quests or spells with a link to the relevant page: https://database.turtle-wow.org/?quest=40548**

NPC: https://database.turtle-wow.org/?npc=4944
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=40548
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work: upon completion of Suspicious Hoofprints, Vimes should have quest "Report from Falgran available**

**Comment by mmcar** [comment] 2023-12-21 19:27
The quest seems to have multiple other per-requesite quests, as described on the forum https://forum.turtle-wow.org/viewtopic.php?t=7518.
I can confirm this is the case having just made 'Report from Falgran' available on my hunter after completing the quest chains as mentioned in the forum post. These other quest chains are not mentioned in the database.turtle-wow.org entry for 'Report from Falgran'.

**Comment by twowTurtReynolds** [comment] 2023-12-21 23:31
Ah, I see. Not even wowhead displays this right!

Just a one off blizzlike exception to the prerequisite system. Closing as intended.

**Closed by twowTurtReynolds** 2023-12-21 23:31 UTC
Labels: Quest, Needs Replication
