### ISSUE TITLE
Bugged flightpath in Stonetalon Mountains

### ISSUE THREAD

**Issue by LWildschut** [slowtorta/turtlewow-bug-tracker#5649] opened 2023-12-19 13:52 UTC
**Please, provide a clear description what the bug is:**

While using the flightpath from the Dwarven area in Stonetalon Mountains to fly to Stonetalon Peak, the flight stopped at Astranaar. The two flightpoints are connected in Astranaar, and when arriving there, the flight got interrupted and the gryphon and I landed in the water. I can no longer interact with NPCs.

Logging out and logging back in resumes the flight point as intended.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Dwarven area in Stonetalon Mountain
2. Talk to the flightmaster
3. Fly to Stonetalon Peak
4. When flying over the Astranaar flightmaster, it stops and you land in the water while still mounted on the gryphon

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**

The flight should continue on to Stonetalon Peak without getting interrupted

**Comment by twowTurtReynolds** [comment] 2023-12-19 14:54
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4619

**Closed by twowTurtReynolds** 2023-12-19 14:54 UTC
