### ISSUE TITLE
Shaman Talent Spirit Armor causes Character panel Armor value to read too high after removing shield. Fixes with relog.

### ISSUE THREAD

**Issue by Jekan4eek** [slowtorta/turtlewow-bug-tracker#1796] opened 2022-08-02 12:38 UTC
**Please, provide a clear description what the bug is:**
Class: Shaman
New talent Spirit Armor not working
Armor is not added when equipping a shield on a hero. The talent states that when using a shield, a 10/20/30% armor bonus is given.
The talent does not add armor.
![image](https://user-images.githubusercontent.com/95292017/182596071-bfdde157-6e66-45fe-aae6-e3c43afc26b6.png)

![image](https://user-images.githubusercontent.com/95292017/182596640-007c732b-a388-4376-9769-e0babc29ec80.png)

10% that is added when equipping a shield, this gives a talent Ancestral Guardian. Indicated in blue on the screenshot

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Couldn't find this talent in the knowledge base

**Expected behavior. Describe how it should work:**

When a hero uses a shield, a percentage of the shield's armor should be added depending on the talent level.

**Comment by ratkosrb** [comment] 2022-08-04 07:59
I can't reproduce the issue. I have more armor with the talent than without.

**Comment by Jekan4eek** [comment] 2022-08-04 10:20
The problem seems to have been resolved. There is more armor when putting on a shield, but when you take off the shield and completely undress the character, the armor that was added due to the talent remains even on a naked character, when you log out, it is removed. It turns out that this is more of a visual bug.

**Comment by twowTurtReynolds** [comment] 2024-01-04 03:39
This has been confusing players. Perhaps we can maybe fix the lua in the client to accommodate for this talent.

**Comment by Giperion** [comment] 2024-02-19 18:40
Made a fix to that. You will now see how armor raised up, when you grab talent!

**Comment by Muigin** [comment] 2024-02-19 18:40
As stated above, will be fixed in the next maintenance.

**Closed by Muigin** 2024-02-19 18:40 UTC
Labels: Shaman, Client, Reproduced
