### ISSUE TITLE
GoA not stacking with other buffs

### ISSUE THREAD

**Issue by ahansen87** [slowtorta/turtlewow-bug-tracker#3686] opened 2023-06-14 10:44 UTC
Grace of Air totem not stacking with Elixir buffs that add agility. 

Steps to reproduce the behavior with as much detail as possible:

I've tried Elixir of Greater Agility and Elixir of the Mongoose.   Neither will add the 25 agility if Grace of Air is already present.  

Once Grace of Air is applied I will not gain any additional agility from any elixir.  Additionally I will only gain 52 agility if Grace of Air is applied after the elixir is present.  

IDs of affected creatures, items, quests or spells with a link to the relevant page:

https://database.turtle-wow.org/?spell=25360

https://database.turtle-wow.org/?spell=17538

https://database.turtle-wow.org/?spell=11334

Expected behavior. Describe how it should work:
I believe Grace of Air and other agility buffs should be stacking to provide the 77 and 25 for a total of 102 agility.

**Comment by balakethelock** [comment] 2023-07-19 15:21
Can confirm they don't stack. The strongest takes effect at any given time.

Personal testing results:
Base agi without any buffs: 200
+ 15 agi elixir : 215
+ grace of air: 277
+ both: 277

The bug **always happens**, not only when the buffs are applied in a specific order.

**Comment by Dragunovi** [comment] 2024-01-25 20:36
Removing item flag as the issue is related to the potion buff/class buff interactions and not the elixir items.

**Comment by ahansen87** [comment] 2024-01-26 12:01
8 months later and that's the only response?

**Comment by Dragunovi** [comment] 2024-01-26 14:33
Closing as the issue should be fixed as listed above.

**Closed by Dragunovi** 2024-01-26 14:33 UTC
Labels: Shaman, Spell
