### ISSUE TITLE
Rakklan's Targe - Shield incorrectly classified as an offhand?

### ISSUE THREAD

**Issue by itorch1** [slowtorta/turtlewow-bug-tracker#5972] opened 2024-01-11 00:28 UTC
**Please, provide a clear description what the bug is:**
Rakklan's Targe, quest reward from 'The Murloc Threat' is likely incorrectly classified as an offhand, when it should be a shield (Given the model, armor and block stat)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=41034

**Expected behavior. Describe how it should work:**
Should be classified as a shield

**Comment by twowTurtReynolds** [comment] 2024-01-11 00:49
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5668

**Closed by twowTurtReynolds** 2024-01-11 00:49 UTC
