### ISSUE TITLE
Towers in EPL not working?

### ISSUE THREAD

**Issue by Chuenzy** [slowtorta/turtlewow-bug-tracker#5045] opened 2023-11-03 13:51 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Activated pvp mode and captured a tower in EPL
2. The quest for capturing towers didn't update
3. I got a chat message that a tower was captured and received honor for it
4. The interface still says "Towers captured: 0" and my quest is at 0/1

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
my IG name is : Chuen

Quest: https://database.turtle-wow.org/?quest=
Quest: Bolstering Our Defenses

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-19 18:14
How did you activate pvp? IIRC having warmode doesnt cut it and the command /pvp must be ran.

**Comment by twowTurtReynolds** [comment] 2023-12-04 22:39
Thanks, closing as dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4715

**Closed by twowTurtReynolds** 2023-12-04 22:39 UTC
Labels: PvP, Needs Replication
