### ISSUE TITLE
South Gilneas no charge pathing

### ISSUE THREAD

**Issue by CBoy95** [slowtorta/turtlewow-bug-tracker#5589] opened 2023-12-13 21:23 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Use warrior charge ability on Spitecrest Naga* along the southern shore
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61407
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=100
Object: https://database.turtle-wow.org/?object=

Expectation of being able to charge enemy unit but error of "No path available" is displayed
*Naga referring to all Naga enemies not just those named "Spitecrest Naga"

**Comment by twowTurtReynolds** [comment] 2023-12-13 21:31
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4748

**Closed by twowTurtReynolds** 2023-12-13 21:31 UTC
