### ISSUE TITLE
Certain Zeppelins Are Invisible

### ISSUE THREAD

**Issue by PvtSkittles** [slowtorta/turtlewow-bug-tracker#5051] opened 2023-11-03 19:29 UTC
**Please, provide a clear description what the bug is:**

Sometimes when I go to certain zeppelins, they are invisible. This happens to me at the Tirisifal Glades to Grom'gol Zeppelin and the Thunder Bluff to Orgrimmar zeppelin. I can see other people board the zeppelins, however it looks like they are floating and if I try to board, I will fall and either take damage or die. I have cleared my WDB folder and have restarted my client, but the problem keeps happening. This does not happen with any of the boats.

**Steps to reproduce the behavior with as much detail as possible:**

1. It is random, I cannot reproduce 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should be able to see and board the zeppelin.

**Comment by twowTurtReynolds** [comment] 2023-11-19 18:10
dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4691

**Closed by twowTurtReynolds** 2023-11-19 18:10 UTC
