### ISSUE TITLE
Hunter Entrapment bugged

### ISSUE THREAD

**Issue by Khanz0** [slowtorta/turtlewow-bug-tracker#1777] opened 2022-08-01 07:19 UTC
The hunter talent entrapment is bugged. The "root" effect never happens no matter the trap

**Expected behavior. Describe how it should work:**
It should be a chance to root the npc affected by any trap. But the chance is 0% because the root never happens

**Comment by ratkosrb** [comment] 2022-08-02 04:31
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1786

**Closed by ratkosrb** 2022-08-02 04:31 UTC
