### ISSUE TITLE
Drape Of Nordrassil

### ISSUE THREAD

**Issue by laserchickendeluxe** [slowtorta/turtlewow-bug-tracker#5898] opened 2024-01-04 23:14 UTC
I got the drape of nordrassil from the hyjal 150 bright dream shard turn in and wanted to enchant it right away, guildie tried to apply "enchant cloak - 5 to all resistance" on it and it said to him "a cloak needs to be equipped" , he couldnt apply it on the cloak. I tried to unequip it and put it into the window again, same outcome.

this is the cloak i mean:
https://database.turtle-wow.org/?item=61753

**Comment by twowTurtReynolds** [comment] 2024-01-04 23:51
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5020
Please search before reporting.

**Closed by twowTurtReynolds** 2024-01-04 23:51 UTC

**Comment by laserchickendeluxe** [comment] 2024-01-04 23:52
im sorry was the first time i did a report
