### ISSUE TITLE
Invocation of Greater Protection will not enchant

### ISSUE THREAD

**Issue by Zelenefer** [slowtorta/turtlewow-bug-tracker#5280] opened 2023-11-19 14:00 UTC
I bought the enchant behind Karazhan and it won’t enchant any of my armor.

1. Walk behind kara
2. Buy the enchant
3. It works instantly

https://database.turtle-wow.org/?item=92006

It should enchant

**Comment by cyaohiri** [comment] 2023-11-19 14:06
Duplicate of #4788.

**Closed** 2023-11-19 14:29 UTC
