### ISSUE TITLE
Alliance, Horde, Steamwheedle Cartel reputation gives 0 reputation to actual alliance/horde/cartel factions.

### ISSUE THREAD

**Issue by istrizhakov** [slowtorta/turtlewow-bug-tracker#5145] opened 2023-11-09 11:21 UTC
**Please, provide a clear description what the bug is:**
Hello,
In the game existing 3 factions: 
https://database.turtle-wow.org/?faction=169 - Steamwheedle Cartel
https://database.turtle-wow.org/?faction=469 - Alliance
https://database.turtle-wow.org/?faction=67 - Horde

In some quests character could be rewarded with appropriate reputation, i.e https://database.turtle-wow.org/?quest=5502, https://database.turtle-wow.org/?quest=5502, https://database.turtle-wow.org/?quest=253 but this aren't increasing any reputation of the faction i.e. Darnassus, Stormwind, Orgrimmar, Undercity, Booty Bay and so on.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete any quest which gives Alliance/Horde/Steamwheedle Cartel reputation
2. Prior turn quest in check reputation change
3. Cry

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=5502 https://database.turtle-wow.org/?quest=5502 https://database.turtle-wow.org/?quest=253
Faction: https://database.turtle-wow.org/?faction=469 https://database.turtle-wow.org/?faction=169 https://database.turtle-wow.org/?faction=67

**Expected behavior. Describe how it should work:**

**Comment by Zmitrok1984** [comment] 2023-11-09 16:42
Before patch 1.17.0 such kind of quest give reputation to Alliance, give 1/4 amount of reputation per faction.
I means if quest give 200 reputation to Alliance, it give by 50 reputation to Darnassus, Stormwind, Ironforge and Gnomeregan

**Comment by ratkosrb** [comment] 2023-11-09 23:15
A Warden of the Horde (5502) does not have any reputation rewards assigned, I think you linked that quest by mistake. It does not say it gives Horde reputation.

Bride of the Embalmer (253) correctly gave me reputation for all dependent factions upon completing it.
![WoWScrnShot_111023_011352](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/f40170c1-2562-4e99-bc13-30396a861911)

**Comment by istrizhakov** [comment] 2023-11-10 09:42
I'm sorry, my bad, didn't know it's shared between all factions.

**Comment by twowTurtReynolds** [comment] 2024-02-09 05:23
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5081

**Closed by twowTurtReynolds** 2024-02-09 05:23 UTC
Labels: Couldn't reproduce, Faction
