### ISSUE TITLE
To Save a Soul Quest

### ISSUE THREAD

**Issue by Drethking** [slowtorta/turtlewow-bug-tracker#5096] opened 2023-11-06 06:53 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. completed https://database.turtle-wow.org/?quest=41125 Quest
2.  Nothing happened afterwards 
3.  According to database https://database.turtle-wow.org/?npc=61120 NPC supposed to spawn
4. Previously on other server https://database.turtle-wow.org/?quest=41124 Quest would autocomplete skipping this step

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=41125
https://database.turtle-wow.org/?npc=61120
https://database.turtle-wow.org/?quest=41124

**Expected behavior. Describe how it should work:**

Previously on PvE server https://database.turtle-wow.org/?quest=41124 Quest didnt exist and u went straight to clicking ashes to continue the quest chain to talk to Japan lady in Ratchet

**Comment by twowTurtReynolds** [comment] 2023-11-18 19:46
Indeed the Kamio stuff was all removed recently, and so this is a replacement quest? I will confirm how this is all supposed to go.

**Comment by twowTurtReynolds** [comment] 2023-11-20 05:15
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5096 . This quest is not a replacement, this was also meant to be removed it seems.

**Closed by twowTurtReynolds** 2023-11-20 05:15 UTC
Labels: Quest, Needs Replication
