### ISSUE TITLE
Cant loot Whipper Root Tuber in Felwood after clearing.

### ISSUE THREAD

**Issue by Metalben** [slowtorta/turtlewow-bug-tracker#5379] opened 2023-11-25 16:07 UTC
After cleaning https://database.turtle-wow.org/?item=11951 in Felwood , you get absolutely nothing

1. Clean dirty Whipper Root Tuber 
2.  Try to loot Whipper Root Tuber 
3.  "Nothing"

**Comment by Muigin** [comment] 2023-11-25 16:08
Duplicate of #5332

**Closed by Muigin** 2023-11-25 16:08 UTC
