### ISSUE TITLE
A Hero's Reward Quest

### ISSUE THREAD

**Issue by ChanceL1fe** [slowtorta/turtlewow-bug-tracker#3470] opened 2023-05-16 04:51 UTC
Usually the quest ends "A Hero's Reward"at Thrall, but apparently you made it custom and now I need to get a reward in the chest (hydraxis coffer), which is not available to me at level 25 (although the quest is green). Pfquest writes that the required level for passing the quest is 55.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?quest=40675

https://prnt.sc/sdvR5qEbBtF8

**Comment by redmagejoe** [comment] 2023-05-23 01:45
This quest does not in any way behave the way your UI is showing. I just did this quest yesterday, and it is indeed collected from Thrall.  This is working as intended.

@slowtorta Please close this.

**Closed** 2023-05-23 02:32 UTC
