### ISSUE TITLE
Troll priest shadowguard not working on ranged attack under shield

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#2009] opened 2022-08-26 13:16 UTC
**Please, provide a clear description what the bug is:**
the mob shooting arrows/ranged attack me. but shadowguard will not proc until my shield fades?
![image](https://user-images.githubusercontent.com/19348079/186912111-5299a87f-dae7-4b5f-ae01-aa01e3db785a.png)

melee attack will work /proc shadowguard even under shield. but the range/arrows
![image](https://user-images.githubusercontent.com/19348079/186912145-6cd001e5-a681-4713-929b-a03a6c04afb0.png)

**Steps to reproduce the behavior with as much detail as possible:**

1.apply shadowguard. apply power word:shield. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
shadowguard damage should proc under power word:shield against melee/ranged/spell attacks

**Comment by Tinyfin-github** [comment] 2022-09-02 10:12
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1603

**Closed by Tinyfin-github** 2022-09-02 10:12 UTC
