### ISSUE TITLE
high spell resist does not increase the chance for spells to be fully resisted.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#5537] opened 2023-12-09 00:16 UTC
**Please, provide a clear description what the bug is:**

spell resist does not increase the chance for spells to be fully resisted. Increasing spell resist should increase the chance spells are fully resisted but my testing has shown that having 300 spell resist against a level 60 target has no effect on whether or not these spells land on the target or not.  

**Steps to reproduce the behavior with as much detail as possible:**

1. Get 300 spell resist unbuffed on a character in my case shadow resist.
2. Have a friend cast corruption, curse of agony, shadow bolts at my character.
3. Binary spells landed 99% of the time. Shadowbolts (non binary spell) had reduced damage but landed just as often as binary spells, never fully resisting.

Reference:
https://classic-wow-archive.fandom.com/wiki/Resistance

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-09 00:21
Blizzlike: DoTs are treated far differently than direct damage spells, and resistance does a lot less to them. This should be working correctly here.

Please only show your testing for shadowbolts, that should work as per the table you have linked, where 300 Resist grants full resists 1 out of 4 times on average.

**Comment by ConcernedTurtler** [comment] 2023-12-09 00:30
> Blizzlike: DoTs are treated far differently than direct damage spells, and resistance does a lot less to them. This should be working correctly here.
> 
> Please only show your testing for shadowbolts, that should work as per the table you have linked, where 300 Resist grants full resists 1 out of 4 times on average.

DoTs are binary spells which is what I stated. They either fully resist or land on the target and do full damage in vanilla wow. My testing has shown that increasing spell resist does NOT increase their chance to be fully resisted which it should.

**Comment by ConcernedTurtler** [comment] 2023-12-09 00:56
Dots should have a chance to fully resist just like non-binary spells according to all the information I've looked into.  I've tested this several times naked with 0 talent on my warlock and my spells never fully resist on my priest who has 300 spell resist. They only do reduced damage.

**Comment by ConcernedTurtler** [comment] 2023-12-20 01:39
Sorry to bump this but it's been a week and I would appreciate if someone else could please take the time to corroborate my findings? I feel like spell resist should fuction correctly and that's not what I've observed in my tests.

**Comment by balakethelock** [comment] 2023-12-20 16:34
https://web.archive.org/web/20220502002708/https://docs.google.com/document/d/17ZJqka2Ve6GFFHR__YPQk0_5_vLhSrXUQ_Xq6K1ecxo/preview
not a bug

**Comment by twowTurtReynolds** [comment] 2023-12-20 18:48
> To restate when testing 300 shadow resist on my priest I did not observe an increase in full resists from any shadow spell. 

Oh. This is a known mechanic. https://github.com/vmangos/core/blob/development/src/game/Objects/Unit.cpp#L2542

Closing as not a bug.

**Closed by twowTurtReynolds** 2023-12-20 18:48 UTC
Labels: Further informations required, Core, Needs Replication
