### ISSUE TITLE
She Sells Sea Shells quest, uninteractable objects

### ISSUE THREAD

**Issue by itorch1** [slowtorta/turtlewow-bug-tracker#5971] opened 2024-01-10 23:54 UTC
**Please, provide a clear description what the bug is:**
She Sells Sea Shells, quest on Blackstone Island, mentions that the quest item should be lootable either from an object, or from an NPC. The sea shell objects are uninteractable however, leaving killing NPCs the only option for completing the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=41058
Quest: https://database.turtle-wow.org/?quest=41176
Object: https://database.turtle-wow.org/?object=2020069

**Comment by twowTurtReynolds** [comment] 2024-01-10 23:55
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5659

**Closed by twowTurtReynolds** 2024-01-10 23:55 UTC
