### ISSUE TITLE
Sulfuras, Hand of Ragnaros Proc Rate Unchanged after 1.17

### ISSUE THREAD

**Issue by Niqlo** [slowtorta/turtlewow-bug-tracker#4991] opened 2023-10-31 21:06 UTC
**Please, provide a clear description what the bug is:**
In the 1.17 itemization changelog, Sulfuras, Hand of Ragnaros was listed as having its proc rate increased from 0.7 ppm to 3.00 ppm. However, after 1.17 this does not seem to be the case, and I observe a proc rate closer to 0.5 ppm. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/109690174/e4567c3e-7828-4d09-8f8f-097a8a19a07c)

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip Sulfuras, Hand of Ragnaros
2. Melee a target until you have a decent data set
3. Calculate Proc Rate

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=17182

**Expected behavior. Describe how it should work:**
The Proc Rate should be 3 ppm, as listed in the 1.17 changelog.

**Comment by Creslin439** [comment] 2023-11-01 01:02
I also parsed this on a dummy for 10 minutes just auto attacks and come to the same conclussion, on 235 attacks it procced only 6.4% of the time which equates roughly with the original ppm of .7 and not 3 as was intended based on the patch notes.

**Comment by TheSyg** [comment] 2023-11-02 15:29
I second this, left the toon autoattacking a dummy for 30 minutes and got around .7 ppm

**Comment by twowTurtReynolds** [comment] 2023-11-19 23:35
Fix for this is currently live :)

**Closed by twowTurtReynolds** 2023-11-19 23:35 UTC
Labels: Item
