### ISSUE TITLE
(Quest) Pyrewood Ambush

### ISSUE THREAD

**Issue by martinkk0** [slowtorta/turtlewow-bug-tracker#4876] opened 2023-10-24 02:25 UTC
1. Reached the building where the NPC (Deathstalker Faerleia) for the quest is located
2. Help her kill all the enemies
3. She gave me the thanks and told me to pick a reward
4. picking a reward makes the music of completed quest plays but nothing else happens
5. The quest "?" symbol is grey but the quest is completed
6. I have free space in my bags for the reward

**Comment by Muigin** [comment] 2023-10-31 01:46
Duplicate of #1708

**Closed by Muigin** 2023-10-31 01:46 UTC
