### ISSUE TITLE
bug of invocation of shattering

### ISSUE THREAD

**Issue by babyloncx** [slowtorta/turtlewow-bug-tracker#5336] opened 2023-11-22 12:55 UTC
**Please, provide a clear description what the bug is:**
i can not use enchant invocation of shattering to Darkflame Helm, the system said "the item is not a valid target."

**Comment by cyaohiri** [comment] 2023-11-22 12:56
See #4788.

**Comment by Muigin** [comment] 2023-11-24 17:51
Duplicate of #4788

**Closed by Muigin** 2023-11-24 17:51 UTC
