### ISSUE TITLE
Nonfunctional Vendor: Argent Quartermaster Hasana

### ISSUE THREAD

**Issue by usedcars4cheap** [slowtorta/turtlewow-bug-tracker#1565] opened 2022-07-11 08:02 UTC
Argent Quartermaster Hasana: https://database.turtle-wow.org/?npc=10856

Does not sell Argent Dawn reputation items as expected. No vendor window is selectable when the dialogue window opens.

For example of expected behavior:
Alliance counterpart: https://database.turtle-wow.org/?npc=10857

**Comment by redmagejoe** [comment] 2023-02-21 13:38
I believe this NPC was deprecated pending updates to how custom rep features were implemented. At current, this NPC is working as intended, but should probably be removed until it is repurposed.

This can be closed.

**Comment by Haaxor1689** [comment] 2023-02-21 15:01
Will be fixed next update

**Closed by Haaxor1689** 2023-02-21 15:01 UTC
Labels: NPC
