### ISSUE TITLE
shadowform bug

### ISSUE THREAD

**Issue by ozzymagnum** [slowtorta/turtlewow-bug-tracker#4147] opened 2023-08-15 11:48 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. when using shadowform character is not going dark but stays in same texture
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
should be a darker texture

**Comment by GrizB37** [comment] 2023-08-15 11:53
Problem occurs when mounting in Shadow Form, only way to fix is drop and retake Shadow Form, or Relog. 

Known bug with. 1.12 vanilla client. Fixed in TBC. 

Maybe it can be fixed here?

**Comment by ozzymagnum** [comment] 2023-08-15 12:48
i look like a healer with this bug instead of a badass shadow priest

**Comment by cyaohiri** [comment] 2023-10-08 14:28
Duplicate of #3982, #2756, and #3149. I guess these can all be closed.

**Comment by Muigin** [comment] 2023-11-24 12:29
This has been fixed and will be pushed in our next client patch (1.17.1)

**Closed by Muigin** 2023-11-24 12:29 UTC
