### ISSUE TITLE
Invocation of Greater Protection (Kara10) not working

### ISSUE THREAD

**Issue by MadcookieBG** [slowtorta/turtlewow-bug-tracker#5404] opened 2023-11-28 01:24 UTC
The Invocation of Greater Protection is not working and can't be enchanted on head or leg item. Instead it displays a message saying "that item is not a valid target". I deleted WDB and relogged but still got the same result.

Screenshot: https://pasteboard.co/OKyVOBJ8wEdm.jpg
Item: https://database.turtle-wow.org/?item=92006

Vadrik - TurtleWoW (the RPPvE server)

**Comment by Muigin** [comment] 2023-11-28 03:26
Duplicate of #4788

**Closed by Muigin** 2023-11-28 03:26 UTC
