### ISSUE TITLE
The Stones That Bind Us - Unable to free their souls

### ISSUE THREAD

**Issue by Sprysea** [slowtorta/turtlewow-bug-tracker#5637] opened 2023-12-18 09:48 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Bring Servant of XX close to a stone of binding
2. Bring health down to 5% or whatever the number is
3. Unit is now frozen with "Spirit Shock", right click the stone of binding to release and then the "Spirit Shock" will be dispelled and instantly applied again, making the NPC unkillable.
      - Yes the NPC are being brought next to the stones within 5 yards of the stone. Still no go.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7669
Quest: https://database.turtle-wow.org/?quest=2681

**Expected behavior. Describe how it should work:**
Should be bringing the Servants close to the stone, then bring down their health. Then right click the stone and continue killing the npc. After which NPC should die.

**Comment by twowTurtReynolds** [comment] 2023-12-19 18:54
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3642

**Closed by twowTurtReynolds** 2023-12-19 18:54 UTC
