### ISSUE TITLE
Invocation of Shattering 

### ISSUE THREAD

**Issue by meekel4d** [slowtorta/turtlewow-bug-tracker#4730] opened 2023-10-13 20:32 UTC
**Please, provide a clear description what the bug is:**

The new karazhan enchants you get from the arcane essence and Karazhan rare reagent turn in near the church do not work on the gear slots that they're supposed to work on. I have not verified that this bug exist for all of the new Karazhan head and leg enchants, but Invocation of Shattering can only be applied to shoulders when the tooltip clearly says "Head and leg slot". 

**Steps to reproduce the behavior with as much detail as possible:**

1. Invocation of Shattering - New enchants from Kara for Head and legs, does not work when applied to head and legs.
2.  Enchant says "This item is not a valid target"
3.  The enchant works on shoulders like the new Hyjal shoulder enchant. However, this is supposed to be a head and legs enchant.

**Expected behavior. Describe how it should work:**

It should apply the enchant for +75 armor penetration to a head or leg slot. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/121821585/5869eb98-e505-4b9f-848d-5c79aca4d01f)

**Comment by ratkosrb** [comment] 2023-10-14 12:54
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4705

**Closed by ratkosrb** 2023-10-14 12:54 UTC
