### ISSUE TITLE
Gilneas targetting bug

### ISSUE THREAD

**Issue by Soph3X** [slowtorta/turtlewow-bug-tracker#5630] opened 2023-12-17 17:11 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Nagas in Gilneas on the beach are not targettable from range or with pets. 
2. Spitecrest Netter is NPC name
3. I am using a hunter and you cannot get pet to attack the majority of them unless right next to them

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-19 18:56
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5040

**Closed by twowTurtReynolds** 2023-12-19 18:56 UTC
