### ISSUE TITLE
Appearance not added to wardrobe - Hidden Shoulder

### ISSUE THREAD

**Issue by AyleeJenn** [slowtorta/turtlewow-bug-tracker#1331] opened 2022-04-20 19:45 UTC
**Please, provide a clear description what the bug is:**
The fashion npc that gives the quest for fashion coins has a store where players can buy "hidden shoulders" of all armor classes. Cloth, leather, mail and plate. I tried buying hidden cloth, hidden leather and hidden mail armor and I also tried equipping all three of them, starting with hidden cloth shoulders.

The hidden cloth shoulders were added to the wardrobe but the hidden leather and hidden mail shoulders were not added to the wardrobe.

The problem with this is that you will not be able to transform shoulder armor of other armor types than the single one that was added to the wardrobe.

An in-game ticket on this was sent and I was advised it is indeed a bug. I am listed it here only for the sake of coordination and tracking.

Thank you very much for all the hard work!!

**Steps to reproduce the behavior with as much detail as possible:** (NOTE: STRONGLY RECOMMENDED NOT TO REPRODUCE UNLESS YOU ARE A DEVELOPER OR GM!!!)

1. Play a class that can equip mail armor
2. Find the fashion npc and buy hidden shoulder armor of cloth, leather and mail type
3. try to equip all three and observe as only a single type gets added

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=51290
Item: https://database.turtle-wow.org/?item=83540
Item: https://database.turtle-wow.org/?item=83541
Item: https://database.turtle-wow.org/?item=83542
Item: https://database.turtle-wow.org/?item=83543

**Expected behavior. Describe how it should work:**
Instead of only a single armor type enlisting into the player's wardrobe, the various hidden shoulder armor types should each enlist into the player's wardrobe.

**Comment by Qix03** [comment] 2022-04-22 03:33
Unfortunately, this is by design. You can only collect the appearance of a single item with a given model. In the case of these hidden shoulders, they will also not be added if you have unlocked the Emperor's New Cloak, for instance, since the model is the same (in that there is no model). Hopefully the devs are willing to loosen the restrictions they placed on the transmogrification system since they first removed it.

I'll drop my petition here for anyone who feels strongly about seeing transmogrification improve.
https://forum.turtle-wow.org/viewtopic.php?f=14&t=2618

**Comment by AyleeJenn** [comment] 2022-04-25 05:42
At first I submitted an in-game ticket reporting it before thinking to also report it here for documentation and tracking purposes. I was told via in-game ticketing system that this is a bug and will be fixed as soon as possible.

Therefore I would think that it is a bug and would be fixed o.o I am not sure where you would have your information from that it is "by design". As far as I can tell from the response I was given it seems to be an unintended bug.

**Comment by slowtorta** [comment] 2022-04-25 08:55
This will be fixed on the next update. Make sure to clear your WDB.

**Closed** 2022-04-25 21:50 UTC
