### ISSUE TITLE
Wrath of Cenarius Underproccing.

### ISSUE THREAD

**Issue by dkmnllth** [slowtorta/turtlewow-bug-tracker#3351] opened 2023-04-29 01:55 UTC
**Please, provide a clear description what the bug is:**

Wrath of Cenarius proc appears to be bugged in its interaction with Consecration. The buff should proc at a rate of about 5% on spell hit of the initial tick of Consecration according to wowwiki (https://wowpedia.fandom.com/wiki/Wrath_of_Cenarius see notes) and a previously closed issue (#2754) that incited a Wrath of Cenarius fix on January 29th. This means that on groups of 20+ mobs, initial ticks of Consecration should cause near constant uptime of Wrath of Cenarius procs. However, I have found that when farming groups of 20+ mobs on my paladin, Wrath of Cenarius rarely procs off of initial Consecration ticks, only proccing once every 6 or 7 casts of consecration (with each initial tick hitting 20+ mobs).

**Steps to reproduce the behavior with as much detail as possible:**

1.Be paladin with Wrath of Cenarius equipped
2. Cast Consecration several times on 20~ mobs
3. Find that average proc rate does not match up with how often the item is supposed to proc.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21190
Spell: https://database.turtle-wow.org/?spell=25906
Spell: https://database.turtle-wow.org/?spell=20924

**Expected behavior. Describe how it should work:**

Wrath of Cenarius should proc at a rate of 5% on initial ticks of Consecration (video evidence: https://www.youtube.com/watch?v=na2NYAxhIrI see timestamps 1:18-1:38). This should result in near constant procs on each cast of Consecration that initially hits 20 or more targets.

Tested by Kareni

**Comment by dkmnllth** [comment] 2023-04-29 02:20
On further testing, I would also like to add that Wrath of Cenarius appears more likely to proc on initial casts of Consecration, whereas recasts of Consecration on the same targets never proc Wrath of Cenarius. Once the buff has procced off a cast of Consecration on a group of mobs, the buff does not seem to proc again on that same group. It should proc on any initial tick on any cast of Consecration regardless of if it has already procced or if the buff is already up.

**Comment by JuliaXperenza** [comment] 2023-04-29 04:54
i think that this is what turtle wants btw, the item is currently working like blizzlike, it is being treated as a single cast spell(initial cast of consecration) same as casting a frostbolt to proc it , old woc here was not Intentional and came from Light's hope,

![123](https://user-images.githubusercontent.com/121488241/235284247-1160771a-381c-43b6-8aea-30c66b40b8d5.png)

**Comment by dkmnllth** [comment] 2023-04-29 04:56
Yes and this is what's not happening, as I explained above. It is not working as blizzlike.

**Comment by dkmnllth** [comment] 2023-04-29 04:57
Right, procs are never guaranteed, however an average of once every 100+ mob hits on initial tick is *not* blizzlike

**Comment by dkmnllth** [comment] 2023-04-29 05:02
As I have explained at length above, the issue is that WoC is *not* proccing on initial casts of consecration, which is why I've made this bug report. It appear to only ever have a chance to apply on the first cast of Consecration on a mob, but not on any recasts, thus breaking the item and making it useless for paladin.

**Comment by Kuz-Shaman** [comment] 2023-05-09 17:40
I can confirm this and the same goes for d2 shaman setbonus. Both only proc around 2% of the time now while Testing when it should be 5% for both

**Comment by twowTurtReynolds** [comment] 2023-12-29 01:37
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/429fe0fe-1e59-4066-99fa-997739fcc429)
Turns out conscecration is currently proccing with every tick, not just the first. With this many mobs, I am seeing 9s permanently. I'm not sure if this was a TWoW dev intended change or not.

I did some single target testing, and the proc rate does seem to be around 5% per first tick conescrate (I had the no cooldown cheat on to spam it.)

Closing as can't reproduce the underproccing at all.

**Closed by twowTurtReynolds** 2023-12-29 01:37 UTC
Labels: Spell, Custom Content Polish, Needs Replication, Needs Blizzlike Proof
