### ISSUE TITLE
Pets prowl ignores Faerie Fire from mobs

### ISSUE THREAD

**Issue by melg8** [slowtorta/turtlewow-bug-tracker#4089] opened 2023-08-05 08:04 UTC
**Please, provide a clear description what the bug is:**
When Winterfall Pathfinder applies Faerie Fire spell to hunter's pet, hunter still can use prowl and pet will be in stealth while under debuf.

**Steps to reproduce the behavior with as much detail as possible:**

1. Attack Winterfall Pathfinder with hunter's pet which know prowl
2. Wait for Winterfall Pathfinder to apply Faerie Fire to pet.
3. Kill Winterfall Pathfinder, wait for pet to get out of combat.
4. Use prowl skill
5. Observe pet in prowl state while with Faerie Fire debuf is still on it.
![Looks like this](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/287368e7-cb3b-4f60-9aaf-5085e091047e)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7442
Spell: ttps://database.turtle-wow.org/?spell=16498
Spell: https://database.turtle-wow.org/?spell=24450

**Expected behavior. Describe how it should work:**
While under Faerie Fire spell pet should not be able to use prowl and become stealthed.
Additionaly investigate if druids Faerie Fire spell also doesn't prevent pet from becoming stealthed.

**Comment by ratkosrb** [comment] 2023-08-05 08:37
![WoWScrnShot_080523_113551](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/d62e5462-d393-4198-b1d0-b079c05cb0d4)

I can't reproduce the problem. It tells me "You can't do that yet" when attempting to activate Prowl on my pet with Faerie Fire on it.

**Comment by melg8** [comment] 2023-08-06 10:45
@ratkosrb Thanks for fast iteration!
I narrowed down problem in a few directions:
1) It only happens when using [pfUI](https://github.com/shagu/pfUI) addon.
2) Auto cast doesnt apply prowl automatically, manuall clicking applies it.

It goes through stages of errors:
In combat -> Not enough focus -> Goes into prowl when enough focus.
Before application of spell: 
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/4ea2d6ea-a061-4907-a59b-071f303a9ec7)

After spell is aplied, notice Log containst message about it, also pet window shows reduced amount of Armor on pet:
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/639d37f6-fe56-41a3-98f0-847b8df29c5c)

Log contains info about Cat gaining Prowl twice, while still under spell effect ( notice still reduced armor on cat).
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/16599015/2ad1cd5b-da77-4139-a0db-b082d517717c)

I dont know if it also affects behavior but i was using pet with rank 1 prowl (which i also linked in original report) and not rank 3.

So it seems that at least server side doesnt check for correct application of prowl, or client becomes really hallusinating whole thing(although i observe both log, buff icon and visual animation on cat being in stealth and slowed from it). Which gives advantages to players who use pfUi compared to others without it.

**Comment by melg8** [comment] 2023-08-11 06:02
Ping @ratkosrb  any updates?

**Comment by twowTurtReynolds** [comment] 2023-12-26 00:43
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/6adb857a-cebc-4009-8d99-c0640b7d8ffb)
Looks fixed now. No idea how you were doing this.

**Closed by twowTurtReynolds** 2023-12-26 00:43 UTC
Labels: Couldn't reproduce
