### ISSUE TITLE
Cannot summon Lord Valthalak in UBRS

### ISSUE THREAD

**Issue by Icfre** [slowtorta/turtlewow-bug-tracker#5912] opened 2024-01-06 05:28 UTC
**Please, provide a clear description what the bug is:**
I was unable to summon Lord valthalak in UBRS using the Brazier of Invocation. I have already summoned and defeated Lord valthalak in the past and this is my 2nd time trying to summon him.
**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Brazier of Invocation from tier 0.5 quest chain
2.  Clear UBRS up to the beast, including the beast
3.  Attempt to use the Brazier of Invocation in the beast's room, multiple spots within this room have been tested
4.  Attempting to use the brazier will usually error saying invalid target if something is targeted otherwise it would say requires haunted locus.

https://www.wowhead.com/classic/item=22057/brazier-of-invocation

**Expected behavior. Describe how it should work:**
Usually the brazier summons Lord Valthalak and you fight him

**Comment by twowTurtReynolds** [comment] 2024-01-06 12:17
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5892

**Closed by twowTurtReynolds** 2024-01-06 12:17 UTC
