### ISSUE TITLE
Guardians of the Altar not working

### ISSUE THREAD

**Issue by Deekinbc** [slowtorta/turtlewow-bug-tracker#1239] opened 2022-03-27 12:36 UTC
**Please, provide a clear description what the bug is:**
A quest in Winterspring requires escorting a Kal'dorei around the owlkin. After lighting 5 torches, you must light the altar to complet ether quest. However, clicking the altar does nothing, the escort remains channeling and it cannot be proceeded.
**Steps to reproduce the behavior with as much detail as possible:**

1. Take the quest, proceed to final part, attempt to click altar.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=4901
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Should activate, proceeding with RP dialogue and quest tag completion.

**Comment by slowtorta** [comment] 2022-03-28 20:27
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/227

**Closed by slowtorta** 2022-03-28 20:27 UTC
