### ISSUE TITLE
Trinket doesnt works

### ISSUE THREAD

**Issue by Emigrantt** [slowtorta/turtlewow-bug-tracker#5516] opened 2023-12-07 10:12 UTC
[Mossheart's Heart] Trinket doesnt works

1 dps - doesnt works (DEFENSIVE STAND war reduces damage - damage becomes 0) 

This Trinket  is for TANK, but in DEFENSIVE STAND  e - damage becomes 0

https://github.com/slowtorta/turtlewow-bug-tracker/issues/5517  the same situation is a big problem for TANK

**Comment by twowTurtReynolds** [comment] 2023-12-07 12:14
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4271

**Closed by twowTurtReynolds** 2023-12-07 12:14 UTC
