### ISSUE TITLE
Gnomeregan Reclamation Factility mobs has no loot

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#6208] opened 2024-02-08 21:51 UTC
**Please, provide a clear description what the bug is:**
There is no loot table for mob Malfunctioning Servitor

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill dozen of mobs
2. See that they never drop anything

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Malfunctioning Servitor](https://database.turtle-wow.org/?npc=61464)
[Corrosive Backup](https://database.turtle-wow.org/?npc=61465)
[XV - 81](https://database.turtle-wow.org/?npc=61466)

**Expected behavior. Describe how it should work:**
They should drop some loot

**Comment by twowTurtReynolds** [comment] 2024-02-08 22:08
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4906

**Closed by twowTurtReynolds** 2024-02-08 22:08 UTC
