### ISSUE TITLE
Void Walker Consume Shadows working as intended?

### ISSUE THREAD

**Issue by Bogy75** [slowtorta/turtlewow-bug-tracker#4217] opened 2023-08-27 08:41 UTC
**Please, provide a clear description what the bug is:*Void Walkers Consume Shadows doesnt always activate but uses the mana cost.*

**Steps to reproduce the behavior with as much detail as possible:*Can the spell Consume Shadows "miss"? Then it is what it is but it can miss like 3 times in a row but uses the mana cost so Void Walker is almost empty on mana for nothing.*

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:*17854/consume-shadows*

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=17854/consume-shadows
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:*While out of combat the spell should heal the Void Walker*

**Comment by twowTurtReynolds** [comment] 2023-12-07 00:20
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2935

**Closed** 2023-12-07 01:18 UTC
