### ISSUE TITLE
Rich Thorium isn't giving enough hits and breaks too early

### ISSUE THREAD

**Issue by Zangatsu** [slowtorta/turtlewow-bug-tracker#251] opened 2021-08-14 21:56 UTC
I've seen several other players complain about this as well.  After a patch not too long ago, Rich Thorium no longer seems able to even give the maximum of 5 ore hits.  It very often breaks after 3 hits, and in fact sometimes it breaks after 2 hits, which is almost proof of a bug.  Rich Thorium is supposed to always give 3 to 5 hits and I highly doubt another player has been out here striking all these thorium veins just once. After a lot of mining I have not gotten a single 5 hit.  It seems to be broken.

**Comment by GrenderG** [comment] 2021-08-19 14:24
Working as intended, Rich Thorium Vein should be able to be mined between 2 and 4 times.

**Comment by Zangatsu** [comment] 2021-08-19 21:22
Are you shitting me?  Working as intended?  https://vanilla-wow-archive.fandom.com/wiki/Thorium_Ore#Rich_Thorium_Veins
[https://static.wikia.nocookie.net/ucp-internal-test-starter-commons/images/a/aa/FandomFireLogo.png/revision/latest/zoom-crop/width/200/height/200?cb=20210713142711]<https://vanilla-wow-archive.fandom.com/wiki/Thorium_Ore#Rich_Thorium_Veins>
Thorium Ore | Vanilla WoW Wiki | Fandom<https://vanilla-wow-archive.fandom.com/wiki/Thorium_Ore#Rich_Thorium_Veins>
Thorium OreItem Level 40Disenchants into:Not disenchantableSell Price: 250 Thorium Oreis mined from various Thoriumveins, with a minimumminingskill of 230. This rare metal combines the weight of lead with the strength of steel. Orcs prize it for weapons because the extra weight allows a skilled user to strike with more force. Thorium armor is amazingly heavy and strong-only adamantine pierces ...
vanilla-wow-archive.fandom.com

________________________________

**Comment by Zangatsu** [comment] 2021-08-19 21:40
I understand bug-fixing is strenuous and difficult and you'd rather avoid touching issues that could cause a chain reaction of further issues.  But you closed my ticket instead of doing a 45 second wowwiki search on the correct state of how Rich Thorium should behave.  I will not be reporting any more bugs.
________________________________

**Comment by redmagejoe** [comment] 2022-07-02 21:13
This issue persists and needs to be reopened. Rich Thorium Veins should give 3-5 taps. They are an exception to the usual ore vein convention of 2-4, just like Small Thorium Vein is 1-2 taps.

**Comment by redmagejoe** [comment] 2023-01-16 22:43
Bumping this. Quick and easy fix, so let's put this at the top of a to-do list, please.

**Comment by Kruxis** [comment] 2023-01-17 22:30
Heyo! Thanks for the report, it's been a while but we'll look into it soon.

**Comment by Kruxis** [comment] 2023-01-17 22:30
Heyo! Thanks for the report, it's been a while but we'll look into it soon.

**Comment by Kruxis** [comment] 2023-01-17 22:44
Should be fixed now. If you get less than 3 hits someone else mined it too.

Fix will be applied on next server restart. 


Save travels!

**Closed by Kruxis** 2023-01-17 22:44 UTC
