### ISSUE TITLE
Entrapment hunter talent not working

### ISSUE THREAD

**Issue by dole555** [slowtorta/turtlewow-bug-tracker#1793] opened 2022-08-02 07:48 UTC
**Please, provide a clear description what the bug is:**
The entrapment talent is not working since the patch. it does not proc the entrapment effect on mobs from any of the traps.
**Steps to reproduce the behavior with as much detail as possible:**

1. Spec entrapment.
2. Place immolation / frost / explosive trap and have a mob walk through it.
3. See that no entrapment debuff occurs on the mob.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=19390

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment] 2022-08-02 08:15
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1786

will be fixed next update

**Closed by ratkosrb** 2022-08-02 08:15 UTC
