### ISSUE TITLE
Damaging On-Hit effects procced by Sap (and Gouge) break stealth and remove Sap

### ISSUE THREAD

**Issue by nyanyaho** [slowtorta/turtlewow-bug-tracker#3183] opened 2023-04-06 11:23 UTC
**Please, provide a clear description what the bug is:**
Damaging On-Hit effects like instant poison, Perdition's blade etc. applied by Sap (and Gouge) take the rogue out of stealth and remove the CC effect instantly. This was introduced after the latest fix to sap not proccing effects at all. It makes things even worse for rogues and makes certain weapons non-viable for PvP or CCing in PvE.

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip a weapon with a damage proc in the main hand.
2. Use Sap 
3. If the damage effect procs, the Sap will instantly be removed and the rogue taken out of stealth, even with the Improved Sap talent.

**Expected behavior. Describe how it should work:**
Damaging procs should not take the rogue out of stealth or remove sap.
This is the original vanilla behavior. 

A quick workaround would be to once again remove the ability of Sap and Gouge to apply on hit effects. 
This current behavior leaves rogues unable to use some of the most popular PvP weapons in PvP and is much worse than not being able to proc effects through Sap.

**Comment by cyaohiri** [comment] 2023-04-06 11:24
Duplicate of #3168.

**Comment by nyanyaho** [comment] 2023-04-06 11:30
> 

This is not a duplicate as the other issue insinuates that the correct behavior is sap and gouge not proccing any damaging effects, which isn't true.

**Closed** 2023-04-06 23:29 UTC
