### ISSUE TITLE
Bug with quest "Race Against Time!"

### ISSUE THREAD

**Issue by Lockyrion** [slowtorta/turtlewow-bug-tracker#5953] opened 2024-01-09 18:10 UTC
**Please, provide a clear description what the bug is:**
I take quest but nothing happens, racing car doesn't appear.
I just stand next to NPC.
Timer is ticking, and after 1 min 50 sec quest fails.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4507
Quest: https://database.turtle-wow.org/?quest=50316

**Expected behavior. Describe how it should work:**
I take quest and get in racing car.
I do one lap, complete quest, and get Daisy's Gift Box as reward.

**Comment by twowTurtReynolds** [comment] 2024-01-09 18:14
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813

**Closed by twowTurtReynolds** 2024-01-09 18:14 UTC
