### ISSUE TITLE
bug problem with Snowball

### ISSUE THREAD

**Issue by Horacius11** [slowtorta/turtlewow-bug-tracker#5789] opened 2023-12-27 21:11 UTC
Hello GM my name in the game is Horacius and my gmail is smxagerardo@gmail.com. I died while trying to kill snowball. i was resurrected and when i returned to the cave the wolf had already died and the mission was not told to me.( I use google tranlate sorry)

Quest Peace comes at a price:
https://database.turtle-wow.org/?quest=50330 

Item The Great Sack of Winter Veil:
https://database.turtle-wow.org/?item=61089

**Comment by twowTurtReynolds** [comment] 2023-12-27 21:15
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5617 and https://github.com/slowtorta/turtlewow-bug-tracker/issues/5709

Same answer applies.

**Closed by twowTurtReynolds** 2023-12-27 21:15 UTC
