### ISSUE TITLE
Can't apply karazhan leg/head enchant

### ISSUE THREAD

**Issue by TayoTeeko** [slowtorta/turtlewow-bug-tracker#5242] opened 2023-11-17 01:49 UTC
**Please, provide a clear description what the bug is:**
I cannot apply the invocation of shattering to my bloodfang leg

**Steps to reproduce the behavior with as much detail as possible:**

1. i right click the invocation of shattering in my bags
2. i try to apply to them to my bloodfang legs
3. it says 'that item is not a valid target'

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Zebouski** [comment] 2023-11-17 01:54
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788

**Closed** 2023-11-17 14:19 UTC
