### ISSUE TITLE
Bug with Improved Ghost Wolf Talent

### ISSUE THREAD

**Issue by Suksiboksi** [slowtorta/turtlewow-bug-tracker#1836] opened 2022-08-06 18:47 UTC
The Enchancement Shaman talent Improved Ghost Wolf should decrease the cast time of the Ghost Wolf by 2 seconds to instant cast. Nonetheless, after picking both ranks of the talent, the Ghost Wolf still has 1 second cast time. 

I believe this is caused by me selecting the first rank of the talent before I had learnt the spell. Therefore:

1. Pick the first rank of the improved Ghost Wolf talent before you achieve level 20 and can learn the spell.
2. Learn the spell at the trainer. (After learning the spell, the cast time was at 2 seconds)
3. Pick the second rank of the talent, and the cast time goes to 1 second.

IDs of affected spells:

https://database.turtle-wow.org/?spell=2645 Ghost Wolf
https://database.turtle-wow.org/?spell=16262 Talent rank 1
https://database.turtle-wow.org/?spell=16287 Talent rank 2

How this should work is that whether one picks the talent before or after learning the Ghost Wolf spell should have no impact on whether the talent actually has an effect or not.

![Ghost Wolf Talent](https://user-images.githubusercontent.com/110740737/183262097-5ac3d19b-74ad-4f7e-92d9-f250c148a2df.jpg)

![Ghost Wolf Tooltip](https://user-images.githubusercontent.com/110740737/183262089-45661f46-868f-4e9e-9973-fefe52c52d2b.jpg)

**Comment by cyaohiri** [comment] 2022-09-03 19:55
It's working as intended and this can be closed.

In vanilla, Ghost Wolf has a 3 second casting time, so two points in the talent bring that down to 1 second. It wasn't until TBC that the basic cast speed was 2 seconds and you were able to make it instant with those two talents.

**Comment by sailor4242** [comment] 2022-10-04 18:59
In classic wow it was instant with 2 points spent (probably 2 sec default cast time), can you please consider an improvement of that sort for this spell?
Its' a shame that shamans have to spent 2 points and still not have it instant.

**Comment by Velite12** [comment] 2022-10-04 19:13
![image](https://user-images.githubusercontent.com/45871932/193904704-4f17766d-6e68-4611-9414-c28dfc7d917f.png)
![image](https://user-images.githubusercontent.com/45871932/193905824-aff05ea9-3c75-4d78-8afc-f00d7848935a.png)
Ghost wolf does not become instant cast with the talent. Closing this as resolved.

**Closed by Velite12** 2022-10-04 19:13 UTC
