### ISSUE TITLE
Ignite stacks reset when a crit lands after two ticks of damage but before the 4s ignite debuff has fallen off

### ISSUE THREAD

**Issue by Ormember** [slowtorta/turtlewow-bug-tracker#5474] opened 2023-12-02 08:17 UTC
**Please, provide a clear description what the bug is:**
Firemage spam fireballs. When he crit 2 fireballs consecutively, debuff not stack.
**Steps to reproduce the behavior with as much detail as possible:**

1. Spam crits nonstop fireballs with Ignite spec'd 5/5
2. Debuff not stack (DoT of ignite lasts 4 sec, cast fireball 3 sec)
3. Feel disappointed that your spec sucks.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=12654
Spell: https://database.turtle-wow.org/?spell=25415

**Expected behavior. Describe how it should work:**
When crit 2 fireballs consecutively, ignite must get 2 stack (max 5 stack)

Video:
https://www.youtube.com/watch?v=VwzYRVjukbM

**Comment by cyaohiri** [comment] 2023-12-03 21:15
Try casting when closer to the target and see if that helps.

**Comment by twowTurtReynolds** [comment] 2023-12-04 02:44
Replicated. I can only get ignite to consistently stack by spamming rank 1 or talented rank 2.

It looks like the fix for https://github.com/slowtorta/turtlewow-bug-tracker/issues/374 allowed the ticks to continue as they both stack up and refresh, but now there has become a time window where ignite has not fallen off yet but a new crit will wipe the current 5 stack and instead start a new ignite from stack 1.

To replicate this, ran `.aura 23433` on myself twice for 100% spell crit, then I stacked ignite to 5 with talented rank 2, and then I start to slow down and try to cast every 2.1s or so, and eventually two ticks of ignite will occur before a cast lands again, and this is where ignite will fail to stack and instead forces a new stack.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a61b9f49-f07a-4cc7-9fb4-bf527f110316)

It is important to note how the debuff doesn't fall in this picture, but the stacks are indeed reset.

**Comment by cyaohiri** [comment] 2023-12-20 21:23
I'm unable to replicate it on VMaNGOS. As long as I land a crit while Ignite is still on the target, a stack is added.
An important difference is that the default Ignite has two ticks, and the first one happens 2 seconds after Ignite is applied, whereas on Turtle WoW, Ignite has has three ticks, and the first one happens the moment Ignite is applied, as can be seen in the screenshot above.
If this is intended, the talent will have to be updated as well since Ignite doesn't do 40% of the damage, but 60%, as it has three ticks instead of two.

**Comment by cyaohiri** [comment] 2023-12-20 21:42
I don't know if this is relevant, but I've noticed that Ignite is sometimes applied about 700 ms after the spell lands. Most of the time it's around 200 ms. The server is hosted locally.
https://streamable.com/7lpc9h

**Comment by BahamutxD** [comment] 2023-12-28 16:54
Right now

1/ You **can** stack ignite by casting 1.5s crit Scorchs without issue.  Ignite damage will go up as stacks grow.

2/ You **can't** stack ignite by casting 2.3s (Mindquickening gem) Fireballs even if they all crit. Ignite damage won't add as you won't be getting stacks of Ignite. 

Needs more testing but I can assume that the "stack window" is only 2 seconds after applying an ignite, despite the DoT still going on for 2 extra seconds/still having a damage tick reamining.

The expected behaviour would be that ignite is applyed instantly when a fire spell crits and then it ticks twice after 2 and 4 seconds. If any ignite is applyed while ignite is already up, the ignite is refreshed (back to being alive for 4 more seconds) and the damage pool from that crit is added to the existing ignite damage pool.

**Comment by Ormember** [comment] 2024-02-04 20:53
Is there any information on this issue?

**Comment by BahamutxD** [comment] 2024-02-26 16:18
After testing this for some time in raid and solo/group content I can tell ignite is not working as it should right now. 

The major drawback is that the amount of times it resets tick damage because of the bugged refresh window makes the damage from Ignite significally lower than it should. Note that while the debuff may still be up on the target, the damage will reset at times. 

For solo content there's some notable side effects aswell. While being solo you should be able to stack your own ignite during that 4 second window but that is not working right now and you'll only achieve stacks if you manage to crit constantly with Scorch (1.5s cast no travel time) or Blastwave/Fireblast (instant casts-no travel time)

**This is how ignite should work.**

-  Any fire spell critical hit from a mage with Ignite talent (5/5 we have 100% chance) should apply an ignite debuff on the target that will damage the target for 40% of the damage made by that spell and this debuff will tick twice after 2 and 4 seconds doing half of that mage evenly split (so 20% damage from the crit per tick). 

In TWoW Ignite ticks 3 times at 0-2-4 seconds for 20% each (60% total) <- Either wrong tooltip due to undocumented changes on this talent or bugged behavior.  The first tick shouldn't be happening.

- The ignite debuff will show on the target the moment a crit lands and will dissapear 4 seconds later (right after 2nd tick) if no other crits happen.

In TWoW the debuff is gone after the third tick during the first ignite. If it refreshes it will go after 2 ticks. This is the correct behavior.

So if a mage crits for 2400 damage, the ignite should tick for 480 twice (40% of 2400 = 960 -> 480 per tick) 2 and 4 seconds after crit.
In TWoW if a mage crits for 2400 damage, the ignite ticks for 480 three times. Instaly and 2 and 4 seconds after.

- If the mage or any other mage with Ignite talent (lets assume 5/5 again for 100% chance) - crits on the target with an ignite debuff up, the damage from that crit will add to the original Ignite and the Ignite debuff timer will reset (so it ticks twice again)

-  An important note here is that refreshes won't change the pace Ignite ticks come - those will keep coming every 2 seconds after the original crit/ignite started. So several crits between crits will add all that extra damage to the tick during the next tick.

So if the same mage/other mage crits for 3000 ( 40% of 3000 =1200 -> 600 per tick) on that same target while Ignite debuff is up, the new ignite will add to the original extending the duration to allow 2 new ticks happen and the tick damage added to the original tick damage.

If 2 crits happen between ticks, the damage from each crit will add. So if 2 mages crits for 3000 (600 per tick each mage), that extra 1200 per tick will add to the ignite on the next tick.

In TWoW this may not happen, the stack window is either bugged or shorter than intended/debuff duration. So despite having Ignite the tick damage may reset to the newly added tick damage as if the ignite debuff dropped from the target for a moment.

This process will keep happening until 5 stacks of Ignite are reached. At that point added damage from new Ignites won't add but they will refresh the duration. Whenever Ignite refreshes, the damage from "old ticks" will prevail while the Ignite is alive. To say it another way, the original crit and its consequent 2 ticks won't drop from the ignite tick after those tick twice. For aslong the ignite is up, the damage keeps adding up to 5 stacks of ignite.

**Comment by pepopo978** [comment] 2024-02-26 22:37
Totally guessing here since I don't know how much you've changed from vmangos and what @jameyboor did for https://github.com/slowtorta/turtlewow-bug-tracker/issues/374 but would love to see this fixed:

Perhaps a call to `Aura::Update` was added before the `bool reapplyIgnite = igniteAura->GetAuraTicks() >= igniteAura->GetAuraMaxTicks();` check in `HandleDummyAuraProc` to make sure damage was happening on ignite refresh?  Don't think it fully explains the 3 ticks when there is no ignite aura yet but would explain the refresh window going from 4s -> 2s

Other thing I noticed was this boolean is confusing as it is getting inverted 
```
bool reapplyIgnite = igniteAura->GetAuraTicks() >= igniteAura->GetAuraMaxTicks();
if (!reapplyIgnite)
{
    ...
    // Refresh Ignite Stack
    igniteHolder->Refresh(igniteAura->GetCaster(), target, igniteHolder);
}
```
makes me wonder if that led to a mistake

**Comment by Muigin** [comment] 2024-02-29 03:18
This should be fixed in the next maintenance.

**Closed by Muigin** 2024-02-29 03:18 UTC
Labels: Mage, Spell, Core, Reproduced, Correct on VMaNGOS
