### ISSUE TITLE
Blue Dragonscale Set's 4 piece bonus doesn't proc from Flametongue Weapon and on-hit effects.

### ISSUE THREAD

**Issue by BloodRaven0** [slowtorta/turtlewow-bug-tracker#5540] opened 2023-12-09 09:48 UTC
**Please, provide a clear description what the bug is:**
The Blue Dragonscale Set's 4 piece bonus does not proc from Flametongue Weapon or effects like "Adds 3 Lightning Damage to your melee attacks" (like from Thunder Lizard's Hide), even though the wording in its effect is identical to Blade of Eternal Darkness, which DOES proc from these effects.

Blue Dragonscale Set text: "Chance on landing a damaging spell to deal 75-85 Arcane damage..."
Blade of Eternal Darkness text: "Chance on landing a damaging spell to deal 100 Shadow damage..."

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip all 4 pieces of Blue Dragonscale Set and cast Flametongue Weapon and/or equip Thunder Lizard's Hide.
2. Go whack a dummy for an hour.
3. See that no arcane damage procs have occured.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=65015
https://database.turtle-wow.org/?item=15048
https://database.turtle-wow.org/?item=20295
https://database.turtle-wow.org/?item=15049

https://database.turtle-wow.org/?spell=7711
https://database.turtle-wow.org/?spell=16615
https://database.turtle-wow.org/?spell=16342

**Expected behavior. Describe how it should work:**
It should proc from these effects. It's a much weaker version of Blade of Eternal Darkness' effect, as it does not give mana and deals lower damage. As it is currently, the debuff can't stack more than once, because it only procs from a shaman's shocks and doesn't proc often enough to refresh it. Druids are always gonna be better at pulling off this build anyway, due to their insane attack speed in cat form, so let us Spellhancement shamans compete at least a little bit with this set. Also indirectly buffing arcane mages and boomkins is nice, since they are not meta, even if it's just 30 damage per arcane spell.

**Comment by twowTurtReynolds** [comment] 2023-12-09 12:10
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4849

**Closed by twowTurtReynolds** 2023-12-09 12:10 UTC
