### ISSUE TITLE
Mage Trainer - ALAH'THALAS

### ISSUE THREAD

**Issue by TAW2618** [slowtorta/turtlewow-bug-tracker#5687] opened 2023-12-21 01:54 UTC
**Please, provide a clear description what the bug is:**
When reaching level 10 to get mage quest from mage trainer within Alah'thlas, the option to train spells is no longer possible even if the quest is dropped. 

**Steps to reproduce the behavior with as much detail as possible:**

1. 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2024-01-09 14:03
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5727

**Closed by twowTurtReynolds** 2024-01-09 14:03 UTC
Labels: Mage, NPC, Needs Replication
