### ISSUE TITLE
Whip Lashers using Lash of Pain much more after thursday restart that fixed kara

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#6104] opened 2024-01-26 02:59 UTC
Lashers in DME (https://database.turtle-wow.org/?npc=13022) are now using lash of pain when the back is exposed always, instead of sometimes, with a bad tick of the back being turned giving 10+ shadow damage backstabs.
While this is dealable, it should proobably be looked at.

**Comment by twowTurtReynolds** [comment] 2024-02-09 02:09
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6105

**Closed by twowTurtReynolds** 2024-02-09 02:09 UTC
