### ISSUE TITLE
Knight-Lieutenant's Lamellar Gauntlets bonus to crusader strike/judgement doesnt work

### ISSUE THREAD

**Issue by Mzheldin** [slowtorta/turtlewow-bug-tracker#2479] opened 2022-11-18 15:12 UTC
Knight-Lieutenant's Lamellar Gauntlets (https://database.turtle-wow.org/?item=23274) bonus to crusader seal/strike doesnt increase incoming holy damage. 
I tested this bonus
1. on dummy (60/boss) 
2. with Seal of Righteousness (because it has plain damage) 
3. with and without gauntlets, 
4. 5 stack of crusader strike or active judgement of crusader debuff on dummy and same spell damage bonus from gear in both cases. In result, I had same damage from Seal of Righteousness in with and without this item.

Expected behavior: holy damage  (Seal of Righteousness for example), inflicted to target (dummy) which have crusader strike or judgement of crusader debuff, with geared Knight-Lieutenant's Lamellar Gauntlets, is greater than without it.

**Comment by ratkosrb** [comment] 2022-11-18 16:03
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1990

**Closed by ratkosrb** 2022-11-18 16:03 UTC
