### ISSUE TITLE
Any druid spell can trigger Improved Starfire. Even friendly ones.

### ISSUE THREAD

**Issue by Sygmoond** [slowtorta/turtlewow-bug-tracker#1773] opened 2022-08-01 03:10 UTC
**Please, provide a clear description what the bug is:**

As the title says, even if you don't have the talent, Improved Starfire can trigger off of Moonfire cast, Moonfire procs, Wrath and even healing spells used on your party and yourself.

**Steps to reproduce the behavior with as much detail as possible:**
As an example, you can:
1.- Cast Rejuvenate on yourself several times, you're sure to proc it eventually.
2.- Enter combat with a high level mob or a Dummy, cast Wrath or Moonfire or Insect Swarm sometimes until it triggers.
3.- It also triggered a couple of times with Soothe Animal, so I do not discard the possibility of it being able to stun with Roots or Hibernate.

**Comment by burner1024** [comment] 2022-08-01 16:31
doesn't happen for me

**Comment by Sygmoond** [comment] 2022-08-01 17:43
I can stream it, don't know how to record it, but it kept happening to me yesterday, it's either that, or a bug with the talents because I used to be spec'd as balance.

**Comment by Sygmoond** [comment] 2022-08-01 17:51
https://drive.google.com/file/d/1rw-4EA4nfWYpGFnNda8xEYyjxhulS9nv/view?usp=sharing

**Comment by Tinyfin-github** [comment] 2022-09-02 10:05
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1712

**Closed by Tinyfin-github** 2022-09-02 10:05 UTC
