### ISSUE TITLE
Shimmering Flat Practice race quest Bug

### ISSUE THREAD

**Issue by KedoNO** [slowtorta/turtlewow-bug-tracker#5853] opened 2023-12-31 10:10 UTC
**Please, provide a clear description what the bug is:**
In the Shimmering Flat, Thousand Needles, I completed the gnome quest for race practicing.
When I needed to complete the goblin race practice quest (Goblin Engineering At Its Finest!) I completed it with a player, but then I abandoned it before speaking with the goblin because the other player needed help with a second practice race quest.
So I abandoned and retook it from the goblin (Jizzle Grikbot), but couldnt join the queue for the practice race anymore (with Dolores, Race Starter girl).
Now I can only join gnome side for real races, cant join goblin ones.

**Steps to reproduce the behavior with as much detail as possible:**

1. "Gnomes Are Genuine Inventors" Quest completed and spoken to the gnome Gregor Fizzwuzz
2. "Goblin Engineering At Its Finest!" Quest completed, abandoned it after the practice race, didn't speak to goblin Jizzle Grikbot
3. Retook the same quest "Goblin Engineering At Its Finest!"
4. Can't join practice race with Dolores, Race Starter girl.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Goblin NPC: https://database.turtle-wow.org/?npc=50521
Goblin Quest: https://database.turtle-wow.org/?quest=50310
Gnome NPC: https://database.turtle-wow.org/?npc=50522
Gnome Quest: https://database.turtle-wow.org/?quest=50312

**Expected behavior. Describe how it should work:**
I was expecting to be able to rejoin the practice race queue in order to complete again the goblin quest "Goblin Engineering At Its Finest!"

**Comment by twowTurtReynolds** [comment] 2023-12-31 18:48
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813

**Closed by twowTurtReynolds** 2023-12-31 18:48 UTC
