### ISSUE TITLE
Can not apply Invocation from Kara to said item slot

### ISSUE THREAD

**Issue by vill8** [slowtorta/turtlewow-bug-tracker#5354] opened 2023-11-23 14:01 UTC
**Please, provide a clear description what the bug is:**
While trying to apply Inovcation of Greater Arcane Fortitude to leg piece the game says that "this is not a valid target"
**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Invocation of Greater Arcane Fortitude
2. Right click it to use it and left click on leg piece
3. Read the error and no profit ;)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=92008

**Expected behavior. Describe how it should work:**
It should apply the enchant to the leg piece as stated in item description

**Comment by vill8** [comment] 2023-11-24 17:30
You can enchant someone's leg piece in trade window ;)

**Comment by Muigin** [comment] 2023-11-24 17:51
Duplicate of #4788

**Closed by Muigin** 2023-11-24 17:51 UTC
