### ISSUE TITLE
cant train engineering in Alah Thalas

### ISSUE THREAD

**Issue by LepidloMaui** [slowtorta/turtlewow-bug-tracker#6044] opened 2024-01-19 20:47 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Train 2 random professions in Alah Thalas
2. Remove professions 
3. can't train engineering profession in Alah Thalas (could train mining)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2024-01-19 20:50
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5663

**Closed by twowTurtReynolds** 2024-01-19 20:50 UTC
