### ISSUE TITLE
Rogue lockpicking possible bug

### ISSUE THREAD

**Issue by PadreScruff** [slowtorta/turtlewow-bug-tracker#5506] opened 2023-12-05 00:26 UTC
[lockpicking bug.zip](https://github.com/slowtorta/turtlewow-bug-tracker/files/13553187/lockpicking.bug.zip)
**Please, provide a clear description what the bug is:**

I do my pickpocketing runs in Blackrock Spire, while doing so i have attempted to open the locked chests in the instance, to create the needed time gap i threw a distract then attempt to open the chest, however this creates what i think is a bug. Where that chest now only says "failed attempt". Is this intended or is this a bug?

**Steps to reproduce the behavior with as much detail as possible:**

I have only done this with the one location but it happens 100% of the time if you do it the way described, so in turn i would assume it would happen in this manner on any chest.

**Expected behavior. Describe how it should work:**

The concept is literally just to farm loot but be able to avoid conflict....you know be a thief

**Comment by twowTurtReynolds** [comment] 2023-12-07 14:53
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3501

**Closed by twowTurtReynolds** 2023-12-07 14:53 UTC
Labels: Rogue, Need Replication on VMaNGOS
