### ISSUE TITLE
Transmog Flying Tigerseye Goggles borked

### ISSUE THREAD

**Issue by ahhh-reptar** [slowtorta/turtlewow-bug-tracker#698] opened 2021-12-30 05:21 UTC
Flying Tigerseye Goggles doesn't appear in the transmog window.  Clicking headslot while wearing them produces error: 

interface\FrameXML\Turtle_TransmogUI\Turtle_TransmogUI.lua 1449:attempt to call a nil value

**Comment by slowtorta** [comment] 2022-01-19 12:06
![image](https://user-images.githubusercontent.com/66763404/150126329-5aca40d0-94c2-4197-a035-c8ee6ae21ef8.png)
Was either fixed by someone else or I cannot reproduce the issues.

**Closed by slowtorta** 2022-01-19 12:06 UTC
Labels: Fixed
