### ISSUE TITLE
Whitemane did not revive Mograine

### ISSUE THREAD

**Issue by Pet-Slime** [slowtorta/turtlewow-bug-tracker#5876] opened 2024-01-03 01:46 UTC
**Please, provide a clear description what the bug is:**

Our group did SM cath twice and whitemane both times failed to ressurect mograine. 

**Steps to reproduce the behavior with as much detail as possible:**

1. We are on Tel'Abim (the pvp server
2.  Our group consisted of Alume (48 paladin, me), Athelred (48 paladin), Blessyou (39 paladin), and Simpdeluxe (43 druid)
3. We cleared the right side of the instant completely to before the cathedral. 
4. We cleared the full catherdral before the boss, this includes the hidden boss first
5. The FIRST time we cleared it, we got Whitemane really low before she rezzed. we also ran into her room. 
6. Mograine did not rez and our paladin party member *blessyou* mentioned he needed quest credit to kill him, and didnt get it. So our group decided to run again. 
7. We ran out and reset the instance.
8. We cleared the full catherdral before the boss, including the hidden boss. Our one paladin did not help in the damage just in case we were DPSing too fast. 
9. Mograine did not rez the second time.
10. We contained a GM (Saphira), who showed up and tried to fix the fight by respawning Whitemane. 
11. The group killed Whitemane once again. Who slept the party and tried to rez mograine. However she still did not rez mograine. 

No loot was obtained from mograine each time.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Whitemane: https://database.turtle-wow.org/?npc=3977
Mograine: https://database.turtle-wow.org/?npc=3976
The quest: https://database.turtle-wow.org/?quest=1053

**Expected behavior. Describe how it should work:**

Expected behavior: After killing Mograine in the fight, Whitemane's door opens. After getting her health down, she should stop combat by putting everyone to sleep. She then goes and revives Mograine. Mograine gets revived and the fight continues to a part 2 with both of them at max hp.

**Comment by twowTurtReynolds** [comment] 2024-01-04 02:46
Thank you for the extremely detailed replication steps. This helps me replicate exactly what you did.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/952bd14c-054f-4479-a480-3bf1d67a54be)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d81e54f9-2396-4276-a95b-1e0cc62bed18)
However, I couldn't replicate the rez issue, she got Mograine up just fine. 

If you or anyone else can figure out what has caused the issue, like the party having a specific aura on that causes it, please let me know and we can try to replicate again.

**Comment by twowTurtReynolds** [comment] 2024-01-04 21:09
Others have reported this too and the staff are looking into it, despite our difficulty replicating.

**Comment by offerduo** [comment] 2024-01-05 19:52
I am getting the exact issue today. My team just did the normal thing: clear the whole room and the miniboss. Then we got the same issue: Whitemane couldn't rez Mograine.

**Comment by Bombg** [comment] 2024-01-07 01:07
Ran into the same issue. Cleared SM cath twice and Mograine didn't resurrect  both times even though the resurrection spell was casted.  Had Mograine's corpse following me around. 
https://i.imgur.com/MtyBXBG.gif

**Comment by DraZtiK** [comment] 2024-01-08 21:36
Happened 2 runs in a row for me today. Not sure why you cannot replicate?

**Comment by twowTurtReynolds** [comment] 2024-01-08 21:39
We've had about 10 reports of this come in this week, so it's definitely an issue. I still can't replicate on the PTR, I've tried 3 times so far... but others on the team can still look in regardless.

**Comment by npinchot** [comment] 2024-01-09 07:18
This happened to us every instance run today we did (four runs), after the first one.

For this set of runs, the group consisted of a level 60 warrior and a level 37 priest.

On the first run, something very strange happened. On the boss encounter, the doors to Whitemane were open. We dps'ed Mograine until he bubbled, and then killed Whitemane while Mograine was bubbled. We ended up stuck inside Whitemane's room and had to put in a GM ticket for help, who reset the boss encounter. Perhaps this is the root cause of the issue? But on the subsequent runs, the dungeon was reset (although the party was not recreated), so presumably dungeon reset would completely wipe out anything about the boss encounter.

Due to the level 60 warrior, I cleared the dungeon quickly.

I reported this in another issue with as much detail as I could think of. The clear order of trash mobs was random. This was on the Nordanaar server (PvE). Sorry I created an additional issue, didn't find this one before creating it. Here's a link to the issue I created - feel free to close it in favor of this one.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/5944

**Comment by DraZtiK** [comment] 2024-01-09 23:55
> We've had about 10 reports of this come in this week, so it's definitely an issue. I still can't replicate on the PTR, I've tried 3 times so far... but others on the team can still look in regardless.

Is PTR the prod server? Currently on the live production server its broke. 10 out of 10 runs and mograine will not get resurrected. Not only will he be dead, he will still be targeting the last person on the top of his aggro. Also, he follows you around like the previous poster provided.

**Comment by twowTurtReynolds** [comment] 2024-01-09 23:56
The PTR is a different server on the same codebase. We use it for testing.

**Comment by DraZtiK** [comment] 2024-01-10 00:13
Any possibility to test on live?

**Comment by twowTurtReynolds** [comment] 2024-01-10 00:53
Fix should be live now. https://forum.turtle-wow.org/viewtopic.php?t=12632

**Closed by twowTurtReynolds** 2024-01-10 00:53 UTC
Labels: Couldn't reproduce, Dungeons & Raids
