### ISSUE TITLE
Attack on southshore event broken

### ISSUE THREAD

**Issue by drnorth** [slowtorta/turtlewow-bug-tracker#4039] opened 2023-07-27 14:44 UTC
**Please, provide a clear description what the bug is:**
Attack on southshore not started or started incorrect without enemies.
**Steps to reproduce the behavior with as much detail as possible:**

1. Southshore Crier come to Southshore
2. Monsters Shadowy Assassin not comes

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC "Southshore Crier": https://database.turtle-wow.org/?npc=2435
NPC "Shadowy Assassin": https://database.turtle-wow.org/?npc=2434
Item: https://database.turtle-wow.org/?item=3668
Quest: https://database.turtle-wow.org/?quest=522

**Expected behavior. Describe how it should work:**
1. Southshore Crier come to Southshore
2. Monsters Shadowy Assassin start coming in main building in stealth
3. You can kill that and loot quest item

**Comment by Lichbanez** [comment] 2023-10-31 09:58
I think they want to merge everything about it here https://github.com/slowtorta/turtlewow-bug-tracker/issues/3675, I hope we'll hear about a fix soon.

**Comment by Muigin** [comment] 2023-10-31 09:59
Duplicate of #3675

**Closed by Muigin** 2023-10-31 09:59 UTC
