### ISSUE TITLE
Cooldown on Brutal Hauberk and Barbaric Belt

### ISSUE THREAD

**Issue by dropdropdrop** [slowtorta/turtlewow-bug-tracker#4296] opened 2023-09-08 12:42 UTC
**Please, provide a clear description what the bug is:**
Warrior Class. Using one of these items sets visible CD for 1 hour on it, and you can't use another item for that duration, but there is no displayable CD on it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Warrior Class
2. Equip both Brutal Hauberk and Barbaric Belt
3. Use Brutal Hauberk
4. Use Barbaric Belt

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: 
https://database.turtle-wow.org/?item=7133
https://database.turtle-wow.org/?item=4264
Spell:
https://database.turtle-wow.org/?spell=9174

**Expected behavior. Describe how it should work:**
It either should allow to use both items on they own 1 Hour CD (like on official?) or sets up both items on CD.

**Comment by twowTurtReynolds** [comment] 2023-12-06 22:14
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2638

**Closed by twowTurtReynolds** 2023-12-06 22:14 UTC
