### ISSUE TITLE
Rogue Flourish Cooldown 6.67mins

### ISSUE THREAD

**Issue by wangmeng2410** [slowtorta/turtlewow-bug-tracker#4859] opened 2023-10-22 08:29 UTC
Flourish - 6.67 mins rather than the 40s

1. Downloaded the clean game client(zip file from turtle wow homepage)
2. Empty WDB, WTF and Interface(pure game enviroment)
3. En language, no other localization packages
4. Connect from CN area directly w/o VPN

Issue Spell: Flourish

**Comment by cyaohiri** [comment] 2023-10-22 08:34
See #4457.

**Comment by wangmeng2410** [comment] 2023-10-22 08:46
> See #4457.

Hi cyaohiri,

I saw the last comment by [Muigin]:
"This behavior should now be fixed serverside, but the client may display an incorrect cooldown until a clientside update can be pushed."

Does it mean that it can be fixed by downloading a new game zip which will be published in homepage in next days?

**Comment by cyaohiri** [comment] 2023-10-22 09:25
> Does it mean that it can be fixed by downloading a new game zip which will be published in homepage in next days?
Yes, and that might happen with the 1.17.1 release.

**Comment by wangmeng2410** [comment] 2023-10-22 12:27
> Yes, and that might happen with the 1.17.1 release.

Thank you a lot!!!
It troubled me few days...

**Comment by Muigin** [comment] 2023-10-22 22:17
Duplicate of #4457

**Closed by Muigin** 2023-10-22 22:17 UTC

**Comment by wangmeng2410** [comment] 2023-11-22 03:10
@Muigin Hi, when this flourish cooldown issue can be fixed?
I saw someone get a patch-z to solve this now, but is it an official patch file?

**Comment by twowTurtReynolds** [comment] 2023-11-22 03:25
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4457#issuecomment-1772416734
