### ISSUE TITLE
Ferra's Collar Bonus damage

### ISSUE THREAD

**Issue by MenelauGC** [slowtorta/turtlewow-bug-tracker#5841] opened 2023-12-30 20:36 UTC
**Please, provide a clear description what the bug is:**Ferra's Collar don't give 4% bonus damage to the pet.

**Steps to reproduce the behavior with as much detail as possible:**

1.Ferra's Collar don't give 4% bonus damage to the pet.
2. Ferra's Collar don't give 4% bonus damage to the pet.
3. Ferra's Collar don't give 4% bonus damage to the pet.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
  15420
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**Ferra's Collar should give 4% bonus damaga to the pet.
I want to mention that i posted this  thing  and was fixed but now after the major patching upgrade on Tel'Abim realm,the item again is not working,i deleted WDB and still didn't fixed it,thank you.

**Comment by twowTurtReynolds** [comment] 2023-12-30 23:42
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5386

**Closed by twowTurtReynolds** 2023-12-30 23:42 UTC
