### ISSUE TITLE
Silver Sun mine: Enemies rise and clip through the ceiling (previous ticket #3690)

### ISSUE THREAD

**Issue by AeternusDoleo** [slowtorta/turtlewow-bug-tracker#3855] opened 2023-07-02 17:07 UTC
**Please, provide a clear description what the bug is:**
In the Silver Sun mine in Alah'Thalas, there are a number of 'Malfunctioning Arcane Construct' spawning. These used to stick to the cave floor, but now end up floating up in small shocks and then clip through the ceiling, eventually ending up outside of the mine on the mountainside.

**Steps to reproduce the behavior with as much detail as possible:**
1. Go into the silver sun mine
2. Wait for the enemies to spawn (might need to kill the ones on the hillside so they respawn)
3. The golems will start to suddenly rise through the ceiling (when they meander around) until they reach the mountainside above the mine and stay there.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Malfunctioning Arcane Construct: Display ID: 18022
NPC: https://database.turtle-wow.org/?npc=80241

**Expected behavior. Describe how it should work:**
These constructs should be an obstacle for players on a repeatable reputation quest for the Sun Elf faction, and should stay in the mine. This looks like some kind of clipping or collision issue where the game thinks the mine is not hollow/walkable for NPCs.

This is a repost of ticket #3690, which was closed with "Fixed in the next patch."
I waited 2 patches to see if perhaps it didn't make it into the first one, but unfortunately this issue is still occurring so I'm resubmitting the ticket. I could not find a way to reopen the existing ticket.

**Comment by twowTurtReynolds** [comment] 2023-12-09 02:38
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4101

**Closed by twowTurtReynolds** 2023-12-09 02:38 UTC
