### ISSUE TITLE
"Thandol Span" quest bug

### ISSUE THREAD

**Issue by james132422** [slowtorta/turtlewow-bug-tracker#6117] opened 2024-01-27 11:42 UTC
**Please, provide a clear description what the bug is:**
The quest requires the player to kill Scarlet Recurits and defeat Vladeus Springriver. Then bring Vladeus Springriver back to Menethil Harbor. However, once the NPC starts to follow the player, and the player moves from Thandol Span to Wetland, the NPC will disappear. It's impossible to finish the quest as no NPC will follow you throughout the Wetland.

![Post crossing](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6616298/eb8de48f-50cd-42eb-b41a-f67a4ca5becf)
![pre crossing](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6616298/e269e3fc-64f7-48fa-b2c8-65239be433fa)

**Steps to reproduce the behavior with as much detail as possible:**

1. Chain quests after "When Cravan Meets Cravan", accept the follow-up quest "Thandol Span"
2. Move to Thandol Span, kill mobs, defeat NPC and talk to NPC to follow.
3. Move from Thandol Span to Wetland (heading towards Menthil Harbour), and the NPC will disappear when you switch between the maps.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC Name: Vladeus Springriver

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
The NPC follows the player to Menethil Harbour and complete quest

**Comment by twowTurtReynolds** [comment] 2024-02-08 10:03
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5352

**Closed by twowTurtReynolds** 2024-02-08 10:03 UTC
