### ISSUE TITLE
Enemies on Tel'abim CCing hunter pet through Bestial Wrath

### ISSUE THREAD

**Issue by Aegael** [slowtorta/turtlewow-bug-tracker#4195] opened 2023-08-23 02:56 UTC
The gorillas on Tel'abim CC hunter pets through bestial wrath, the 31-point hunter beastmastery talent. As far as I'm aware, this talent is supposed to make the pet immune to all forms of cc besides death when activated.

**Comment by twowTurtReynolds** [comment] 2023-12-03 23:10
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2576 which was fixed.

**Closed by twowTurtReynolds** 2023-12-03 23:10 UTC
