### ISSUE TITLE
Veil of Nightmare not enchantable

### ISSUE THREAD

**Issue by edguix** [slowtorta/turtlewow-bug-tracker#5216] opened 2023-11-15 10:20 UTC
I am not an enchanter, so this is from the perspective of the enchantee. 

I try to have my cloak enchanted+3 Agility to Veil of Nightmare. The  error reported by enchanter is "Must have a Cloth equipped". 

Steps to produce Error:

1. Go up to enchanter with, Enchant Cloak - Lesser Agility, which is +3 Agility to cloak. 
2. Right Click Enchanter's Portrait and select Trade.
3. Go into your Bags and place 2 Lesser Nether Essence, materials needed for enchant, into the trade. 
4. Hit Trade..
5. Wait for enchanter to also hit trade so Lesser Nether essence is traded to enchanter.
6. Right Click portrait of enchanter again. 
7. Select Trade.
8. Plase the cloak, Veil of Nightmare, into the "will not be traded"window.
9. Wait for Enchanter to apply his spell of "Enchant Cloak - Leser Agility"
10. Enchanter will tell you that the equipment cannot be enchanted and report the error "Must have a Cloth equipped.:

Spell, Item ID's in question:

Veil of Nightmare Item: https://database.turtle-wow.org/?item=61210
Enchant Cloak - Lesser Agility Spell: https://database.turtle-wow.org/?spell=13882
Lesser Nether Essence x 2: https://database.turtle-wow.org/?item=11174
Artisan Enchanting: https://database.turtle-wow.org/?spell=13920

Expected Behaviour: 

1. Go up to enchanter with, Enchant Cloak - Lesser Agility, which is +3 Agility to cloak. 
2. Right Click Enchanter's Portrait and select Trade.
3. Go into your Bags and place 2 Lesser Nether Essence, materials needed for enchant, into the trade. 
4. Hit Trade..
5. Wait for enchanter to also hit trade so Lesser Nether essence is traded to enchanter.
6. Right Click portrait of enchanter again. 
7. Select Trade.
8. Plase the cloak, Veil of Nightmare, into the "will not be traded"window.
9. Wait for Enchanter to apply his spell of "Enchant Cloak - Leser Agility"
10. Wait for icon of Veil of Nightmare to turn green, meaning enchant has successfully been targeted.
11. Hit Trade.
12. Trade window should go away.
13. Inspect your Veil of Nightmare cloak and notice that it has successfully had 3 agility added to stats.

**Comment by Muigin** [comment] 2023-11-15 10:21
Duplicate of #4684

**Closed by Muigin** 2023-11-15 10:21 UTC
