### ISSUE TITLE
The touch of Zanzil quest won't finish

### ISSUE THREAD

**Issue by Seer0f** [slowtorta/turtlewow-bug-tracker#5273] opened 2023-11-18 21:15 UTC
**Please, provide a clear description what the bug is:**
The Touch of Zanzil quest won't complete.

**Steps to reproduce the behavior with as much detail as possible:**
1) I gathered everything that the quest required, I bought everything from different vendors, only the Bronze Tube (4371) was bought from the AH. I wasn't able to complete the quest. 
2) I cleared my .wdb folder, still nothing. 
3) I deleted my .wdb folder and disabled all my addons, still nothing. 
4) I asked random druid player to cleanse the poison debuff  (9991) from me, still nothing, the quest won't complete.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
**Quest**: https://www.wowhead.com/classic/quest=2609/the-touch-of-zanzil
**NPC**: https://www.wowhead.com/classic/npc=7207/doc-mixilpixil
**Items**:
https://www.wowhead.com/classic/item=3421/simple-wildflowers
https://www.wowhead.com/classic/item=3372/leaded-vial
https://www.wowhead.com/classic/item=4371/bronze-tube
https://www.wowhead.com/classic/item=8431/spool-of-light-chartreuse-silk-thread
https://www.wowhead.com/classic/item=8432/eau-de-mixilpixil
**Spell**: https://www.wowhead.com/classic/spell=9991/touch-of-zanzil

**Expected behavior. Describe how it should work:**
The expected result is completing the quest line and acquiring an item (8432) to dispel the debuff.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151404097/6c5f0ca0-8782-41b8-8e1d-d5c29180a282)

**Comment by twowTurtReynolds** [comment] 2023-11-18 21:37
The last time we had one of these issues, the user accidentally left an item in the bank. Can I get a pic of all 4 items in your inventory? Do hover over them and confirm they are the real items and not ones that might share the same icon which indeed could trick us

**Comment by Seer0f** [comment] 2023-11-18 21:45
Of course, here they are
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151404097/0f82d044-c4f5-4407-8c21-a93d545220b4)

**Comment by twowTurtReynolds** [comment] 2023-11-19 03:14
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a6dcf9a2-3c5f-4522-a6a7-b38503879f0b)
Thats odd you are having the problem, it's definitely not a serverside issue. Perhaps you have the wrong vial on accident? Maybe some addon conflict?

Closing as not a bug, can't replicate.

**Closed** 2023-11-19 03:15 UTC
Labels: Quest, Needs Replication
