### ISSUE TITLE
Bugged NPC & Area with Quest "Thandol Span"

### ISSUE THREAD

**Issue by Ramaan** [slowtorta/turtlewow-bug-tracker#5622] opened 2023-12-16 14:35 UTC
The Quest "Thandol Span" a lvl 60 custom Turtle WoW Quest cannot be completed because of the NPC you have to escort back to Menethil vanishes as soon as he moves like 20 yards away from the Event Zone where the scripted Mobs appear.

Once you defeat the two waves of 2 Enemies the NPC "Vladeus Springriver" appears. As soons as you fight him, he becomes friendly once reaching 20% health points. When you interact with the NPC and he agrees to follow you, the Event keeps triggering with the 2 Waves of Enemies if you are too slow killing them but the major issue happens when you try to leave the area.
As soon as you walk south to Menethil, the NPC vanishes and doesnt reappear if you walk past south.
But the really weird part happens when you go north, the NPC does NOT vanish.

I tried to escort the NPC through arathi and by water to Wetlands but as soon as he enters a certain part of the wetlands as if it were like a line or so he keeps disappearing.

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Vladeus Springriver
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=Thandol Span
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-16 17:43
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5352

**Closed by twowTurtReynolds** 2023-12-16 17:43 UTC
