### ISSUE TITLE
Bloody Belt Buckle incorrectly can't be used on other players

### ISSUE THREAD

**Issue by kitasanblack123** [slowtorta/turtlewow-bug-tracker#4583] opened 2023-10-06 14:15 UTC
**Please, provide a clear description what the bug is:**
the BR belt buckle can't be used to other players, but other buckles all can do like enchant, 1.17 information say all buckle can  be
installed by other players,even if you aren't a blacksmith,so i think it's a bug.
**Steps to reproduce the behavior with as much detail as possible:**

1.when i want to install it to other player,it remind me it just can be used to me,and then i try to delete the WDB,but it's not effective.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment] 2023-10-06 19:34
This must be changed in SpellItemEnchantment.dbc @slowtorta 

ID 3054 set last column to 0 instead of 1 to make it possible to apply enchant to other players.

**Comment by kitasanblack123** [comment] 2023-10-11 01:32
this bug has be fixed？

**Comment by GitsGift** [comment] 2023-10-17 12:49
any eta?

**Comment by Muigin** [comment] 2023-10-18 23:20
This will be fixed in a future maintanence.  This requires a tweak to spell behavior.  No current ETA.

**Comment by twowTurtReynolds** [comment] 2023-12-06 18:57
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4583

**Closed by twowTurtReynolds** 2023-12-06 18:57 UTC
Labels: Client
