### ISSUE TITLE
Bug about enchantments from Karazhan

### ISSUE THREAD

**Issue by senze** [slowtorta/turtlewow-bug-tracker#5062] opened 2023-11-04 09:59 UTC
Enchantment from Karazhan cannot be used on a head or leg slot item.

1. It will hint "It is not valid item" when using on a head or leg slot item.
2. It can be used on a shoulder slot item but will hint "must equit a miscellaneous".
3. I tried item "Invocation of Expansive Mind" only, please check other enchantments.
Invocation of Expansive Mind: https://database.turtle-wow.org/?item=92007

**Comment by Muigin** [comment] 2023-11-13 11:37
Duplicate of #4788

**Closed by Muigin** 2023-11-13 11:37 UTC
