### ISSUE TITLE
Elemental Devastation + Storm Gauntlets

### ISSUE THREAD

**Issue by Altgf-spelladin** [slowtorta/turtlewow-bug-tracker#3203] opened 2023-04-08 11:27 UTC
I have decided to test, if there is a synergy between item Storm Gauntlets (adds 3 Lightning Damage to melee attacks) and talent in Elemental Combat tree Elemental Mastery (gives +9% melee crit after critting with a spell effect) - appereantly, the synergy isn't working.

I am not sure, if the synergy has worked on classic, but in theory it should work, even though it doesn't.

Storm Gauntlet's effect is considered a **spell offensive** act. What proves it, is the fact that it can proc Wrath of Cenarius effect, which requires a spell offensive act. 
Wrath of Cenarius: https://database.turtle-wow.org/?item=21190

Those gloves can also crit and they proc talents, like Vengance for paladins, which procs after landing any critical offensive ability.

By the way, Storm Gauntlets are just one of many items with this effect. There is even a custom set on Turtle with exact same effects.

I think it's a bug and it would be nice if the synergy got fixed and started working. Thank you!

Storm Gauntlets: https://database.turtle-wow.org/?item=12632
Elemental Devastation: https://database.turtle-wow.org/?spell=29180

**Comment by ratkosrb** [comment] 2023-04-08 11:51
This is not a bug. Vengeance is specifically marked as being able to proc from procs. Elemental Devastation is not.

**Closed by ratkosrb** 2023-04-08 11:51 UTC

**Comment by Altgf-spelladin** [comment] 2023-04-08 15:16
> This is not a bug. Vengeance is specifically marked as being able to proc from procs. Elemental Devastation is not.

Doesn't really change the fact, that Storm Gauntlets should proc Elemental Devastation. Storm Gauntlets' effect is considered as offensive spell and therefore it should proc Elemental Devastation.
