### ISSUE TITLE
Equipment model error

### ISSUE THREAD

**Issue by Damaslove** [slowtorta/turtlewow-bug-tracker#5599] opened 2023-12-14 08:25 UTC
itemID:[Rod of Resuscitation]  61454

The model of this equipment is reversed when worn, with the head facing downwards. I hope it can be repaired as soon as possible, otherwise it will look unsightly，thank you.

![20231214162148](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149647129/0f707cad-3c57-48c3-abcc-fe7e3d1c16b9)

**Comment by twowTurtReynolds** [comment] 2023-12-14 12:32
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4932

**Closed by twowTurtReynolds** 2023-12-14 12:32 UTC
