### ISSUE TITLE
Pyrewood Ambush quest bugged.

### ISSUE THREAD

**Issue by Valjan** [slowtorta/turtlewow-bug-tracker#4985] opened 2023-10-31 01:44 UTC
**Please, provide a clear description what the bug is:** Pyrewood Ambush Horde quest is not completeable after council has been defeated.

**Steps to reproduce the behavior with as much detail as possible:**

1. Accept the quest from Deathstalker Faerleia in Pyrewood
2.  The council event starts, kill 4 waves of council members
3. The council event ends, quest is unable to be turned in, quest marker above npc remains gray.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2058
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=452
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** I should be able to turn in the quest after the council has been defeated.

**Comment by Muigin** [comment] 2023-10-31 01:45
Duplicate of #1708

**Closed by Muigin** 2023-10-31 01:45 UTC
