### ISSUE TITLE
Drape of Nordrassil is not enchantable

### ISSUE THREAD

**Issue by pipthedevil** [slowtorta/turtlewow-bug-tracker#5910] opened 2024-01-06 00:12 UTC
**Please, provide a clear description what the bug is:**

Unable to enchant hyjal reward item Drape of Nordrassil, tested using Enchant Cloak - Greater Resistance

**Steps to reproduce the behavior with as much detail as possible:**

1. Put cloak into trade window in enchant slot
2. Enchanter cannot add enchantment, gets error message "Must have cloth equipped"
3. Verified via multiple enchanters whether cloak was equipped or in inventory.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=](https://database.turtle-wow.org/?item=61753)

**Expected behavior. Describe how it should work:**

Cloak should be enchantable via the enchant box in trade window

**Comment by twowTurtReynolds** [comment] 2024-01-06 00:27
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5020
Please search before reporting.

**Closed by twowTurtReynolds** 2024-01-06 00:27 UTC
