### ISSUE TITLE
Mithril Nodes in Western Plaguelands Phase out when approached

### ISSUE THREAD

**Issue by StandInTheRiver** [slowtorta/turtlewow-bug-tracker#4069] opened 2023-08-01 22:21 UTC
**Please, provide a clear description what the bug is:**
Mining nodes that spawn near the mountain edge around 34 78 in western plaguelands phase out when approached
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the area at 34 78
2.  approach a node near 34 78 
3. Node disappears

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Nodes should not phase out

**Comment by twowTurtReynolds** [comment] 2023-12-07 00:09
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312

**Closed by twowTurtReynolds** 2023-12-07 00:09 UTC
