### ISSUE TITLE
Blood Frenzy is Still Broken 1.16.3

### ISSUE THREAD

**Issue by Jdavidlol** [slowtorta/turtlewow-bug-tracker#1901] opened 2022-08-12 02:57 UTC
**Please, provide a clear description what the bug is: 
The druid talent blood frenzy still does not grant attack speed (in either form) or rage in Bear Form**

**Steps to reproduce:**
As someone mentioned before but was listed as closed:
1. Learn blood frenzy.
2. Shift to cat, cast tiger's fury, check attack speed.
3. Shift to bear, cast Enrage, see that no rage is added immediately. Also check attack speed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=16954
I think this is it? The description is nothing like whats suggested in the Talent tree,

**Expected behavior. Describe how it should work:**

1.Increase attack speed, as per talent description.
2.Enrage instantly generates 10 rage as per talent description.
3.Spell and buff tooltips should reflect changes from the talent.

![BFFF](https://user-images.githubusercontent.com/24926558/184276669-cca801d9-6c5b-4ba8-a8cb-67bdaa2373ba.png)

Some info from this was lifted from the last time this bug was posted to make it quicker to post.

**Comment by ratkosrb** [comment] 2022-08-15 10:07
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1831
Will be fixed next update.

**Closed by ratkosrb** 2022-08-15 10:07 UTC
