### ISSUE TITLE
Idol of Evergrowth item crashes client

### ISSUE THREAD

**Issue by vevhlos** [slowtorta/turtlewow-bug-tracker#6297] opened 2024-02-18 02:34 UTC
**Please, provide a clear description what the bug is:**

Hello, I got Idol of Evergrowth from Razorlash in Maraudon, and I noticed a couple of problems. First, the item has a totally different use than advertised in database.turtle-wow.org. DB says extended duration, the actual item [ingame] has 3% proc for AoE nature damage on hit taken. Second, when equipped and i cast thorns on myself, an empty buff icon gets added on my buffs list along the usual Thorns icon, with no hover text, and when i try to right click (cancel), the client crashes. Some of my macros also throw an error while the buff is active (expected string, got nil, on a GetPlayerBuff function result passed to strfind). Thanks!

**Steps to reproduce the behavior with as much detail as possible:**

1. Get item 51802 [Idol of Evergrowth]
2. Equip item as a Druid
3. Cast Thorns on self
4. Try to cancel Evergrowth proc by right-clicking the [invisible] buff icon
5. Please note that i am running the client on Linux under WINE, but everything else works gucci

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=51802

**Expected behavior. Describe how it should work:**

Not crash client, DB should reflect actual properties.

**Comment by twowTurtReynolds** [comment] 2024-02-18 03:20
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5947

**Closed by twowTurtReynolds** 2024-02-18 03:20 UTC
