### ISSUE TITLE
South Greater Wind Stone

### ISSUE THREAD

**Issue by Belugaga90** [slowtorta/turtlewow-bug-tracker#5652] opened 2023-12-19 17:24 UTC
Hello,

The south Greater Wind Stone to summon the High Council in Silithus is not working properly. some times it does, but sometimes it spawns but we cant interact with it, even when using all the equipment required. when that happens, rigth now we need to wait for the server to reset to use it. we opened in game ticket but gm did not know how to help. is that a thing that can be fixxed?

Thank you.

**Comment by twowTurtReynolds** [comment] 2023-12-19 17:40
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5590

**Closed by twowTurtReynolds** 2023-12-19 17:40 UTC
