### ISSUE TITLE
Whip Lashers buff/bug

### ISSUE THREAD

**Issue by Creedastic** [slowtorta/turtlewow-bug-tracker#6106] opened 2024-01-26 09:20 UTC
**Please, provide a clear description what the bug is:** 

Whip Lashers in Dire Maul East deal a lot more damage than they used to do compared to the past. I am not aware of any change to these mobs, and GM in game told me there was no recent change on them. I deleted my WDB folder but the issue persists. I have been farming these mobs every day with the same gear, rotation and spec, but today I found out that doing the same thing on 2 packs of mobs gets me killed almost instantly, while in the past I could easily survive 2 packs of them. I think they were changed and their damage was increased massively, I think you should revert this change.

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Dire Maul East
2. Attempted to kill 2 packs of Whip Lashers
3. The damage they deal is increased and killed me instantly

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13022

**Expected behavior. Describe how it should work:**
These monsters should deal a lot less damage than what they are dealing now, as yesterday they were dealing a lot less. Note my gear has not changed at all compared to yesterday, nor my spec or rotation used.

**Comment by twowTurtReynolds** [comment] 2024-02-09 02:09
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6105

**Closed by twowTurtReynolds** 2024-02-09 02:09 UTC
