### ISSUE TITLE
Flash of Light uses two charges of Eye of the Dead and Zandalarian Hero Charm's on-use effects.

### ISSUE THREAD

**Issue by LHKeep** [slowtorta/turtlewow-bug-tracker#6215] opened 2024-02-10 04:54 UTC
**Please, provide a clear description what the bug is:**

Each cast of Flash of Light uses two charges of the on-use effect of both 'Eye of the Dead' and 'Zandalarian Hero Charm' (Holy Light properly only uses one charge).

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip and use either Eye of the Dead, or Zandalarian Hero Charm.
2. Use the trinket's on-use effect.
3. Cast Flash of Light and notice that 2 charges are consumed with each cast.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell (Flash of Light rank 6): https://database.turtle-wow.org/?spell=19943

Eye of the Dead:
Item (Eye of the Dead): https://database.turtle-wow.org/?item=23047
Spell (The Eye of the Dead on use effect): https://database.turtle-wow.org/?spell=28780

Zandalarian Hero Charm:
Item (Zandalarian Hero Charm): https://database.turtle-wow.org/?item=19950
Spell (Zandalarian Hero Charm on use effect): https://database.turtle-wow.org/?spell=24658

**Expected behavior. Describe how it should work:**

Flash of Light should only expend one charge of the on-use effect of Eye of the Dead and Zandalarian Hero Charm, like Holy Light does, instead of two charges.

**NOTE:**
Please **DO NOT** close this as a duplicate of 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/5137
https://github.com/slowtorta/turtlewow-bug-tracker/issues/6112

**It is not a duplicate.** You may have fixed the originally reported issue for Shaman's Chain Heal, but you DID NOT fix it for Flash of Light! I have both trinkets and confirmed just now that it is still bugged for Flash of Light as of today.

**Comment by twowTurtReynolds** [comment] 2024-02-10 09:51
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5137

**Closed by twowTurtReynolds** 2024-02-10 09:51 UTC
