### ISSUE TITLE
Bloodsail Buccaneers rep issues

### ISSUE THREAD

**Issue by Dualityz** [slowtorta/turtlewow-bug-tracker#5025] opened 2023-11-02 15:22 UTC
**Please, provide a clear description what the bug is:**
Doing Garfield Sparkblast's Red Flag Over the Sea questline turns the Bloodsail Buccaneer neutral ( and later friendly ) to you, yet because of questing in Gadgestan you may unintendedly end up hated with them again.

This may be an issue because 
a. You may have risked death ( or died ) to the Baron's guards in order to experience those new custom quests on the Jaguero Isle, only to have the possibility of leveling there disapearing unintendedly because of leveling in Tanaris right after STV ( very common path ) 
b. You can end up being hated by both the pirates and booty bay

It should be possible to regain rep for these guys, maybe with a turn in just like the Cartel cloth NPCS, to avoid being stuck in an unwanted, awkward leveling position towards both factions.

**Steps to reproduce the behavior with as much detail as possible:**

1. Do the questline from Garfield Sparkblast in Booty bay
2. Do a couple of quests from Gadgeztan
3. Bloodsail Bucaneers are unfriendly with you again
4. No way of grinding it back up. Goodbye Jaguero isle custom questing :(

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=60453
Quest: https://database.turtle-wow.org/?quest=40172

**Expected behavior. Describe how it should work:**

You shouldn't lose rep with the Bloodsail Buccaneers by questing elsewhere than Booty bay; OR you should be given an option farm it back up, and not lose out on the Bloodsail rep entirely for a mistake.

**Comment by twowTurtReynolds** [comment] 2023-12-04 21:35
I've convened with the staff and this being closed as working as intended, not a bug. I would take any further discussion about this decision to the suggestions forum.

**Closed by twowTurtReynolds** 2023-12-04 21:35 UTC
Labels: Quest, Suggestion
