### ISSUE TITLE
Lodestone wand in wrong hand

### ISSUE THREAD

**Issue by Squirreled** [slowtorta/turtlewow-bug-tracker#5690] opened 2023-12-21 05:18 UTC
![handagain](https://github.com/slowtorta/turtlewow-bug-tracker/assets/137924886/f5fd9709-2e0b-48d6-b682-7208b1fa6abd)
Character swings right arm and projectiles appear from right hand, however the wand model is in the left hand.
This was also an issue with blackflame wand, which i reported earlier.
It seems the twow wands have a tendency to be in the left hand.

All wands should be in the right hand.

**Comment by twowTurtReynolds** [comment] 2023-12-21 14:00
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5646

**Closed by twowTurtReynolds** 2023-12-21 14:00 UTC
