### ISSUE TITLE
custom chillwind armor procc doesnt work

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2815] opened 2023-02-08 12:57 UTC
**Please, provide a clear description what the bug is:**

https://database.turtle-wow.org/?item=61079
i have tried this chest for quite a while now. it says chance on hit, so that means when i hit something, but never proccs against dummies. maybe its worded wrong and it was meant to work like demon forfed bresatplate "when struck in combat", but no doesnt procc either when hit.

**Expected behavior. Describe how it should work:**

procc should work sometimes instead of never

**Comment by ratkosrb** [comment] 2023-02-08 13:26
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2805
The effect will be removed from the item, and instead the stats will be increased.

**Closed by ratkosrb** 2023-02-08 13:26 UTC
