### ISSUE TITLE
Greater Wind Stone is bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#1314] opened 2022-04-17 21:18 UTC
Greater Wind Stone is bugged

https://database.turtle-wow.org/?object=180539  This Greater Wind Stone is not respawning.

 49334, Entry 180559 - [Greater Wind Stone X:-6749.069824 Y:1647.140015 Z:8.070550 MapId:1]

Entry: 180559, GUID: 49334
Name: Greater Wind Stone
Type: 10, Display Id: 6427
 GO State: 1, Loot State: 1
 Not spawned. Respawns in 3600 seconds (22:23:59).
 
Manual respawn does not respawn the object

The other two windstones work properly

**Comment by Kruxis** [comment] 2022-04-24 10:25
Will be fixed on next restart =)

**Comment by slowtorta** [comment] 2022-11-06 12:55
![image](https://user-images.githubusercontent.com/66763404/200171931-2ff4b3b5-a5ca-425d-8bb2-8fde0d9ca293.png)
This Wind Stone should not respawn every 10 minutes, I belive it's working as intended right now.

**Closed by slowtorta** 2022-11-06 12:55 UTC

**Comment by Sringaram** [comment] 2022-11-15 02:50
Still is still broken, the stone south is never up.

**Comment by geojak** [comment] 2022-12-27 22:41
this bugged

**Comment by geojak** [comment] 2022-12-27 22:41
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1988

**Comment by geojak** [comment] 2023-01-29 10:40
@slowtorta could be reopened or maybe locked at in #1988
Very visible bug annoying raid after raid week after week. Please
