### ISSUE TITLE
Elunes Blessing Quest broken

### ISSUE THREAD

**Issue by Squirreled** [slowtorta/turtlewow-bug-tracker#6093] opened 2024-01-25 04:28 UTC
The quest text says "receive Elune's Blessing"

Elunes blessing is a buff gained by standing in the light spawned by killing omen.
This gives a 60 min buff.

However even with the buff active the quests does not count as completed and is therefore impossible to turn in.

**Comment by twowTurtReynolds** [comment] 2024-01-25 04:29
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6091

**Closed by twowTurtReynolds** 2024-01-25 04:29 UTC
