### ISSUE TITLE
Bugged Hardcore Death.

### ISSUE THREAD

**Issue by Sruzzy** [slowtorta/turtlewow-bug-tracker#3767] opened 2023-06-24 03:58 UTC
**Please, provide a clear description what the bug is:** The first boss lady has an explosion with a really fucked up collision radius for an insta-death mechanic. 

**Steps to reproduce the behavior with as much detail as possible:**

1.Kill the first troll boss in gnomer
2. Die from the rocks in some random location unbeknownst to you.
3. Get mad that you wasted countless hours to a bug. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** Not insta kill you with what i assume are "rocks" from 30 yards away from where the rocks are.

**Comment by Sruzzy** [comment] 2023-06-24 04:02
Charecter named Circles on hardcore died because of this. not cool. I hate to be a karen but i really would like a resurrection because that's beyond stupid.

**Comment by ConcernedTurtler** [comment] 2023-06-24 20:00
It's called hardcore for a reason. Start over.

**Comment by Jeradooka** [comment] 2023-06-26 15:58
Sorry man, this is not a bug. This encounter has always been this way. Sorry for your loss.

**Comment by Zebouski** [comment] 2023-06-28 00:14
Blizzlike yeah you def do get instakilled for being behind or underneath the rock falling spot.

Are you saying that the kill raidus is way way too far out and you died despite your model being nowhere near the area? It would probably be helpful if you can show in a diagram.

> Charecter named Circles on hardcore died because of this. not cool. I hate to be a karen but i really would like a resurrection because that's beyond stupid.

this was covered when you signed up for hard core. turtle staff don't do revives ever for any reason.

**Comment by Sruzzy** [comment] 2023-06-28 03:25
@Zebouski I'm aware of their policy of not taking responsibility for deaths caused by shitty code. Torta has a SS, I was reasonable and even asked to just drop the HC moniker. Never filing another bug report. 

Chromiecraft actually can admit when their code is shit and you died because of it.

**Comment by redmagejoe** [comment] 2023-06-28 03:28
The bugtracker comments are not a place for you to air your grievances like a child because you couldn't be bothered to acknowledge the Terms of Service you agreed to be using the service.  Please use this platform to report and document bugs, or stop posting.

**Comment by Gurky-Turtle** [comment] 2023-06-28 21:10
Sorry to hear you died. As for the event I just finished testing it and it looks like the npc warns the player as well as runs a safe distance away telling you to also stand back. It works this way for both explosions for this event you can stand a little closer than the npc without getting hit but if you stand to close to the explosion you will get hit seeing two charges are going off at the same time. 

Think about it in real life if someone is blowing up cave entrances are you going to stand closer to the explosion than the person who is setting them off?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/d6404cbe-bc1c-4c9c-839a-8feeab164187)

I am going to go ahead and close this bug report seeing what you died to is part of the rp event for summoning the boss.

**Closed by Gurky-Turtle** 2023-06-28 21:10 UTC
