### ISSUE TITLE
A square of solid land in Feralas can drown players

### ISSUE THREAD

**Issue by SaxxonPike** [slowtorta/turtlewow-bug-tracker#4800] opened 2023-10-18 04:30 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Go around (77.0, 48.6) in Feralas, on the part of the path in the image
2. Notice the breath meter starts ticking down
3. Step away a short distance and the breath meter resets

![Screenshot 2023-10-17 232820](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2202546/f45dd3d4-1e09-478c-be57-d762e022cf93)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

n/a

**Expected behavior. Describe how it should work:**

Players standing on solid land should not be able to drown.

**Comment by Muigin** [comment] 2023-10-19 06:11
Duplicate of #4568

**Closed by Muigin** 2023-10-19 06:11 UTC
