### ISSUE TITLE
Troll priest shadowguard no proc from ranged

### ISSUE THREAD

**Issue by priestofshadow** [slowtorta/turtlewow-bug-tracker#386] opened 2021-10-18 12:43 UTC
On my troll priest when PW:shield is on, and shadowguard is on, mobs that shoot arrows at me will not make shadowguard proc. Melee hits when PW:shield is on will make SG proc. I think ranged hits when no PW:shield is on will will make SG proc, but i dont remamber 100%.
For sure ranged hits when PW shiled si on will not make it proc.

Also SG never procced a blackout for me, so not sure if its bugged or i just had bad RNG. 
And while you're at it can you check if SG procs shadoow weaving talent? i know it should but my level is not high enough to try it.

Also here is very good video explaining everything SG should proc. Pls start at 5:00 mark
https://youtu.be/ebfftvVL3rk

**Comment by slowtorta** [comment] 2022-05-15 23:31
Probably fixed in the next revision, please report if still not working as intended.

**Closed by slowtorta** 2022-05-15 23:31 UTC
Labels: Fixed, Spells & Talents
