### ISSUE TITLE
Judgement not working sometimes

### ISSUE THREAD

**Issue by RevengeanceOne** [slowtorta/turtlewow-bug-tracker#3285] opened 2023-04-19 06:49 UTC
**Please, provide a clear description what the bug is:**

Judgement + Seal of the Crusader does not work at times when it should. I believe it happened with other seals as well during leveling but I can't confirm that. 

**Steps to reproduce the behavior with as much detail as possible:**

1. To test this I have used frost oil on my weapon which has a 10% base chance to proc. 
2. I have then activated Seal of the Crusader (which should increase the proc chance to 300% according to the skill description) 
3. I then activated Judgement on an enemy entity (test dummy, mob, player, etc) with varied results although it shouldn't be that way according to point (2.). As you can see in the combat log of the screenshot I've provided, It worked the first time , followed by a second time where it simply consumed my seal and nothing happened, followed by a third use of judgement where it worked again. Sometimes it works 5 times in a row, sometimes it doesn't work 7 times in a row ... however at a 300% rate it is obvious it should work every time. 

![2d08bd5e847b2955d9770beeb6b1e565-1](https://user-images.githubusercontent.com/131232558/232988430-3553f02e-520d-4c7a-931f-e424aa4450be.jpg)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

For this test I have used rank 6 Seal of the Crusader and Judgement

Spell1: https://database.turtle-wow.org/?spell=20271
Spell2: https://database.turtle-wow.org/?spell=20308

**Expected behavior. Describe how it should work:**

It should always proc with something like a frost oil applied (but this is just one of the examples I have found convenient to test, it is most definitely not a frost oil issue) provided the judgement does not miss or get resisted, however I am almost certain that is not the case for my tests. But it is hard to confirm since judgement with Seal of the Crusader simply does not show in the combat log.

**Comment by ratkosrb** [comment] 2023-04-19 22:57
What weapon are you using? Some effects have reduced chance to trigger. If it's any kind of crowd control like stun, fear, etc then it's intended not to work most of the time.

**Comment by ratkosrb** [comment] 2023-04-21 05:03
> The weapon used has no importance in this test.

No, that's not how it works. The bonus chance multiplier is calculated based on the weapon. If your weapon has a CC effect, that will also reduce the chance for Judgement to proc any enchants on it like Frost Oil. Closing this as its not a bug. Stop using weapons with CC or AoE effects if you want to have the full benefit of Judgement of the Crusader.

**Closed by ratkosrb** 2023-04-21 05:03 UTC

**Comment by RevengeanceOne** [comment] 2023-04-21 05:12
> > The weapon used has no importance in this test.
> 
> No, that's not how it works. The bonus chance multiplier is calculated based on the weapon. If your weapon has a CC effect, that will also reduce the chance for Judgement to proc any enchants on it like Frost Oil. Closing this as its not a bug. Stop using weapons with CC or AoE effects if you want to have the full benefit of Judgement of the Crusader.

Okay but that means the skill description is incomplete and misleading!! I don't see any mention of it being 6x instead of 30x if the weapon used has a CC effect! Much less so that the weapon itself affects the chance of the enchant itself!! This needs to be added to the skill tooltip!!
