### ISSUE TITLE
New enchant item does not apply to item

### ISSUE THREAD

**Issue by LeOtheChen** [slowtorta/turtlewow-bug-tracker#4870] opened 2023-10-23 11:56 UTC
**Please, provide a clear description what the bug is:**

The new enchant item [Invocation of Greater Protection] does not apply to [Bloody Gladiator's Headband]. When processed, a red system warnning pops up states "That item is not a valid target"

**Steps to reproduce the behavior with as much detail as possible:**

1. Right click [Invocation of Greater Protection] 
2. Left click [Bloody Gladiator's Headband]

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=

**Expected behavior. Describe how it should work:**

**Comment by Datedb** [comment] 2023-10-24 15:32
known bug it enchants shoulder at the moment.

**Comment by LeOtheChen** [comment] 2023-10-31 03:16
Thank you for the reply.

Another bug when apply to shoulder item.

Apply  [Invocation of Greater Protection] to [Bloodfang Spaulders] resulting system message "Must have a Miscellaneous equipped" 

Item: 
https://database.turtle-wow.org/?item=16832
https://database.turtle-wow.org/?item=92006

**Comment by Muigin** [comment] 2023-10-31 03:22
Duplicate of #4788

**Closed by Muigin** 2023-10-31 03:22 UTC
