### ISSUE TITLE
"Pyrewood Ambush" quest does not complete

### ISSUE THREAD

**Issue by gemanner** [slowtorta/turtlewow-bug-tracker#5109] opened 2023-11-07 13:17 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. start quest
2. wave defense
3. Quest Completed

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2058
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=452
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Cannot be completed after the last wave defense

**Comment by ratkosrb** [comment] 2023-11-07 22:50
![WoWScrnShot_110723_234952](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/cba901b6-c4b9-41fa-87d8-25aec0fb3105)

Cannot reproduce the issue. The quest completed fine for me. Were you maybe in a raid group, which prevented you from completing normal quests?

**Comment by ratkosrb** [comment] 2023-11-07 22:55
![WoWScrnShot_110723_235452](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/76be28cf-f687-4b50-846f-2f4dbba75ce1)

I just tested it on the Live server too and it completed fine there as well. Closing the issue.

**Closed by ratkosrb** 2023-11-07 22:55 UTC
Labels: Couldn't reproduce
