### ISSUE TITLE
disarm 

### ISSUE THREAD

**Issue by Blaskaren** [slowtorta/turtlewow-bug-tracker#3497] opened 2023-05-20 06:08 UTC
**Please, provide a clear description what the bug is:**
Disarming within 1-3 seconds after the first disarm is over.

**Steps to reproduce the behavior with as much detail as possible:**

1. Charge in
2. Rend 
3. (Disarmed)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4656
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
They should not be able to disarm within 10 seconds when the first disarm is over.
Pretty sure they shouldn't be able to disarm at all, but i might be wrong about that one.

**Comment by twowTurtReynolds** [comment] 2023-12-09 04:02
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142

**Closed by twowTurtReynolds** 2023-12-09 04:02 UTC
