### ISSUE TITLE
Battlegrounds population breaking problem. (8vs12 wsg for example)

### ISSUE THREAD

**Issue by Ylivoima** [slowtorta/turtlewow-bug-tracker#5737] opened 2023-12-23 20:10 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Join battleground (for example WSG) in PVP server(tel abim). 
2. Play for while, people come and go but alliance only goes and only horde comes so
3.  its suddenly 8vs12 game. 8 alliances vs 12 hordes. or 9vs11, ETC. this sucks it happens in like most of the games I play. Also happened in AV yesterday. 

**Expected behavior. Describe how it should work:**

WSG should be 10vs10. AV should be 40vs40. This happen in most of matches

**Comment by Ylivoima** [comment] 2023-12-23 20:25
![ggwp](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115708855/4b3dba60-a6bc-46d4-b2d3-9746f51d2e20)
just an example but been in worse disadvantege games aswell.

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:48
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3239

**Closed by twowTurtReynolds** 2023-12-25 00:48 UTC
