### ISSUE TITLE
Storm Gauntlets' proc doesn't activate Vengeance on crit.

### ISSUE THREAD

**Issue by PetiteNausicaa** [slowtorta/turtlewow-bug-tracker#402] opened 2021-10-28 10:29 UTC
**Please, provide a clear description what the bug is:**

Storm Gauntlets' proc is to launch a spell that does 3 damage on each melee hit.
This spell can crit for 4 damage, based on %spellcrit.
However, when Storm Gauntlets' proc does a crit, it does not proc paladin's talent Vengeance. It should, as Vengeance trigger on any critical success, from spells, abilities, melee attacks alike.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get a paladin with Storm Gauntlets and Vengeance
2. Attack a mob and crit with the Gauntlets' proc
-> The proc works (3 damage on each melee strike and melee judgement)
-> It correctly crits (with %spellcrit)
-> It doesn't scale with spell power (normal)
But : 3. Its crit doesn't proc Vengeance.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

The item : https://database.turtle-wow.org/?item=12632
The talent : https://database.turtle-wow.org/?spell=20059
The spells triggered by the item : 
https://database.turtle-wow.org/?spell=16615
https://database.turtle-wow.org/?spell=16614

**Expected behavior. Describe how it should work:**

Storm Gauntlets should activate Vengeance. Indeed: its proc activates a spell, and when a spell crits, Vengeance activates.
It worked like that during vanilla, and during classic ; it is a known, important and old quirk of retribution paladin itemization.

ADDITIONAL NOTE : 
The same behaviour should be observed on other items with the same kind of effect. It is for example known : 
- Fiery Plate Gauntlet https://database.turtle-wow.org/?item=12631
- Blazefury Medallion https://database.turtle-wow.org/?item=17111
should also trigger Vengeance. 

I did not try those effects yet. I don't know if the bug is specific to Storm Gauntlets or to all this family of effects on Turtle WoW. Perhaps it should be investigated.

**Comment by slowtorta** [comment] 2022-04-29 21:57
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1274

**Closed by slowtorta** 2022-04-29 21:57 UTC
Labels: Fixed, Spells & Talents
