### ISSUE TITLE
Ostarius 

### ISSUE THREAD

**Issue by XIANpengfei** [slowtorta/turtlewow-bug-tracker#5774] opened 2023-12-26 06:03 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The door of O'Dam（entrance guard）
2. Unable to rereceive this task.
3. The mission is to find the Olddam slate，The first and second blocks.
4. This task is intended to summon the Ostarius
5.I need a piece of his gear， but I couldn't summon it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by XIANpengfei** [comment] 2023-12-26 07:52
https://database.turtle-wow.org/?quest=40107  
This task。

**Comment by twowTurtReynolds** [comment] 2023-12-26 13:10
Do you see how this quest is marked as Raid? This is a world boss quest. World bosses have 7 day long respawn timers.

Working as intended.

**Closed by twowTurtReynolds** 2023-12-26 13:10 UTC
