### ISSUE TITLE
List of known Alterac Valley issues 

### ISSUE THREAD

**Issue by slowtorta** [slowtorta/turtlewow-bug-tracker#1478] opened 2022-06-04 12:21 UTC
1. NPC keeps respawning: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1281
2. Snivvle respawn: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1440
3. Infantry and other issues: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1288
4. Alterac Valley guards continue spawning after towers are burned: https://github.com/slowtorta/turtlewow-bug-tracker/issues/536
5. When players control Coldtooth Mine and Snivvle respawns, they lose control of the mine and cannot regain control of it: https://github.com/slowtorta/turtlewow-bug-tracker/issues/307

**Comment by geojak** [comment] 2022-06-04 23:14
Just noticed my issue in aboes list no. 2. Is a duplicate of the older issue no 5. In above list

**Comment by geojak** [comment] 2022-06-18 21:54
hello i spike with absolo today who recetly changed faction and knows both sides of av well. he made me aware of 2 more issues:

1. the neutral mine mobs in north and south do not drop the same amount of armor scraps. if you could qualize this out of fariness, i would suggest take the lower value if the se rly differ form each other.
2. absolon shared his suspicion with me, that horde npc mobs hit less hard on averag then the alliance nps. but he is not sure abot it too. if possible it would be great out of fiarness to have a check if liteunants and commanders on both sides have somewhat similair values.

**Comment by burner1024** [comment] 2022-07-22 14:38
- Both Ivus and Rokholar lose their objective after a while, and just stand on the field of strife. The farthest I see them get is IBGY and IWB, respectively.

**Closed** 2023-02-18 23:58 UTC
Labels: PvP

**Comment by welpenhund** [comment] 2023-05-11 19:24
Bump - post nearly 5month old and it still happens
