### ISSUE TITLE
Rogue talent "Improved sap" is broken

### ISSUE THREAD

**Issue by Kurpatoff** [slowtorta/turtlewow-bug-tracker#1692] opened 2022-07-27 16:32 UTC
I use 2 point for talent "improved sap" and all time after I use  sap my stealth dont worked

Char name: **Gundabad**

**Comment by JoLiKMC** [comment] 2022-07-27 19:00
In order to always remain in Stealth while using Sap, you need to spend **three** talent points, not two.

**Comment by nonameform** [comment] 2022-07-27 19:35
> In order to always remain in Stealth while using Sap, you need to spend **three** talent points, not two.

The talent was changed. It's just two ranks now, so the original post is correct. The talent calculator at TWoW doesn't reflect all of the changes.

**Comment by joeblack16** [comment] 2022-07-28 06:49
I can confirm its broken.
Interesting moment - right after i put 2/2 in improved sap it worked just fine. But after i relogged, every time i use sap it reveals me and puts me in combat.

**Comment by pe-hy** [comment] 2022-07-30 12:22
Yup its broken. Currently a huge nerf for PVP rogue.

**Comment by ratkosrb** [comment] 2022-07-30 17:37
I can't reproduce the issue. I always remain in stealth with the talent.

**Comment by joeblack16** [comment] 2022-08-03 07:11
@ratkosrb how did you try? Have you relogged?
I double checked. I resetted talents and put 2/2 to improved sap again. It worked fine **until relog**. After that it does not return me to stealth

**Comment by Slimthegrim** [comment] 2022-08-04 18:45
@ratkosrb I'm still able to reproduce this bug as of this morning. I've attempted clearing WDB multiple days to no avail. I've attempted a fresh client install as well with neither mods nor addons, which also doesn't fix improved sap.

Here are the exact steps to encounter bug:
1. Clear talents, and any talents through 2/2 imp sap.
2. Test sap, and confirm it's not broken when talent is freshly applied
3. Logout
4. Login to same character
6. Test sap, _**stealth breaks**_ when it should not. [bug here]
7. Clear talents, and apply 2/2 imp sap, return to step 2.

A fresh application of talents, or re-applying the same talent set via Gobbo Brainwash Device appears to mitigate the bug until relog when it just happens again.

@ratkosrb Please take a second look at the input, I'd kindly ask what specific evidence can I go out and gather for you?

**Comment by ratkosrb** [comment] 2022-08-06 02:08
I tested with logging out and it still works for me.
https://streamja.com/Q23eq

**Comment by pe-hy** [comment] 2022-08-06 08:28
Try that on a player entity. You are sapping NPCs.

**Comment by Twitnyeastern** [comment] 2022-08-06 08:39
Hello! This issue exists for me too for more then 2 weeks, exectly as Slimthegrim has written above(steps).
 Could you please explain what does "Couldn't reproduce" mean? It will not look and fixed for us or? Need to understand what to do next with this problem that permanently brokes one of game class.

**Comment by Slimthegrim** [comment] 2022-08-06 13:50
> I tested with logging out and it still works for me. https://streamja.com/Q23eq

https://streamkek.com/lYrVbWOMdC captured this morning, imp sap breaks stealth.

**Comment by jameyboor** [comment] 2022-08-07 21:29
Fixed in next update.

**Closed by jameyboor** 2022-08-07 21:29 UTC
Labels: Couldn't reproduce

**Comment by Twitnyeastern** [comment] 2022-08-08 21:42
Really fixed, thanks!
