### ISSUE TITLE
Warlock Talent: "Pyroclasm" doesn't work with HellFire.

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#4184] opened 2023-08-21 19:43 UTC
**Please, provide a clear description what the bug is:**

The warlock talent pyroclasm is supposed to have a 26% chance to stun the target with hellfire if you put two talent points into this. Testing on targeting dummies and in duels it never seems to stun.

**Steps to reproduce the behavior with as much detail as possible:**

1. Spec into pycroclasm in the destruction tree.
2.  Use hellfire targets.
3.  Observe that it never stuns the target.

edit: Same issue has been reported before: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3484

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=18073

**Expected behavior. Describe how it should work:**

The target should bet stunned when hit by the spells listed in the talent.

**Comment by twowTurtReynolds** [comment] 2023-12-07 01:38
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1674

**Closed by twowTurtReynolds** 2023-12-07 01:38 UTC
