### ISSUE TITLE
Spirit Healer not working in Deadwind Pass for Horde on EU PvP Tel'Abim

### ISSUE THREAD

**Issue by hjortmar** [slowtorta/turtlewow-bug-tracker#5248] opened 2023-11-17 11:11 UTC
**Please, provide a clear description what the bug is:**
We (Horde) wiped in Karazhan Crypts and everyone in the group had to run from Redridge to the instance. Seems odd.

Also happened with a mage in the group yesterday when he died.. so Im guessing it will be easy to reproduce.

As a sidenote: near Archlich there are some cracked floorboards in the corridor that leads to his room.. it is possible, atleast as Undead, to fall through those cracked floorboards.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go into instance, die near Archlich or Anderson.
2. Enjoy, 10 minute runback.

**Expected behavior. Describe how it should work:**

Respawn outside, at the spirit healer.

**Comment by Muigin** [comment] 2023-11-17 14:55
Duplicate of #4937

**Closed by Muigin** 2023-11-17 14:55 UTC
