### ISSUE TITLE
In the mountains behind Deadmines in Westfall, the corpse of a Defias Highwayman attacked me. It slid towards me on its belly, dead on the ground, and unattackable because it was dead, and then it wailed on me until I was dead. Didn't receive damage numbers either.

### ISSUE THREAD

**Issue by HenningPM** [slowtorta/turtlewow-bug-tracker#5161] opened 2023-11-10 21:12 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by HenningPM** [comment] 2023-11-10 21:13
The bug is as the title states.

As for how to reproduce it, I do not know. He was dead when I got there, and aggroed on me as if he wasn't.

NPC: https://database.turtle-wow.org/?npc=122

**Comment by cyaohiri** [comment] 2023-11-13 12:21
It isn't yet known why this happens, but you can read more about it here: https://github.com/vmangos/core/issues/2198

**Comment by twowTurtReynolds** [comment] 2023-11-18 18:30
Thank you @cyaohiri for the link, this issue will be tracked there. Closing this as dup

**Closed** 2023-11-18 18:31 UTC

**Comment by Gamemechanicwow** [comment] 2023-11-21 21:06
> Thank you @cyaohiri for the link, this issue will be tracked there. Closing this as dup

The issue is unlikely to be tracked on vmangos, as the bug reported there looks like it belongs to a different fork,
