### ISSUE TITLE
Seal of Ascension  Quest bugged 

### ISSUE THREAD

**Issue by Ttourro** [slowtorta/turtlewow-bug-tracker#3737] opened 2023-06-20 13:05 UTC
Just completed 2nd part of this quest (Forging the seal of ascession by flame of NPC Dragon. The issue is when dragon below 10% of health, i have to Mind Control him, and use HIS ability to forge the seal. IT IS DOESNT WORK. After i`m using mind controll item, seal on the floor getting forged by itself and become lootable. Normaly i have to lower less then 10% of dragon, then  Mind control him with scpecial quest item provided, then once dragon controled, i have use his spell and forge the seal. Then i should be able to loot it.

**Comment by Zebouski** [comment] 2023-06-20 20:57
looks like a duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3067 and https://github.com/slowtorta/turtlewow-bug-tracker/issues/467

**Comment by Ttourro** [comment] 2023-06-21 08:07
issue #467  here since November 2021. So sad. No one gonna change it. Never. ;(

**Comment by Gurky-Turtle** [comment] 2023-06-22 16:10
https://github.com/slowtorta/turtlewow-bug-tracker/issues/467

**Closed by Gurky-Turtle** 2023-06-22 16:10 UTC
