### ISSUE TITLE
Unable to engage in combat in Dustwind Cave

### ISSUE THREAD

**Issue by KibbyCreekwood** [slowtorta/turtlewow-bug-tracker#4824] opened 2023-10-19 05:59 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. This seems to only be an issue with my specific character, as I have attempted to show this to other players and they do not have the same issue, but can witness me having this issue. When my character (Jamaikib, femme troll hunter) attempts to enter Dustwind Cave in Durotar, she becomes unable to engage in combat. Her first combat hit generally hits, but all subsequent hits are misses or absorbs. I also brought this to the attention of GMs and demonstrated this bug to GM Waldt, who witnessed me attempting to kill several mobs within the cave. They advised me to exit the game, delete my WDB folder, and then restart the game. I did so, and still experienced this bug. This happens to ALL mobs existing within the cave, and ranged mobs are still able to target and hit me, but I cannot hit them, similar to when a mob has lost its target and is returning to its patrol location, but the mob remains targeting and attacking me while I am unable to damage it. Other players are also able to witness me missing in combat, and are able to engage in combat normally, including other hunters. No special actions or movements are required except for entering the cave. Mobs with the same names and IDs as mobs inside of the cave are able to be engaged in combat normally. If I attempt to engage a mob that is within the cave while I am on the outside of the cave, the same bug occurs, keeping me from damaging them.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I should uhhh... be able to kill mobs in the cave.

**Comment by KibbyCreekwood** [comment] 2023-10-19 06:01
To clarify, when I said:

"Mobs with the same names and IDs as mobs inside of the cave are able to be engaged in combat normally."

What I meant was,

Outside of the cave, there are mobs identical to the ones inside of the cave. I can engage in combat with the ones that are outside of the cave normally, but ones that are inside of the cave, I am unable to target and engage in combat.

**Comment by KibbyCreekwood** [comment] 2023-10-19 06:11
A friend of mine will be playing soon, so we will be trying some experiments to (hopefully) give you more to work with. Will be attempting a duel wherein they start in the cave, one where they enter the cave after we start combat, and one where I start in the cave and they start outside it. I'm not sure if that'll actually be helpful, but it will at least be funny for us lol\

**Comment by KibbyCreekwood** [comment] 2023-10-19 06:24
Update: Physical combat works against enemies, but I cannot use ranged or pet attacks. As a hunter, this is essentially not being able to do combat

**Comment by KibbyCreekwood** [comment] 2023-10-19 06:34
Okay, nevermind--physical does NOT work against enemies sometimes. Can't figure out a way to reproduce it, it's just totally random.

In terms of duels--this is possible within the cave as long as we are not in a party, which causes us to be unable to fight each other. But that seems like it might be intended, as it works everywhere and seems unrelated to the bug.

**Comment by Muigin** [comment] 2023-10-20 09:50
Duplicate of #3659

**Closed by Muigin** 2023-10-20 09:50 UTC
