### ISSUE TITLE
Mailbox at Nordanaar gone

### ISSUE THREAD

**Issue by Oledien43** [slowtorta/turtlewow-bug-tracker#5430] opened 2023-11-29 18:01 UTC
**Please, provide a clear description what the bug is:**

Mailbox at Nordanaar gone, either I specifically can't see it for whatever reason (I deleted wdb and restarted my game ofc) or its been moved/removed

**Comment by twowTurtReynolds** [comment] 2023-11-29 18:06
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5427

**Closed by twowTurtReynolds** 2023-11-29 18:06 UTC
