### ISSUE TITLE
Good god there's so many baxxils

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#4109] opened 2023-08-07 21:17 UTC
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/25846834/c4fe7980-39cd-4195-a334-8ca4feaf2bb1)
this is far watch post, its the quest where you escort this guy back to the goblin town in durotar right? There's so many of him holy shit.

**Comment by twowTurtReynolds** [comment] 2023-12-07 02:49
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4055

**Closed by twowTurtReynolds** 2023-12-07 02:49 UTC
