### ISSUE TITLE
Emerald Blessing very incorrect behavior

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4639] opened 2023-10-08 16:32 UTC
**Please, provide a clear description what the bug is:**
The spell uses aura 191 (SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED) which should NOT have been used for an effect of that kind. That will set the character's speed at a constant 110% no matter what other auras are applied to it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Mount up and walk around
2. Put the aura on yourself
3. Walk around with a mount and look at the speed difference

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=57108

**Expected behavior. Describe how it should work:**
Look at the multitude of spells made by Blizzard as guidance on how to recreate the effect
https://www.wowhead.com/classic/spells?filter=29;31;0
https://www.wowhead.com/classic/spell=13889/minor-speed this is the spell id of the speed on boots enchant

If you want it to have the "increase movement speed without stacking" effect, you should use aura 31 (SPELL_AURA_MOD_INCREASE_SPEED)

**Comment by twowTurtReynolds** [comment] 2023-12-05 04:44
I can no longer reproduce this, it looks like it was fixed in another report.

**Closed by twowTurtReynolds** 2023-12-05 04:44 UTC
