### ISSUE TITLE
Pet Avoidance Missing (demons)

### ISSUE THREAD

**Issue by Spriggit11** [slowtorta/turtlewow-bug-tracker#5962] opened 2024-01-10 15:11 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Summoned demons at level 60 do not have/cannot learn Avoidance
2. Every kind of summoned demon pet lacks avoidance
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

These summoned demons should have or at least be able to learn Avoidance.

**Comment by twowTurtReynolds** [comment] 2024-01-10 17:07
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3383

**Closed by twowTurtReynolds** 2024-01-10 17:07 UTC
