### ISSUE TITLE
Bloodsail Buccaneers rep grinding considered griefing

### ISSUE THREAD

**Issue by Rinsedd** [slowtorta/turtlewow-bug-tracker#4740] opened 2023-10-14 15:47 UTC
**Please, provide a clear description what the bug is:**
The only way to farm Bloodsail Buccaneers is considered griefing, the only npc that gives rep after revered is Jazzrik in the Badlands.
Had 3 GM interractions already.

**Steps to reproduce the behavior with as much detail as possible:**

1.Killed every other member of the steamwheedle, none give bloodsail rep past revered except Jazzrik

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://www.wowhead.com/classic/npc=9179/jazzrik

**Expected behavior. Describe how it should work:**
Either expand the bloodsail compound to give enough rep with dailies / repeatables, or make Booty Bay mobs give rep past revered.

**Comment by KaidenLightbourne** [comment] 2023-10-15 03:26
The easiest fix is to just add the rep from jazzrik to the guards in order to get exalted through guards kill - a more lucrative and RP-thematic way would be through dailies and gatherable turn ins to get rep with the pirates such as: Various rums, coins and treasures that are already in the world that prove no use for anything else and thus gives them monetary value within the game.

**Comment by Rinsedd** [comment] 2023-10-15 11:18
> The easiest fix is to just add the rep from jazzrik to the guards in order to get exalted through guards kill - a more lucrative and RP-thematic way would be through dailies and gatherable turn ins to get rep with the pirates such as: Various rums, coins and treasures that are already in the world that prove no use for anything else and thus gives them monetary value within the game.

something thematical would be nice instead of mindless grind

**Comment by Muigin** [comment] 2023-10-20 09:59
Duplicate of #4326

**Closed by Muigin** 2023-10-20 09:59 UTC
