### ISSUE TITLE
Iron and Gold in Crystalvein Mine (43-44 lvl)

### ISSUE THREAD

**Issue by AKryukov92** [slowtorta/turtlewow-bug-tracker#2909] opened 2023-02-27 06:30 UTC
Current situation
Crystalvein Mine (Stranglethorn vale) is filled with mobs of level 43-44 [Ironjaw Basilisk](https://database.turtle-wow.org/?npc=1551) 
I assume this cave should contain mineral nodes useful to craft some 40+ gear. In case of minerals it is Mithril.
But I found Iron node in this cave.
Coordinates are 
/script local locX, locY = GetPlayerMapPosition("player");DEFAULT_CHAT_FRAME:AddMessage(locX .. ", " .. locY);
0.43170389533043, 049376690387726

I also found 3 Gold veins there with coords
0.44133853912354, 0.48068070411682
0.43542838096619, 0.46420261263847
0.42174848914146, 0.46632874011993

It is wrong, because Iron and Gold are used to craft gear of 25-39 level.

How it should be
This cave should be filled with Mithril nodes.
Gold is supposed to be rare material, so it should spawn no more than 1 node per cave.

**Comment by twowTurtReynolds** [comment] 2023-12-12 04:24
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2919

**Closed by twowTurtReynolds** 2023-12-12 04:24 UTC
