### ISSUE TITLE
Manifestations of Nightmare says that Farana Leafblade is in Nordanaar, but she is at the south of Hyjal

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#5880] opened 2024-01-03 11:57 UTC
**Please, provide a clear description what the bug is:**
![Farana](https://github.com/slowtorta/turtlewow-bug-tracker/assets/40469927/8bce2b87-3ce7-4e5f-983a-41202525ed27)

**Steps to reproduce the behavior with as much detail as possible:**

1. Take [Manifestations of Nightmare](https://database.turtle-wow.org/?quest=41022)
2. Read the topmost section.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=41022

**Comment by twowTurtReynolds** [comment] 2024-01-04 03:21
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4648

**Closed by twowTurtReynolds** 2024-01-04 03:21 UTC
