### ISSUE TITLE
fallddamage with slowfall calcualted wrong

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2675] opened 2023-01-08 17:23 UTC
**Please, provide a clear description what the bug is:**

lets consider 4 points:
A: THe highest point you start falling
B. The pointed you actiavted a slowfall ability
C. THe point slowfall buff expires
D. THe point you land on the ground

so combined, you were falling actiavted sowfall bt the buff expired before you landed and you fell some more without any slowfall activate before you touched ground.

what happens is you receive the full fall damage for the hole distance A to D. the slowfall in between is ignored

If your slow fall runs out a second before you land, then you still die 

**Expected behavior. Describe how it should work:**

You should only take the fall damage from point C. to D., so damage from wehre slowfall expired and you started to free fall again.

**Comment by Kruxis** [comment] 2023-01-11 08:39
Where did you fall 30 seconds? o_O

**Comment by geojak** [comment] 2023-01-11 09:51
i jump trough a window in ironforge, then i fell trough the world with slowfall. 1 second before i landed my slowfall ran out and i crasehd hard into old ironfroge. being the only skeleton there in ages

**Comment by Kruxis** [comment] 2023-01-11 12:18
That's good to know because thats a different Spell

**Comment by RUTHINAS** [comment] 2023-01-13 01:30
Duplicate of #1589

The fall damage is actually even more brutal than just the damage from A to D. All the time spent slow falling is added to a fall damage _timer_, the result of which can be lethal if the slow fall effect were to end just a bit before touching down. This turns, for example, the Darkmoon Faire cannon into a death trap, and parachutists need to be careful to only do HALO (High Altitude, Low Opening) jumps, as opening the 10 second parachute too early would surely be lethal. This seems to apply to any kind of slow fall effect.

The bug remains unfixed.

**Closed** 2023-01-13 01:59 UTC
