### ISSUE TITLE
High Inquisitor Whitemane Won't Resurrect Scarlet Commander Mograine

### ISSUE THREAD

**Issue by MariaKilsved** [slowtorta/turtlewow-bug-tracker#5913] opened 2024-01-06 09:24 UTC
**Please, provide a clear description what the bug is:**
When fighting High Inquisitor Whitemane in Scarlet Monastery Cathedral, she will cast the spell Scarlet Resurrection on Scarlet Commander Mograine. However, Scarlet Commander Mograine is not resurrected. It seems like the sleep effect cast while she is resurrecting him isn't properly cast. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Enter Scarlet Monastery Cathedral.
2. Fight Scarlet Commander Mograine and kill him.
3. Place damage over time effects on High Inquisitor Whitemane (this step might be unnecessary).
4. Fight High Inquisitor Whitemane until she reaches ~50% health. 
5. Receive a sleep effect from High Inquisitor Whitemane.
6. As High Inquisitor Whitemane is casting Scarlet Resurrection, the stun effect will somehow be broken and you will be able to attack her. 
7. Attack High Inquisitor Whitemane while she is casting Scarlet Resurrection (this step might be unnecessary).
8. Scarlet Commander Mograine will not be resurrected.
9. Attempts at resetting the encounter will not prevent this bug. Instead, a seemingly successful cast of Scarlet Resurrection will have no effect.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=3977
NPC: https://database.turtle-wow.org/?npc=3976

**Expected behavior. Describe how it should work:**
During this boss encounter, players should kill Scarlet Commander Mograine. High Inquisitor Whitemane will then enter through a door, and players will fight her instead. When she has lost a certain health %, she will put a sleep effect on all players in the party. While the party is incapacitated, she will resurrect Scarlet Commander Mograine using Scarlet Resurrection. The sleep effect on the party will not break prematurely, making it impossible to interrupt her. Any damage over time effects on High Inquisitor Whitemane will be unable to interrupt her spellcast.

**Comment by twowTurtReynolds** [comment] 2024-01-06 12:19
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5876

**Closed by twowTurtReynolds** 2024-01-06 12:19 UTC
