### ISSUE TITLE
Incorrect t0.5 item stats on TelAbim

### ISSUE THREAD

**Issue by khuongdo0214** [slowtorta/turtlewow-bug-tracker#5233] opened 2023-11-16 03:41 UTC
**Please, provide a clear description what the bug is:**
The T0.5 sets on Tel Abim do not seem to have the updated stats mentioned in https://forum.turtle-wow.org/viewtopic.php?t=10971.
 In particular, Hunters' Beastmaster set seems to have the wrong stats.

**Steps to reproduce the behavior with as much detail as possible:**

1. Obtain Beastmaster's Gloves by doing the t0.5 quest line.
2.  See that it doesn't have the 1% hit noted in the T0.5 Midpatch Itemization Changes post.
3.  Same for Beastmater's belt and beastmaster's bindings, and I guess others too.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= https://database.turtle-wow.org/?item=22015
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
They should have the updated stats that were supposed to have gone live on Oct 17.

**Comment by Zebouski** [comment] 2023-11-16 19:54
Just the gloves right? Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5225 and https://github.com/slowtorta/turtlewow-bug-tracker/issues/4893 

not specific to telabim

**Closed** 2023-11-16 19:56 UTC

**Comment by khuongdo0214** [comment] 2023-11-16 22:06
> Just the gloves right? Duplicate of #5225 and #4893
> 
> not specific to telabim

No, even the gloves have a different stat. The gloves currently have + crit chance to pet rather than + hit on telabim. The problem is not that it's missing the stat, the problem is it's having the pre-itemization change stats.

**Comment by Zebouski** [comment] 2023-11-17 04:21
Just checked on telabim
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/11151284/5f2bf00c-af09-4092-b661-98560971e5ee)
The gloves dont have +crit, you need to clear your wdb. It has the buggy post itemization update stats. 

ticket confirmed duplicate
