### ISSUE TITLE
Not able to enchant leggins of the inferno with invocation of greater protection

### ISSUE THREAD

**Issue by Ravenya333** [slowtorta/turtlewow-bug-tracker#5199] opened 2023-11-13 11:35 UTC
When i try to enchant my leggins of the inferno https://database.turtle-wow.org/?item=61265 with Invocation of greater Protection https://database.turtle-wow.org/?item=92006
there comes the message that the pants are an invalid target

**Comment by Muigin** [comment] 2023-11-13 11:37
Duplicate of #4788

**Closed by Muigin** 2023-11-13 11:37 UTC
