### ISSUE TITLE
survival panel merged with engineering

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#922] opened 2022-01-16 18:28 UTC
**Please, provide a clear description what the bug is:**
![WoWScrnShot_011622_170821](https://user-images.githubusercontent.com/25199983/149672879-d99eb336-0fb1-4b0d-8c8d-a5febbf652de.jpg)

i think this picture should explain the sitaution.
the tents and torches recipe seem to work, i can clikc them. the wrong engineer things cant be displayed when i try to click them.
this problem must have started after i became a gnomish engienering because it wasnt always like this

**Expected behavior. Describe how it should work:**
enginering should not bug out survival

**Comment by LeopoldHock** [comment] 2022-01-18 13:15
Known issue. Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/801

**Closed by LeopoldHock** 2022-01-18 13:15 UTC
