### ISSUE TITLE
Pattern Leaning(Cleaning Cloth)

### ISSUE THREAD

**Issue by truekripp** [slowtorta/turtlewow-bug-tracker#6380] opened 2024-02-28 11:59 UTC
BUG: Skill Profession skill learning.
I tried to learn the first few Survival Skill patterns, which are sold by the Survival guy in northern STV.
I bought 3, and right clicked them in a fast sequence in my bags(they have a cast time, so I waited for that to finish, on each usage)
Only two of the three skills were given to my Survival book.

No idea how to reproduce, but I guess it happens if you try to learn several patterns efficiently, in a row.. 
I clicked the patterns I needed(one after another, in quick sequence), while leveling Survival. 
If I go to the vendor who sells the pattern, it tells me that I already have learned the pattern(I even spent the gold to buy a second, to make 100% sure). I reloaded the game, relogged, removed WDB, reset my entire game folder but the "Cleaning Cloth" skill will not appear in my Survival window.
The GM who contacted me has taught me a spell called "Cleaning Cloth" in the general tab of my skill book. Clicking that gives me the error that says "You already know Cleaning Cloth", which does align with the pattern, but doesn't align with my Survival Skill Book.
Here's a picture for reference: https://imgur.com/a/0qKdSsU
Cleaning Cloth located in my usual Skill Book. No Cleaning Cloth in my Survival skill book, Tells me I already know that spell when I click it.

NPCS/Items
NPC: https://database.turtle-wow.org/?npc=50070
Item: https://database.turtle-wow.org/?item=60002
Spell: https://database.turtle-wow.org/?spell=46069

How it should work
I should buy the pattern from the Survival NPC. Then right click it to learn the actual skill. It should appear in my Survival window, and then I should be able to craft it.

**Comment by twowTurtReynolds** [comment] 2024-02-28 13:06
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6125

**Closed by twowTurtReynolds** 2024-02-28 13:06 UTC
