### ISSUE TITLE
Grime-Encrusted Ring Bug

### ISSUE THREAD

**Issue by Homemadecherrypie** [slowtorta/turtlewow-bug-tracker#3495] opened 2023-05-20 01:05 UTC
**Please, provide a clear description what the bug is:**
Quest does not provide Brilliant Gold Ring as it should
**Steps to reproduce the behavior with as much detail as possible:**

1. Get grime encrusted ring
2. Accept quest
3. Turn it in at the correct machine in Gnomeregan
4. Enjoy your lack of quest reward.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=9326
Quest: https://database.turtle-wow.org/?quest=2945
Missing Reward: https://database.turtle-wow.org/?item=9362

**Expected behavior. Describe how it should work:**
Grime-Encrusted ring goes in machine, Brilliant Gold Ring comes out.

**Comment by redmagejoe** [comment] 2023-05-23 01:33
You have to talk to the machine multiple times.  This quest is working as intended on current version.

@slowtorta Please close this.

**Closed** 2023-05-23 07:44 UTC
