### ISSUE TITLE
Quest issue

### ISSUE THREAD

**Issue by spndxx** [slowtorta/turtlewow-bug-tracker#5861] opened 2024-01-01 03:08 UTC
**Please, provide a clear description what the bug is:**
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/154472019/8ba1e5c1-433e-4edd-b8a9-2a408d7e828c)

I am not able to complete it even tho it says its completed. 
I do not want to abandone because I won't be able to find them again that fast.
Please help me fixt it or count it as completed and distribute the prize from the quest.
Thank you. 

**Steps to reproduce the behavior with as much detail as possible:**

1. First there were 4 GMs to be tagged for the quest, later "Dated" has been removed.
2. Deleted my WDB but still cant return the quest. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=50321
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by spndxx** [comment] 2024-01-01 03:09
Happy New Year!

**Comment by twowTurtReynolds** [comment] 2024-01-01 03:25
Happy new year!

Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5818, read the comments here.

**Closed by twowTurtReynolds** 2024-01-01 03:25 UTC
