### ISSUE TITLE
rockbiter and blood fury dont stack.

### ISSUE THREAD

**Issue by guruvex** [slowtorta/turtlewow-bug-tracker#4059] opened 2023-07-31 01:39 UTC
**Please, provide a clear description what the bug is:**
not sure if its a bug or intended. but i can only have blood fury or rockbiter rank 1 effecting me at a time.

not sure if this effects it or not
im hard core, with glyph of slow and steady and exhaustion on.

**Comment by twowTurtReynolds** [comment] 2023-12-07 03:40
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3994

**Closed by twowTurtReynolds** 2023-12-07 03:40 UTC
