### ISSUE TITLE
Blood Frenzy Feral Druid Talent

### ISSUE THREAD

**Issue by IlluinDruid** [slowtorta/turtlewow-bug-tracker#2714] opened 2023-01-18 12:33 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. _When you turn on the TF, the buff from the Blood Frenzy talent appears for only a split second, and then immediately the timer switches to 11_
2. _The TF turns on for 13 seconds and also switches to 12 after a split second_

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=5217
Spell: https://database.turtle-wow.org/?spell=45722
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
_Both buffs should hang on the feral for the same time_

**Comment by Zeyla-TW** [comment] 2023-03-14 10:22
I believe you're referring to the differing buff durations, in which case this https://github.com/slowtorta/turtlewow-bug-tracker/issues/2418 is most likely the cause of your concern. If your issue is not related to brutal impact increasing the duration of tiger's fury, then we can re-open this issue. For now though, closing as duplicate.

**Closed by Zeyla-TW** 2023-03-14 10:22 UTC
