### ISSUE TITLE
Argent Dawn quartermasters don't give a vendor option

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#2850] opened 2023-02-17 03:13 UTC
When speaking to any of the quartermasters, none of them give me any vendoring options. I am currently friendly with AD. I've experienced this on past characters as well. I recall being able to vendor once I hit honored (on a previous alt). I've tried deleting WDB, reloading UI, trying chars on different accounts, etc.

**Comment by Haaxor1689** [comment] 2023-02-21 14:59
Duplicate of #1565

**Closed by Haaxor1689** 2023-02-21 14:59 UTC
