### ISSUE TITLE
Avoidance on Warlock Pets

### ISSUE THREAD

**Issue by Spriggit11** [slowtorta/turtlewow-bug-tracker#4792] opened 2023-10-17 14:36 UTC
**Demons from old Warlock characters don't have avoidance**

**Steps to reproduce the behavior with as much detail as possible:**

1. Summon demon from characters made before summoned demons were given avoidance skill
2. Demons do not have avoidance skill
3. The old tome which offered the avoidance skill is not learnable

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=voidwalker, succubus, imp, felhound
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
I thought warlock pets hadn't been given avoidance until I noticed a post from a newer player to Turtle showing that his pet clearly had it. My warlock was made several years ago so my guess is that the change somehow doesn't affect the older character's summons. This was the case with the lack of avoidance on hunter pets until a recent patch made -newly- tamed animals come with the avoidance skill after level 50.

**Comment by Muigin** [comment] 2023-10-19 05:23
A solution to this is pending. ETA unknown.

**Comment by twowTurtReynolds** [comment] 2023-12-03 23:35
Closing as dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3383

**Closed by twowTurtReynolds** 2023-12-03 23:35 UTC
