### ISSUE TITLE
Trueshot damage issue

### ISSUE THREAD

**Issue by tedddyli** [slowtorta/turtlewow-bug-tracker#4690] opened 2023-10-11 09:32 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. trueshot does the same damage as my weapon attack instead of  what it should be -- +50 damage
2. Only happens to me, my char name is Hcqi
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by tedddyli** [comment] 2023-10-12 10:05
It's the crossbow from the quest award from SW vault

**Comment by Muigin** [comment] 2023-10-19 05:51
The Goldplated Royal Crossbow has a weapon attack of 86 to 131.  Are you saying that your Trueshot is only doing between 86 and 131 damage before armor, such as on an Apprentice Training Dummy?

**Comment by twowTurtReynolds** [comment] 2023-12-05 03:58
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2604

**Closed by twowTurtReynolds** 2023-12-05 03:58 UTC
