### ISSUE TITLE
Power of the Scourge is not working....

### ISSUE THREAD

**Issue by MaxLovved** [slowtorta/turtlewow-bug-tracker#4972] opened 2023-10-30 09:06 UTC
**Please, provide a clear description what the bug is:**
Hello there! The Power of the Scourge is not working.

**Steps to reproduce the behavior with as much detail as possible:**
1.I got the Power of the Scourge from Naxxramas raid this week.
2. Use the Power of the Scourge on Rime Covered Mantle.
3. The Spell Damage +15 and +1% Spell Critical Strike form Power of the Scourge is not working.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Power of the Scourge's ID 23545.

**Expected behavior. Describe how it should work:**
![BUG1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149350452/1afc6add-3512-47f7-9cac-48d80162a8b9)

**Comment by MaxLovved** [comment] 2023-10-30 09:11
Hello there! If Power of the Scourge is working, The Spell Power will add to 671 and Crit Chance will add to 25.71%, i think.
Hope Game Engineer can solve this bug.

**Comment by twowTurtReynolds** [comment] 2023-11-20 04:21
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3361 

Please read the advice there.

**Closed by twowTurtReynolds** 2023-11-20 04:21 UTC
