### ISSUE TITLE
Greater paladin blessings dont work

### ISSUE THREAD

**Issue by lyssebabz** [slowtorta/turtlewow-bug-tracker#3176] opened 2023-04-05 08:44 UTC
**Please, provide a clear description what the bug is:**
When trying to use any of the Greater blessing buffs as a paladin, it dosen't apply. It eats reagent and does nothing else.

**Steps to reproduce the behavior with as much detail as possible:**

1. Click Greater blessing of sanctuary
2. Confirm you didn't get buff
3. Click Blessing of sanctuary
4. confirm you got the buff

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: 
https://database.turtle-wow.org/?spell=25917
https://database.turtle-wow.org/?spell=25939
https://database.turtle-wow.org/?spell=25951
https://database.turtle-wow.org/?spell=25920
https://database.turtle-wow.org/?spell=25946
**Expected behavior. Describe how it should work:**
it should buff you

**Comment by cyaohiri** [comment] 2023-04-05 09:15
Duplicate of #3175.

**Comment by ratkosrb** [comment] 2023-04-05 18:00
Should be fixed once this commit goes live https://github.com/slowtorta/turtle-wow/commit/159d7e419d42b2913a1150288bbf87ea3f82d785

**Closed by ratkosrb** 2023-04-05 18:00 UTC
