### ISSUE TITLE
Quest Broken Cliff Inspection - wrong rep reward

### ISSUE THREAD

**Issue by Gedodile** [slowtorta/turtlewow-bug-tracker#5745] opened 2023-12-24 11:02 UTC
As Alliance you get a horde reputation reward for quest "Broken CLiff Inspection" in Stonetalons: 	"Your Durotar Labor Union reputation has increased 100".

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:38
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5688

**Closed by twowTurtReynolds** 2023-12-25 00:38 UTC
