### ISSUE TITLE
Invocation of Shattering not usable on Crown of Destruction

### ISSUE THREAD

**Issue by mrdoxy** [slowtorta/turtlewow-bug-tracker#5650] opened 2023-12-19 13:55 UTC

**Comment by Zmitrok1984** [comment] 2023-12-19 14:03
wait till tomorrow. will be fixed in 1.17.1

**Comment by twowTurtReynolds** [comment] 2023-12-19 14:53
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788

**Closed by twowTurtReynolds** 2023-12-19 14:53 UTC
