### ISSUE TITLE
Inferno no rewards

### ISSUE THREAD

**Issue by hentspents** [slowtorta/turtlewow-bug-tracker#5628] opened 2023-12-17 01:19 UTC
When you hit 60 and you have done inferno quest you dont get any rewards 

**Steps to reproduce the behavior with as much detail as possible:**

1. Start HC 
2. Get to lvl 59 and finsih inferno chain quest
3. Hit 60 

**Expected behavior. Describe how it should work:**
if you get 60 with hc challange and inferno quest done you should get a mail into the mailbox with youre rewards for completing this hard challange

**Comment by twowTurtReynolds** [comment] 2023-12-17 01:41
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5627

**Closed by twowTurtReynolds** 2023-12-17 01:41 UTC
