### ISSUE TITLE
Wrath of Cenarius

### ISSUE THREAD

**Issue by Shibarashi** [slowtorta/turtlewow-bug-tracker#4080] opened 2023-08-04 06:04 UTC
**SoR on paladin cannot activate this effect, but it is the same mechanic like a Zandalarian Hero Charm, and proc chance seems not like 5%, only like 1-2% it is maximum, what made this ring is OVER Usless, 1 Proc per 1 minutes during 40+ spell casts effects( lifedrains, shadow oils, judgments of SOR, consicrations) some near 2.2% and  it is 132/6=22 SPD that a low for this item, it's ring now worse then most of aq20/zg rings**

**Im playing on paladin a lot and i know about fixes who made impossible to activate this ring on every tick of Consicration, but this proc chance a very very low, and cannot be activated by SoR, and proc chance from the another sources has lowed, not 5%**

1. https://www.wowhead.com/classic/item=21190/wrath-of-cenarius
2. 
3. 

**[Spell ID: 25906]**

**Please do something with this, it is BiS ring must to be for Ret Paladins, and here i cant realease it**
Thx for attention

**Comment by ConcernedTurtler** [comment] 2023-08-04 23:26
a bunch of crybabies complained about this item being too good a few months ago so it got nerfed big time.

**Comment by Shibarashi** [comment] 2023-08-05 05:35
> a bunch of crybabies complained about this item being too good a few months ago so it got nerfed big time.
Yes, I understand, but it should be good, why make top rings in the game, junk of the ZG level, and even worse, a profit of 22 spd, that's COOL, i understand the fix with the consicration and aoe pack's of mob, but not proc chance from another soureces, and absence of proc from SoR

**Comment by Shibarashi** [comment] 2023-08-08 16:19
> SoR Hits are considered meele Hits not Spell Hits when it comes to proccing stuff. Changing it would be a huge nerf for Palas but the right thing to do maybe. The backlash would be big unless crusader strike is made good and exocism baseline usable. But current pala meta is all about that sor doubling proccs which new paladins often see completely unaware of because it's werid

Isnt, it is a melee attack by magical type skill mechanics. not correct he must to activate WoC, this attack is considering a stacks of Zandalarian Hero Charm, so, it is a mechanical of spell casting, just a speed cast and damage variate of Attack speed of weapon, this is a special one of the all WoW classic mechanics

**Comment by twowTurtReynolds** [comment] 2023-12-07 03:19
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3243

**Closed by twowTurtReynolds** 2023-12-07 03:19 UTC
