### ISSUE TITLE
The BUG TRIO in TAQ finally killed Lord kri BUG

### ISSUE THREAD

**Issue by yebingfen** [slowtorta/turtlewow-bug-tracker#5772] opened 2023-12-26 03:36 UTC
**Please, provide a clear description what the bug is:**
My team killed the BUG TRIO in TAQ, and finally killed Lord kri, but after killing Lord kri, his body disappeared.
This BUG occurred around 25.12.2023 14:55 server time, and caused us con't loot his drop item, waiting for your reply.
server : Nordanaar
ID : dovedaily

**Steps to reproduce the behavior with as much detail as possible:**

1.My team killed the BUG TRIO in TAQ, and finally killed Lord kri 
2. after killing Lord kri, his body disappeared.
3. This BUG occurred around 25.12.2023 14:55 server time, and caused us con't loot his drop item

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=15511
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Because Lord kri's body disappeared, we did not see the drop table and could not loot his drop items, please inform us of the drop and issue this drop

**Comment by twowTurtReynolds** [comment] 2023-12-26 03:49
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5768, use that report instead for further discussion.

The message I have posted there remains true here.

**Closed by twowTurtReynolds** 2023-12-26 03:49 UTC
