### ISSUE TITLE
BR - Hunters can send pet on enemies before the gates are opened

### ISSUE THREAD

**Issue by tristanwagner** [slowtorta/turtlewow-bug-tracker#4445] opened 2023-10-01 23:50 UTC
**Please, provide a clear description what the bug is:**

Hunters can send pet on enemies before the Blood Ring gates are opened. The pet will  bypass  the closed door. When I witnessed this, the hunter was using an owl and was very well aware of that since he did  it at every start  of match.

**Steps to reproduce the behavior with as much detail as possible:**

1. Queue Blood Ring as a  hunter
2. Somehow target enemy player
3. Send pet to attack enemy player

**Expected behavior. Describe how it should work:**

Players shouldn't be able to target enemies before  the match have started, and the pet  shouldn't be able to bypass the closed  doors

**Comment by twowTurtReynolds** [comment] 2023-12-06 20:15
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3985

**Closed by twowTurtReynolds** 2023-12-06 20:15 UTC
