### ISSUE TITLE
Soul Link buff doesn't apply to Enslaved Demons or caster. (Tel'Abim)

### ISSUE THREAD

**Issue by Rangtuk** [slowtorta/turtlewow-bug-tracker#5781] opened 2023-12-27 01:22 UTC
**Please, provide a clear description what the bug is:**
[Unconfirmed whether working on Nordanaar]
Soul Link is castable and will consume mana when you have an enslaved demon (either random mob or Infernal/Doomguard), however the buff doesn't actually get activated
**Steps to reproduce the behavior with as much detail as possible:**

1. Summon an Infernal (Inferno) or Enslave your local demon (unconfirmed if working with Curse of Doom/Ritual of Doom)
2. Cast Soul Link
3. Cry that Soul Link doesn't work unless its a normal summon

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=19028

**Expected behavior. Describe how it should work:**
Per the 1.16.1 class update notes (and the Soul Link spell description), Soul Link should be appliable to all enslaved variety demons

**Comment by twowTurtReynolds** [comment] 2023-12-27 01:26
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2497

**Closed by twowTurtReynolds** 2023-12-27 01:26 UTC
