### ISSUE TITLE
Regen Items with Priest's Meditation Talent

### ISSUE THREAD

**Issue by Lexiebean** [slowtorta/turtlewow-bug-tracker#1750] opened 2022-07-31 09:46 UTC
Regen items with the "Allows 5% of your Mana regeneration to continue while casting" effect ([Meditation Rank 1 (14521)](https://database.turtle-wow.org/?spell=14521)) do not stack with the Priest's talent [Meditation Rank 2 (14776)](https://database.turtle-wow.org/?spell=14776) or [Meditation Rank 3 (14777)](https://database.turtle-wow.org/?spell=14777)

Item examples:
https://database.turtle-wow.org/?item=19369
https://database.turtle-wow.org/?item=60564
https://database.turtle-wow.org/?item=83465

My tests: https://i.imgur.com/n7oA2Gt.png

Values are the mana ticks that I observed while regening directly after casting a spell.

Expected results would have been to see an increase in mana per tick when using 2/3 or 3/3 Meditation while wearing the items.

**Comment by nyronic** [comment] 2022-10-24 12:03
I just discovered this same issue myself. While doing my own tests I observed the same exact behavior the OP has described. Ranks 2 and 3 of Meditation cause equipable items with cast regen to do nothing.

**Comment by cyaohiri** [comment] 2022-10-24 12:29
Shouldn't it stack with rank 1 as well? I understand it doesn't as the item uses the same aura as the talent, but that doesn't seem right.

**Comment by Trofogol** [comment] 2023-02-27 16:12
This spell called Meditation, I think the issue is about it
https://database.turtle-wow.org/?spell=14521

**Comment by schanzee** [comment] 2023-05-11 15:10
Any way to get this looked at? Super disappointing to get these items only to realise they don't work at all for priests if you have 3/3 Meditation which is a staple in literally every priest spec.
You can only pick 1/3 Meditation and need at least 3 of these items to gain the benefit of one of them over just picking 3/3 Meditation and taking something else.

The issue seems to be that you used the 1/3 Meditation talent for the effect which you can stack multiple times but any amount gets canceled out by a 2/3 or 3/3 talent if you have it.

Can you make it so the effect applies the Druid (https://database.turtle-wow.org/?spell=17106) or Mage (https://database.turtle-wow.org/?spell=18462) talent instead if you're a priest?

**Comment by OonaFae** [comment] 2023-05-13 04:02
Would very much like to see a fix for this.  Especially since the new raid has an item with this feature.

**Comment by Gurky-Turtle** [comment] 2023-07-11 23:17
Should be fixed in patch 1.16.6

**Comment by schanzee** [comment] 2023-12-04 17:03
this is broken again

**Comment by twowTurtReynolds** [comment] 2023-12-13 18:48
Thorough details in https://github.com/slowtorta/turtlewow-bug-tracker/issues/5586

**Comment by ConcernedTurtler** [comment] 2024-01-10 02:05
Any update on whether or not this is being looked into?

**Comment by Dragunovi** [comment] 2024-01-15 13:23
Leaving this open to be safe but these issues should've been alleviated when the spell used for equipment was swapped from the Priest talent to its standalone unique spell just made for equipment.

**Comment by schanzee** [comment] 2024-01-19 02:41
Not working for me right now

**Comment by Dragunovi** [comment] 2024-01-25 20:41
This issue should be finally eliminated with the next server restart after manually changing all items to use the new custom spell version of the effect instead of using the Priest talent version, lets hope it never comes back.

**Closed by Dragunovi** 2024-01-25 20:41 UTC
Labels: Priest, Spell, Item, Needs Replication
