### ISSUE TITLE
THe qeust rise obsidion can not be compelted

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1152] opened 2022-02-23 18:13 UTC
**Please, provide a clear description what the bug is:**

the quest can not be completed, the scripted event is missing

**Steps to reproduce the behavior with as much detail as possible:**

1. start the qeust
2. the npc doesnt spawn
3. obsidion cant be attacked

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?quest=3566

**Expected behavior. Describe how it should work:**

quest can be completed 
https://www.youtube.com/watch?v=leraa1Dtzng
https://classic.wowhead.com/quest=3566/rise-obsidion

**Comment by slowtorta** [comment] 2022-02-23 19:36
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/507

**Closed by slowtorta** 2022-02-23 19:36 UTC
