### ISSUE TITLE
The quest : The icy menace

### ISSUE THREAD

**Issue by muse518** [slowtorta/turtlewow-bug-tracker#5890] opened 2024-01-04 16:48 UTC
**Please, provide a clear description what the bug is:**
Since the player Dated was removed from the quest list, the quest is showing as completed, but I can't complete the quest from the npc anymore.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=https://tieba.baidu.com/p/8845464459?fid=27981065&pid=149561915360&cid=0#149561915360
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=
![_20240104171051](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149399080/fac4cb02-c3b2-4fc2-b293-94b60b51ce54)
![_20240104171116](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149399080/2fa9339b-f413-43c1-bd76-dea15c02892a)

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2024-01-04 16:51
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5818

**Closed by twowTurtReynolds** 2024-01-04 16:51 UTC
