### ISSUE TITLE
Quest: [An Infinite Hunt]. Item not usable. The GM confirmed.

### ISSUE THREAD

**Issue by Bravian-XP** [slowtorta/turtlewow-bug-tracker#4943] opened 2023-10-28 15:37 UTC
Quest: [[An Infinite Hunt]](https://database.turtle-wow.org/?quest=80411)

I need to use quest item (red crystal) on the ground, it should summon a NPC. But it's not active. And no one else cant use it.
 I thought I had to wait for the event to start, but I've been here for over an hour. 

GM said that its seems to be broken.

![World of Warcraft_231028182723](https://github.com/slowtorta/turtlewow-bug-tracker/assets/146672371/f0859146-10c7-413c-a941-4b19f21c832a)

**Comment by Muigin** [comment] 2023-10-30 07:03
Duplicate of #3650

**Closed by Muigin** 2023-10-30 07:03 UTC
