### ISSUE TITLE
Illusion items under Asian servers will cause the set effect to be invalidated

### ISSUE THREAD

**Issue by simonfloy** [slowtorta/turtlewow-bug-tracker#4901] opened 2023-10-25 13:47 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.After transforming the Bloody Gladiator Chain Armor Shoulder Guards and Pants and Chest I was wearing into a rank set, I lost the effects of the 6-piece set I was originally supposed to enjoy
2. When I first reported it to the GM, the GM replied to me that it was just a display error
But after I repeatedly tested the damage and skill values, it was confirmed that I lost my set effect, I was supposed to get 6/6 set effect, but now it's only 3/6, I not only lost my illusion coins, but also my set effect, this is a very frustrating bug and massively appeared in Asian server clients
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Changes only cosmetic effects without losing any set effects or equipment effects

**Comment by simonfloy** [comment] 2023-10-25 13:49
套装在幻化过后失去了套装属性

**Comment by twowTurtReynolds** [comment] 2023-11-22 01:31
I can confirm that you have not lost your set effect. Me personally I have ran with 8/9 t3 with multiple pieces using xmog, and the 8set proc sitll appears as a buff when it should.

If you can provide evidence otherwise, please post as much detail as you can. Otherwise, I am closing as likely not a bug.

**Closed by twowTurtReynolds** 2023-11-22 01:31 UTC
