### ISSUE TITLE
Unable to enchant Leggings of the Inferno with 2% dodge

### ISSUE THREAD

**Issue by hjortmar** [slowtorta/turtlewow-bug-tracker#5544] opened 2023-12-09 18:02 UTC
**Please, provide a clear description what the bug is:**

It is not possible to enchant Leggings of the Inferno with 2% dodge through Invocation of Greater Protection.

**Steps to reproduce the behavior with as much detail as possible:**

1. Right-click on "Invocation of Greater Protection"
2. Select "Leggings of the Inferno" to enchant.
3. Notice that it says "The item is not a valid target." even this is a leg item.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item 1: https://database.turtle-wow.org/?quest=41080
Item 2: https://database.turtle-wow.org/?item=61265

**Expected behavior. Describe how it should work:**

This is a leg item and should be eligible for this enchant.

**Comment by twowTurtReynolds** [comment] 2023-12-09 18:07
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788

Please read the pins.

**Closed by twowTurtReynolds** 2023-12-09 18:07 UTC
