### ISSUE TITLE
Guild Text boxes only have first letter capitalized

### ISSUE THREAD

**Issue by Valamartle** [slowtorta/turtlewow-bug-tracker#1755] opened 2022-07-31 15:20 UTC
**Please, provide a clear description what the bug is:**
Text entered into guild text boxes only has the first letter capitalized, except GMotD. I couldn't find any other report of it. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Enter text into a text box for any type, Officer note, public note, guild info, except GMotD
2. Once entered, anything past the first letter is forced into lowercase. Noticed this when trying to put a discord link in Guild Info box. It shows correctly in GMotD though. 

**Expected behavior. Describe how it should work:**
In notes and guild info, text should have more than just the first letter capitalized.

**Comment by slowtorta** [comment] 2022-08-11 19:59
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1898

**Closed** 2022-08-16 01:48 UTC
