### ISSUE TITLE
People can roll on target dummy loot

### ISSUE THREAD

**Issue by Teknishun7** [slowtorta/turtlewow-bug-tracker#5850] opened 2023-12-31 02:42 UTC
Upon destruction people from my party could roll on the Truesilver bar contained in the target dummy
Only the engineer that placed the target dummy should be able to loot it and people from the party souldnt be able to loot the dummy

Target dummy that I noticed the bug on: https://database.turtle-wow.org/?spell=19814

Item that was rolled for: https://database.turtle-wow.org/?item=6037

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89323351/1bbb1b03-b266-48f3-aef6-a91c8fa8e3d8)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/89323351/d4aa6199-a59d-42a9-acd8-2ab454ec374e)

**Comment by twowTurtReynolds** [comment] 2023-12-31 18:07
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3115

**Closed by twowTurtReynolds** 2023-12-31 18:07 UTC
