### ISSUE TITLE
"Goblin Brainwashing Device" Keeps Resetting Saved Specs.

### ISSUE THREAD

**Issue by Suilan7** [slowtorta/turtlewow-bug-tracker#5753] opened 2023-12-24 15:50 UTC
Hello. 

Character Name: Suilan level 60 Mage.
Character Faction and Race: Alliance, High Elf.
Server: Tel'Abim (PVP)

For quite some item, I have been using "Goblin Brainwashing Device" through out my leveling. Brought item from Donation Rewards. Saving specs worked as it was described by item, used two slots. Unfortunately, once I hit level 60 "Goblin Brainwashing Device" stopped working as it was indented. 

Here is how currently "Goblin Brainwashing Device" works for me.

1. Before logging into the game, I do delete files inside WDB folder.
2. Open the game and log in into character.
3. Once I am in the game, I receive a message in yellow letters "Your saved dual spec has been reset."
4. When I open "Goblin Brainwashing Device" I see that my two saved specs are gone and I have to set them again.
5. Since my two saved specs are gone, I try and save my first spec in my first specialization slot. 
6. As long as I am in the game "Goblin Brainwashing Device" remembers my first saved spec.
7. I log out of the game and log in to the game, and again, I receive a message in yellow letters "Your saved dual spec has been reset." I open "Goblin Brainwashing Device" and I see that my first saved spec that I saved previously is gone. 

Item: https://database.turtle-wow.org/?item=51715

"Goblin Brainwashing Device" with current 2 open slots that I have should save any spec that I choose to and if I log out and log in to the game saved specs should be saved.

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:25
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5582

**Closed by twowTurtReynolds** 2023-12-25 00:25 UTC
