### ISSUE TITLE
Sap procing poison.

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#3185] opened 2023-04-06 13:33 UTC
**Please, provide a clear description what the bug is:**

As a Rogue - Sap is proccing on-hit effects such as Poison, causing Saps to instantly break and aggro targets.

**Steps to reproduce the behavior with as much detail as possible:**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by cyaohiri** [comment] 2023-04-06 13:38
Duplicate of #3168.

**Comment by ratkosrb** [comment] 2023-04-07 00:38
Closed by https://github.com/slowtorta/turtle-wow/commit/d2ca7a881a7185a9a48eb052973de64719047edf

**Closed by ratkosrb** 2023-04-07 00:38 UTC
