### ISSUE TITLE
moving corpses in av mines

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1229] opened 2022-03-24 10:18 UTC
**Please, provide a clear description what the bug is:**

in av mine is a pat of 5 mobs warlking in foramtion.
if zou killen part ot that pat, the dead corpses will keep in formation

**Steps to reproduce the behavior with as much detail as possible:**

1. go av mines
2. find the pat of 5
3. kill a few but not all
4. get out of combat
5. obesrve the corpses keep foramtion

**IDs
![WoWScrnShot_032322_170406](https://user-images.githubusercontent.com/25199983/159894930-b4c08341-8405-430d-9280-854699f40cd5.jpg)
![WoWScrnShot_032322_170403](https://user-images.githubusercontent.com/25199983/159894941-42175b08-d595-4400-9ffa-3ebb1eecb966.jpg)
![WoWScrnShot_032322_170404](https://user-images.githubusercontent.com/25199983/159894946-4b06162e-a0d8-4503-9339-d23c5718f1c3.jpg)
 of affected creatures, items, quests or spells with a link to the relevant page:**
![WoWScrnShot_032322_170408](https://user-images.githubusercontent.com/25199983/159895015-a18f40c4-b1d1-4bb5-8e2c-b71ec359237b.jpg)

**Expected behavior. Describe how it should work:**

coprses dont move

**Comment by slowtorta** [comment] 2022-05-09 12:08
Couldn't reproduce locally, but probably be fixed in the next revision.

**Closed by slowtorta** 2022-05-09 12:08 UTC
Labels: Fixed
