### ISSUE TITLE
[Quest] [NPC] [NPC-Flags] [Event] Grand Magister Rommath

### ISSUE THREAD

**Issue by Jan125** [slowtorta/turtlewow-bug-tracker#5938] opened 2024-01-08 21:36 UTC
**Please, provide a clear description what the bug is:**
Grand Magister Rommath on Nordanaar is currently unclickable.

**Steps to reproduce the behavior with as much detail as possible:**
1. The quest "An Audience With the Prince" makes Rommath unclickable during the RP-event.
2. The event does not seem to have ended properly.
3. Rommath is stuck in unclickableness.
4. Killing and respawning him via GM does not reset him to clickableness.

Login-Logout: No change.
WDB cleared: No change.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
NPC: https://database.turtle-wow.org/?npc=61800
Item: n/a
Quest: https://database.turtle-wow.org/?quest=41240
Spell: n/a
Object: n/a

**Expected behavior. Describe how it should work:**
Like, it should work. He should be clickable.
Not tested:
1. How a server shutdown affects him.
2. How he reacts to horde players in his vicinity.

Edit: Oops, forgot title.

**Comment by twowTurtReynolds** [comment] 2024-01-08 21:50
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5831

**Closed by twowTurtReynolds** 2024-01-08 21:50 UTC
