### ISSUE TITLE
Can't summon Infernal if pet is dead (Until it despawns)

### ISSUE THREAD

**Issue by NoelHG** [slowtorta/turtlewow-bug-tracker#4422] opened 2023-09-30 10:29 UTC
**Please, provide a clear description what the bug is:**

Can't summon Infernal if pet is dead and not despawned. Voidwalker sacrifice, demonic sacrifice all cause this.

**Steps to reproduce the behavior with as much detail as possible:**

1. Use a voidwalker and sacrifice
2. Attempt to cast inferno

**Expected behavior. Describe how it should work:**

It should allow you to use inferno if your pet is dead but not yet despawned

When you use infernal, it should work like a normal summon spell that deletes your existing pet.

**Comment by twowTurtReynolds** [comment] 2023-12-25 20:50
Upon further review, this post is a duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2442. Closing this and tracking the problem there.

**Closed by twowTurtReynolds** 2023-12-25 20:50 UTC
Labels: Warlock, Reproduced, Needs Blizzlike Proof
