### ISSUE TITLE
s(troll priest racial)hadowguard not triggering by spell and range attacks under shield

### ISSUE THREAD

**Issue by JaceEverwood** [slowtorta/turtlewow-bug-tracker#2053] opened 2022-09-02 04:06 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. this is how the troll priest's racial behaved in classic wow
2. 
3. 
[https://www.youtube.com/watch?v=knCUxJ9cFCk&t=212s  9:55](https://www.youtube.com/watch?v=knCUxJ9cFCk&t=595s)
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Tinyfin-github** [comment] 2022-09-02 06:34
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2009

**Closed by Tinyfin-github** 2022-09-02 06:34 UTC
