### ISSUE TITLE
Maraudine Wrangler casts disarm too often

### ISSUE THREAD

**Issue by gnarbrok** [slowtorta/turtlewow-bug-tracker#3135] opened 2023-03-31 13:56 UTC
The mob Maraudine Wrangler spam casts disarm - it casts it on combat, and then casts almost immediately upon the debuff expiring. This seems to be part of a broader class of issues with mob AI where mobs casts some spells way too often. Some mobs are just actually like that. But I can't find any evidence that these mobs are supposed to be this nasty. (Melee classes would be lucky to get even 2 hits in.)

**Steps to reproduce the behavior with as much detail as possible:**

1. Fight Maraudine Wrangler.
2. Get perma disarmed.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?npc=4655
https://database.turtle-wow.org/?spell=8379

**Expected behavior. Describe how it should work:**

They should cast disarm at a reasonable rate (no idea what that rate is unfortunately.)

**Comment by twowTurtReynolds** [comment] 2023-12-09 14:58
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142

**Closed by twowTurtReynolds** 2023-12-09 14:58 UTC
