### ISSUE TITLE
Hunter ranged attack speed bug. Need hotfix.

### ISSUE THREAD

**Issue by Smittych** [slowtorta/turtlewow-bug-tracker#2865] opened 2023-02-20 12:57 UTC
**Please, provide a clear description what the bug is:**
I think quiver doesn't work properly. There is an availability to make your ranged attack speed 0.1 or even less.
You can also decrease your attack speed to infinity long.
Attack speed goes normal after relog, but without quiver attack speed bonus.

**Steps to reproduce the behavior with as much detail as possible:**
1. equip slow weapon + quiver
2. check your attack speed
3. unequip quiver
4. equip fast weapon
5. equip quiver 
6. equip slow weapon
7. check your attack speed again
8. repeat to infinity

For decrease attack speed swap slow and fast weapon in the recipe

I am using this quiver: https://database.turtle-wow.org/?item=8217

**Expected behavior. Describe how it should work:**
Attack speed should be recalculated after quiver equipped or unequipped.

**Comment by ratkosrb** [comment] 2023-02-20 21:20
Do you have some addon that is showing the attack time? Because with the default interface, I do not notice any different after going through these steps. My attack speed is the same at steps 2 and 7.

**Comment by Smittych** [comment] 2023-02-21 09:40
Hi ratkosrb,
No, I don't have any such addon, I watch in on the "Auto attack" skill and character interface.
Its strange, that it not works with you. 
I would like to make some movie where I show these steps, but don't have any soft for that. Think I can share my screen for GM via discord.

**Comment by redmagejoe** [comment] 2023-02-21 19:22
Please provide video evidence reproducing this issue, and also ensure that your character is, in fact, attacking faster and it isn't simply a UI display bug.

**Comment by Smittych** [comment] 2023-02-22 08:22
It seems that attack speed increasing has been fixed. 
But there is still a little bug. Equipping a quiver doesn't affect on your attack speed, but if you switch weapons it recalculates it correctly. So still need to recalculate attack speed on equipping or unequipping a quiver.

**Comment by jameyboor** [comment] 2023-02-23 03:56
Fixed on next update.

**Closed** 2023-02-23 04:07 UTC
