### ISSUE TITLE
[Woven Ivy Cloak] not working properly

### ISSUE THREAD

**Issue by Tyramag** [slowtorta/turtlewow-bug-tracker#5791] opened 2023-12-27 23:31 UTC
If you complete the elite quest <<Bring Down the Priestess!>> in Hinterlands you get to choose Woven Icy cloak as a reward. The cloak as described when struck in combat inflicts 1 Arcane damage to the attacker. It does not work with warrior on defensive stance. It works as intended on battle stance and berserker stance, but when switching in defensive stance it does nothing. While in Battle S, and Berserker S, you can see the dmg in floating text and in the combat log. When i defensive S you dont see neither. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Get the cloak and equip on a warrior
2. switch to defensive stance
3. let a mob attack you

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=51757
Quest: https://database.turtle-wow.org/?quest=60074

**Expected behavior. Describe how it should work:**
It should reflect 1 dmg to all attackers in all stances.

**Comment by cyaohiri** [comment] 2023-12-27 23:35
Duplicate of #4271.

**Comment by Tyramag** [comment] 2023-12-27 23:45
I just read the other thread. So there is no fix on that nor will be any fix in the future then?

**Comment by cyaohiri** [comment] 2023-12-27 23:48
There is no fix yet, but keep in mind there are hundreds of issues waiting to be fixed, so it might take a while.

**Comment by Tyramag** [comment] 2023-12-27 23:56
I understand. And thank you for the amazing work that you do! Have a happy new year.

**Comment by cyaohiri** [comment] 2023-12-28 00:32
Thank you!

**Closed** 2023-12-28 19:58 UTC
