### ISSUE TITLE
Wrong Talent Description 

### ISSUE THREAD

**Issue by Phobos-Programmer** [slowtorta/turtlewow-bug-tracker#3631] opened 2023-06-05 19:22 UTC
**Please, provide a clear description what the bug is:**
1) In the previous big patch rogues got a new ability "Flourish" https://database.turtle-wow.org/?spell=45604. This ability could be improved with "Improved Slice and Dice talent". But if we check the Improved Slice and Dice description we will find that there is no info about Flourish impact. To be honest I started playing rogue in Turtle about one year ago and I just recently incidentally found out about Flourish improvement from "Improved Slice and Dice" talent. I guess we need to change the description and as minimum just leave note about Flourish and as maximum - also rename whole talent, like "Improved Dexterity - Increases the duration of your Slice and Dice and Flourish abilities by 45%.
2) In the previous big patch rogues got a new "Agitating Poison" https://database.turtle-wow.org/?item=65032. Assassin tree has talent to improve poison effects "Vile Poisons" which does not impact threat value. To prevent confusion I suggest add some note, like, "Does not impact threat generation."
3) In TW "Deadly Poison V" https://database.turtle-wow.org/?item=20844 has the unique ability (in comparison to original vanilla)  to apply different stacks for each weapon. This is a good addition and should be described in poison description to let people know about it.

**Steps to reproduce the behavior with as much detail as possible:**
1) Check description "Improved Slice and Dice" talent description, there is nothing about Flourish. Invest 3 points in Improved Slice and Dice and inspect you extended Flourish duration for 45%
2) it's impossible to check it from the client side, all I have is comments from TW developers, that it has only impact on Agitating Poison poison damage and not any impact on hidden poison threat numbers.
3) Apply Deadly Poison V on both weapons and check that target has 2 Deadly Poison debuffs

**Expected behavior. Describe how it should work:**
Current Improved Slice and Dice talent in assassin tree should provide any information about Flourish impact, Vile Poison should have any info about threat, Deadly Poison V description should notify players about two independant stacks per weapon.

**Comment by Muigin** [comment] 2023-10-22 22:22
Duplicate of #3539

**Closed by Muigin** 2023-10-22 22:22 UTC
Labels: Rogue, Spell
