### ISSUE TITLE
Soul Link not affecting enslaved demons. 

### ISSUE THREAD

**Issue by bellmountain** [slowtorta/turtlewow-bug-tracker#4392] opened 2023-09-24 19:11 UTC
According to the tooltip 'Soul Link'  should work on enslaved demons. (blizzlike, always has been)
But for me it doesnt.  I tried a bunch of satyrs in dire maul and none got soul linked to me.
I cast the spell, animation goes off but no buffs get applied to me or the enslaved demon.
Should work exactly like on summoned demon.
Cheers

**Comment by Muigin** [comment] 2023-10-20 07:23
Duplicate of #2497

**Closed by Muigin** 2023-10-20 07:23 UTC
