### ISSUE TITLE
A question about professional cleaning cloths for survival

### ISSUE THREAD

**Issue by quyufan-hue** [slowtorta/turtlewow-bug-tracker#6305] opened 2024-02-19 00:57 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. My Survival major has reached level 60 and I have purchased an outline for cleaning cloths from NPC and learned it. However, when I opened Survival major manufacturing, the option for cleaning cloths was not displayed. I tried to use both Warlock and Druid professions, but they were learned but not displayed, which prevented me from manufacturing cleaning cloths

2. My friend's account can make cleaning cloths, but I also did not have the option to make cleaning cloths when I asked my friend to log in to my account

3.I have added a picture of my problem. Please help me check it and I hope it can be resolved. Alternatively, please let me know if it is due to an account issue or a bug in the game

NPC: Thorn Valley Survival Professional Camp

Item: Outline: Cleaning Cloth
item：Outline: Cleaning Cloth
Outline: Cleaning Cloth：Level: 55
Buy for: 1 50
Sells for: 37 50
Display ID: 15274
Disenchant ID: 0
Allowable Races: All
Race Mask: -1
Allowable Classes: All
Class Mask: -1
Script Name:

**Expected behavior Describe how it should work: When I learn Cleaning Cloth, I can create it in the section of Survival Professional Manufacturing**

![ab6c87e3d6385a771d1cd9107e4ff5f](https://github.com/slowtorta/turtlewow-bug-tracker/assets/67569883/65f60621-bfae-44ca-ade5-c9c9c7b1b873)

**Comment by twowTurtReynolds** [comment] 2024-02-19 00:58
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6125

**Closed by twowTurtReynolds** 2024-02-19 00:58 UTC
