### ISSUE TITLE
Aura: Stealth (Pets)

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#2891] opened 2023-02-24 14:22 UTC
I know this is an "intended" mechanic (which was fixed in TBC, like many other oversights and bugs) but I'll report it nonetheless since it's harmful to server's PvP balance.

Player pets will continue to follow and attack you even after you stealth/prowl/shadowmeld away, regardless of distance. This also works through vanish most of the times.
It gets even more ridiculous with succubus involved as she can follow you around while being invisible herself.

Here we had a change which stopped pets from going to targets when there's no line of sight between the owner and the target so fixing this issue would go a long way towards further improving PvP enjoyment.

**Comment by redmagejoe** [comment] 2023-02-24 15:07
If it was fixed in TBC then it sounds like it was realized as a bug or faulty behavior, and as such devs should strive to apply the same change to this.  Vanish should force the same cancel pet attack behavior as a CC does in a party.

**Comment by Zeyla-TW** [comment] 2023-02-27 05:38
This is indeed working as intended according to vanilla stealth vs TBC stealth. The way spells work is that they can only have up to 3 "spell effects" on a single spell at a time. Currently, stealth already utilizes the effects: "Shapeshift", "Mod Stealth", and "Decreased Speed" so when Blizzard wanted to add the instantaneous "Sanctuary" effect utilized by spells like vanish and divine intervention that breaks NPC targeting, they had to instead attach that effect as a background script that triggers it when stealth is activated instead (which is potentially possible for vanilla servers to implement, but just a bit more annoying to set up). Some clever spell editing could achieve the same result, but it would be a bit sloppy.

**Comment by Sringaram** [comment] 2023-02-27 16:43
Any kind of solution to this would be welcome and I'm sure there are already some options available from the vmangos community.

**Comment by Phobos-Programmer** [comment] 2023-03-05 21:33
first of all, lets split 
- bug when pet breaks rogue stealth after vanish 
and
- suggestion to prevent rogue/cat/elf stealth breaking after usual re-stealth, which was not a bug on original vanilla and required to force rogue use "distract" on pet to cancel such pet's follow run.

**Comment by iljakorolev** [comment] 2023-03-06 16:16
> * suggestion to prevent rogue/dru-cat/elf stealth breaking after usual re-stealth, which was not a bug in original vanilla and required to force rogue use "distract" on pet to cancel such pet's pursuit. This was fixed in TBC

To be even more specific, stealth breaks whenever you are targeted by pet. Example:
- lock targets you from far away and puts succubus on you
- you stealth after that at reasonable distance
- invisible succubus still at you and breaks you from stealth

**Closed** 2023-05-03 17:25 UTC

**Comment by Sringaram** [comment] 2023-05-03 18:30
So is this getting changed or?

**Comment by Sringaram** [comment] 2023-05-04 13:21
Very nice!
