### ISSUE TITLE
Zandalarian Hero Charm - Chain heal still consumes multiple charges per cast

### ISSUE THREAD

**Issue by gologotzmann** [slowtorta/turtlewow-bug-tracker#5279] opened 2023-11-19 11:04 UTC
**Please, provide a clear description what the bug is:**
Zandalarian Hero Charm  still consumes multiple charges per Chain Heal cast.
This was supposed to be fixed in the latest update, but seems to be not working.
**Steps to reproduce the behavior with as much detail as possible:**

1. Be in a group with 2 or more party members. 
2. Get 2 or more people injured.
3. Stand grouped up so that Chain Heal can bounce. Activate Zandalarian Hero Charm and cast Chain Heal.
4. Observe that it consumes more than 1 charge per cast.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19950

Spell: https://database.turtle-wow.org/?spell=10625

**Expected behavior. Describe how it should work:**
It should only consume 1 charge per chain heal cast, as mentioned in the item description: "Every time you cast a spell..."
And it was meant to be fixed with the latest update ;  Eye of the Dead  trinket works correctly.

**Comment by twowTurtReynolds** [comment] 2023-11-19 13:37
dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5279

**Closed by twowTurtReynolds** 2023-11-19 13:37 UTC
