### ISSUE TITLE
STV: Skullsplitter troll patrols

### ISSUE THREAD

**Issue by Gasan918** [slowtorta/turtlewow-bug-tracker#6221] opened 2024-02-10 09:20 UTC
**Please, provide a clear description what the bug is:**

No patrols in Skullsplitter location. Troll packs are just standing on their place. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/96973359/4983300b-8299-45a3-a16c-76a6116c99c2)

If i remember right, there must be 2 (or maybe even 3) patrols, patrolling the trails that connect troll camps.

**Comment by twowTurtReynolds** [comment] 2024-02-10 09:38
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3178

**Closed by twowTurtReynolds** 2024-02-10 09:38 UTC
