### ISSUE TITLE
Booty Bay Bruisers Rep Kills Stops After Revered. Cannot get Exalted.

### ISSUE THREAD

**Issue by GrizB37** [slowtorta/turtlewow-bug-tracker#4339] opened 2023-09-17 00:44 UTC
**Please, provide a clear description what the bug is:**
Once you reach Revered with Bloodsail Bucaneers , the Booty Bay Bruisers stop giving Rep, this makes it impossible to hit exalted with them and obtain the new Requires - Exalted rewards from the Bloodsail Quarter Master.

The only other mob in the game that gives rep is a vendor called Jazzrik in the Badlands, but only 5 rep on a 5 min respawn, but you cannot kill this NPC for long as the GM's either tell you to stop or teleport you away, making this rep grind impossible to finish.

**Steps to reproduce the behavior with as much detail as possible:**
1. Gain Revered with Bloodsail Bucaneers, Kill a Booty Bay Bruiser, No more rep gain.
2. Try kill Jazzrik and got teleported away by GM's for killing a vendor repeatedly
3. Impossible to hit exalted

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4624 - Booty Bay Bruiser - (Rep gain stops at revered)
NPC: https://database.turtle-wow.org/?npc=9179 - Jazzrik (Only mob that grants rep after revered NPC Vendor in Badlands)
Item: https://database.turtle-wow.org/?item=83491 - (Impossible to get with GM's Intervention)

**Expected behavior. Describe how it should work:**
Well I'd expect to be able to get exalted and finish my rep grind with the Bloodsail Bucaneers, but this is not possible when the only NPC is a vendor in the Badlands on a 5 min respawn timer and the GM's teleport you away when you kill it more than 3-4 times. - Making this rep impossible to max to Exalted and get the custom items the TWoW Devs have added.

I would really like to see this fixed please, I really want to hit exalted with Bloodsail Bucaneers so I can then grind my Steamwheedle rep back up to exalted also :) Thanks for your time :D

**Comment by Muigin** [comment] 2023-10-20 10:00
Duplicate of #4326

**Comment by Muigin** [comment] 2023-10-20 10:01
Duplicate of #4326

**Closed by Muigin** 2023-10-20 10:01 UTC
