### ISSUE TITLE
Missing River Water, Hillsbrad Foothills, Southshore

### ISSUE THREAD

**Issue by Kluttertoy** [slowtorta/turtlewow-bug-tracker#5579] opened 2023-12-13 05:03 UTC
**Please, provide a clear description what the bug is:**
Water chunk invisible, missing collision, can walk in depth. Breath bar still appears but noticeably higher than the water should be.

**Steps to reproduce the behavior with as much detail as possible:**

1. Consistent bug, location Hillsbrad Foothills, Southshore between Snapjaws and nagas

**Expected behavior. Describe how it should work:**
Swimming should occur, water should be visible. 
![image1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115521886/0d12f97a-0acc-4548-9bad-6e2dc33da46d)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/115521886/c1a312ec-48db-4a22-8c30-d4dcbd24a7be)

**Comment by twowTurtReynolds** [comment] 2024-02-08 10:18
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4657

**Closed by twowTurtReynolds** 2024-02-08 10:18 UTC
Labels: Reproduced, Map Dev
