### ISSUE TITLE
Quest [Mea Culpa, Lord Valthalak]

### ISSUE THREAD

**Issue by Bloomer94** [slowtorta/turtlewow-bug-tracker#5924] opened 2024-01-07 12:04 UTC
Quest [Mea Culpa, Lord Valthalak] (https://database.turtle-wow.org/?quest=8995)
1. in the instance UBRS when i use [Brazier of Beckoning] (https://database.turtle-wow.org/?item=22056) in the middle of room after killig boss the Beast - nothing happen

when use Brazier of Beckoning in the middle of the room writine "reque the Beast`s Chamber" 
and in anothers place of room "Invalid target"

Expected behavior:

after use [Brazier of Beckoning] (https://database.turtle-wow.org/?item=22056) must be summoned boss Lord Valthalak (https://database.turtle-wow.org/?npc=16042)

**Comment by twowTurtReynolds** [comment] 2024-01-07 12:40
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5892

Please use search before reporting bugs.

**Closed by twowTurtReynolds** 2024-01-07 12:40 UTC
