### ISSUE TITLE
Darkmoon Faire cycle is busted

### ISSUE THREAD

**Issue by Ennea** [slowtorta/turtlewow-bug-tracker#5219] opened 2023-11-15 12:20 UTC
**Please, provide a clear description what the bug is:**

The Darkmoon Faire cycle is broken. The faire is "under construction" every Wednesday, but it is in each location from Sunday until Saturday. This makes no sense; why would the faire be under construction when they've already been set up fully for three days prior?

As it is, the faire schedule for each location is as follows:
Sunday, Monday and Tuesday: the faire is there
Wednesday: the faire is "setting up"
Thursday, Friday, Saturday: the faire is there
Saturday -> Sunday: the faire moves to the next location

**Expected behavior. Describe how it should work:**

Rather than the above, it should work like this:
Wednesday: the faire is setting up
Thursday to Tuesday: the faire is there
Tuesday -> Wednesday: the faire moves to the next location

**Comment by Zebouski** [comment] 2023-11-15 13:57
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3381

**Closed** 2023-11-17 15:09 UTC
