### ISSUE TITLE
There is a bug in the Mage's T0.5 Wizard Leggings

### ISSUE THREAD

**Issue by whatoutlima** [slowtorta/turtlewow-bug-tracker#5275] opened 2023-11-19 03:52 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The 23 spell damage on the T.05 leggings is supposed to be active as an equip, but it currently shows that it is active and cannot be used
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-19 03:58
Dupe of your own post https://github.com/slowtorta/turtlewow-bug-tracker/issues/5274

Please do not create more than one post. And please search for the existing issue.

**Closed by twowTurtReynolds** 2023-11-19 03:58 UTC
