### ISSUE TITLE
Shaman loot drops in MC in the PvP server, and vice versa pressumably

### ISSUE THREAD

**Issue by Oledien43** [slowtorta/turtlewow-bug-tracker#5237] opened 2023-11-16 15:44 UTC
Our guilds first MC run happened on Tuesday, and we had a couple of shaman loot pieces drop, I made a ticket and was told to submit the bug here.

The server is not xfaction, therefore there should not be shaman T1/T2 pieces in alliance raids, and vice versa, Paladin T1/T2 in Horde raids

https://prnt.sc/Jy91TT256tfQ

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/28779603/78aba3fa-a938-46a8-bc9a-97d7626dd682)

**Comment by Zebouski** [comment] 2023-11-16 20:37
duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5209 but thanks for confirming the issue extends to not just dungeons but also raids

**Closed** 2023-11-17 14:20 UTC
