### ISSUE TITLE
Cant summon Lord Valthalak in UBRS

### ISSUE THREAD

**Issue by n0rayn** [slowtorta/turtlewow-bug-tracker#5909] opened 2024-01-05 21:01 UTC
Rakisha and I do the Quest "Mea Culpa, Lord Valthalak".
We have the Brazier of Beckoning and Lord Valthalak's Amulet in the Inventory.
In UBRS after slaing the Beast we try to summon Lord Valthalak.
Wenn wir klick on the Brazier of Beckoning we get either the Message "Invalid Target" or the Message "Requires the Beast's chamber".
I contact a gm and i get a new Brazier of Beckoning and i have to try it again, with the same results, unfortunately.
So we recommended to write an bug report.

**Steps to reproduce the behavior with as much detail as possible:**

1.  Slai the Beast in UBRS
2.  Try to Summon Lord  Valthalak with the Brazier of Beckoning and Lord Valthalaks Amulet.
3.  Get the Messages "Invalid Target" or "Requires the Beast's Chamber.
4.  Played UBRS till the end, came back and try to Summon Lord Valthalak again (with the same result).
5.  Contakt the GM
6.  Get a new Brazier of Beckoning and try to Summon Lord Valthalak again (with same results)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2024-01-05 21:53
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5892

Please use search before reporting.

**Closed by twowTurtReynolds** 2024-01-05 21:53 UTC
