### ISSUE TITLE
Dustwind cave no have NPC paths

### ISSUE THREAD

**Issue by hokagegaara** [slowtorta/turtlewow-bug-tracker#4423] opened 2023-09-30 11:57 UTC
Dustwind cave no have NPC paths
NPC paths/ways are not generated in this cave.

Pet & Enemy not work in this WMO cave.
1) The hunter's pet often falls under the textures.
2) Some abilities simply don’t work or enemy evade
Knowing such places, using charge in them has a chance of falling under the textures.
3) Enemy's and pets cannot chase the target or attack. 

https://cdn.discordapp.com/attachments/484376201272754176/1157644209076060220/image.png
https://cdn.discordapp.com/attachments/484376201272754176/1157644242190082048/image.png
Evade enemy and can attack/walk me, me pet under texture and not attack enemy.
https://media.discordapp.net/attachments/484376201272754176/1157645993911787570/image.png

**Comment by Muigin** [comment] 2023-10-20 09:50
Duplicate of #3659

**Closed by Muigin** 2023-10-20 09:50 UTC
