### ISSUE TITLE
No loot from skinning

### ISSUE THREAD

**Issue by Tofu0117** [slowtorta/turtlewow-bug-tracker#5272] opened 2023-11-18 17:28 UTC
**Please, provide a clear description what the bug is:**

When you skin mobs, it happen sometimes to not receive leather. You can't skin mob anymore after and corps is still there. i think it's happen more frequently when it's someone else who kill the mob. It Happen with all mobs level and all kind of leather.

**Steps to reproduce the behavior with as much detail as possible:**

1.Kill mobs
2. Skin them
3. loot leather or not

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Kill mobs, skin them if you have the skill and loot leather

**Comment by twowTurtReynolds** [comment] 2023-11-19 20:34
Actually, it looks like this is a duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3061 which actually has proper rep steps.

**Closed by twowTurtReynolds** 2023-11-19 20:34 UTC
Labels: Profession, Needs Replication, Need Help from the Community :)
