### ISSUE TITLE
Soul Link Doesn't Work on Enslaved Demon

### ISSUE THREAD

**Issue by NoelHG** [slowtorta/turtlewow-bug-tracker#4421] opened 2023-09-30 10:26 UTC
**Please, provide a clear description what the bug is:**

I do not see any buff on either demon or warlock when using soul link on enslaved demons. The animation and everything works but no buff is shown.  I have not yet tried other enslaved demons, but I suspect the same will happen at least with felguard/doomguard.

**Steps to reproduce the behavior with as much detail as possible:**

1. I summoned an infernal and tried to use Soul Link.

**Expected behavior. Describe how it should work:**

I should see a buff on both caster and demon I imagine.

**Comment by Muigin** [comment] 2023-10-20 07:23
Duplicate of #2497

**Closed by Muigin** 2023-10-20 07:23 UTC
