### ISSUE TITLE
The Untamed Blade possibly not on the loot table

### ISSUE THREAD

**Issue by jonsouls** [slowtorta/turtlewow-bug-tracker#5129] opened 2023-11-08 13:59 UTC
**Please, provide a clear description what the bug is:** By it's nature, I can't confirm this and more of an extreme suspicion I have (hearsay, if you will). After raiding BWL for 5 months, we have seen every item drop EXCEPT The Untamed Blade, which, statistically speaking, is extremely, beyond extremely unlikely to happen. He drops 3 items on death - a T2 Bracer, one of two trinkets and one of four remaining items, including UTB. However, not only have we not gotten a single drop in 5 months without missing a single ID, others that I have talked to outside my guild have said similar things.

**Steps to reproduce the behavior with as much detail as possible:**

1. Kill Razorgore the Untamed in BWL. If you have an internal PTR, you can respawn and kill him as many times as you wish.
2. Loot the body and notice the constant lack of UTB (it's always Mantle of the Blackwing Cabal or Gloves of Rapid Evolution that drop. On that note, we haven't seen Spineshatter either).
3. Get frustrated.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=12435
Item: https://database.turtle-wow.org/?item=19334

**Expected behavior. Describe how it should work:** The weapon should drop. :(

**Comment by Zmitrok1984** [comment] 2023-11-08 16:04
Simple inspecting people in SW during a few min
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/e89beeda-1ef4-4ecd-a53e-84eab9320d84)
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/99164611/3ebff9f1-c60b-45f4-b6fd-e605249eb062)

**Comment by Zebouski** [comment] 2023-11-08 20:57
Not a bug. This is how RNG works.

**Comment by twowTurtReynolds** [comment] 2023-11-17 15:23
https://www.omnicalculator.com/statistics/probability

Here we have a 90% chance for UTB to not drop. With 20 weeks of attempts, the chance for a guild to not see the drop even once is 12%. About 1 in 8 guilds will experience from a specific point in time for a specific piece of loot. This unfortunately means seeing these dry spells is very common.

As https://database.turtle-wow.org/?npc=12435 shows he has UTB on the loot table at this moment, closing as not a bug.

**Closed by twowTurtReynolds** 2023-11-17 15:23 UTC
