### ISSUE TITLE
Band of Thorns Not Proccing

### ISSUE THREAD

**Issue by Helmholtz232** [slowtorta/turtlewow-bug-tracker#6310] opened 2024-02-20 06:31 UTC
**Please, provide a clear description what the bug is:**

Band of Thorns does not seem to be proccing its arcane thorns ability.

**Steps to reproduce the behavior with as much detail as possible:**

1.Equipped Band of Thorns in Ring slot 1, 2 and both.
2. Fought an enemy with each configuration and the arcane thorns damage did not proc when I was hit.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5007

**Expected behavior. Describe how it should work:**

I would expect that every time my character is struck, the enemy would be hit for 1 arcane damage per equipped ring.

**Comment by twowTurtReynolds** [comment] 2024-02-20 06:47
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4271

**Closed by twowTurtReynolds** 2024-02-20 06:47 UTC

**Comment by Helmholtz232** [comment] 2024-02-20 23:47
Can I submit a video proof? I read through #4271 and see that they
mentioned that the effect only happens in defensive stance. I am also
seeing that effect. Swapping to battle stance allows the thorns to apply as
i expected.
