### ISSUE TITLE
HE Skinning trainer

### ISSUE THREAD

**Issue by LordSpank** [slowtorta/turtlewow-bug-tracker#5722] opened 2023-12-22 23:19 UTC
**Please, provide a clear description what the bug is:**

buying Skinning training from the NPC does not give you the skill. You can buy it over and over and it does not show up in your skillbook and the trianer still offers it to you.

**Steps to reproduce the behavior with as much detail as possible:**

1. clcik on trainer and select journeyman skinning
2. click ACCEPT button when it pops up
3. check skillbook and see it is not there
4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc= faction id = 371
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

training should 'stick'

**Comment by twowTurtReynolds** [comment] 2023-12-25 01:19
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5739

**Closed by twowTurtReynolds** 2023-12-25 01:19 UTC
