### ISSUE TITLE
“Talisman of ascendance”,this item may have bug

### ISSUE THREAD

**Issue by tiancaisnake** [slowtorta/turtlewow-bug-tracker#5441] opened 2023-11-30 02:57 UTC
**Talisman of ascendance,this item may have bug:**

this time i add the item and spell url on  https://database.turtle-wow.org

**Steps to reproduce the behavior with as much detail as possible:**

**Talisman of ascendance,this item may have bug,when i use "Talisman of ascendance",i can get buff named "ascendance",
If i cast spell "holy light" it consume one layer at a time,but if i cast spell "Flash of light" it weill consume two layer.
Under normal circumstances when i use "Talisman of ascendance" ,i can cast 6 damage or healing spells ,but now, i use "Talisman of ascendance", i can only cast 3 "Flash of light" not 6

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=22678
Spell: https://database.turtle-wow.org/?spell=19948

**Comment by twowTurtReynolds** [comment] 2023-12-04 18:23
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5309

Please do not create duplicate tickets.

**Closed by twowTurtReynolds** 2023-12-04 18:23 UTC
