### ISSUE TITLE
Water Shield and Totem of the Calming River generate threat at max mana

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#6228] opened 2024-02-11 03:48 UTC
Totem of the Calming River's equip effect is listed as "Your Water Shield ability grants an additional 6 mana per 5 sec. while active." Instead of giving the player 6 MP5 like other "mana per 5 sec." effects, it instead generates the mana every 5 seconds - even if the Shaman is at 100% mana. This mana generation generates threat, unlike other sources of "mana per 5 sec."

**Steps to reproduce:**

1. Equip Totem of the Calming River
2. Cast Water Shield
3. Drink to max mana then stand up
4. Have another player in your raid group pull a mob that has raid-wide aggro (such as Gurubashi Berserker in Zul'Gurub) by walking into its detection range
5. Both players do nothing else
6. Mob should change target to the Shaman after the Totem of the Calming River effect triggers

**Affected Items:**

Item: https://database.turtle-wow.org/?item=61698

**Expected behavior:**
"Mana per 5 sec." effects should not generate mana when mana is full, and should not generate threat if mana is full or not.

**Comment by Muigin** [comment] 2024-02-11 04:27
Mana energize effects, except for Blessing of Wisdom explicitly, do in fact generate 0.5 threat per mana restored, but should not generate any threat for mana that is not actually restored.  Please use TWThreat to test if you do, in fact, generate threat at full mana and with no other actions taken.

If you do not generate threat while at full mana, this is working as intended.  If you have evidence of it behaving otherwise, please share it here and we will look into it.

**Comment by imcdermott13** [comment] 2024-02-11 07:15
The buff is generating 4 Threat every 5 seconds while at full mana. Tested using TWThreat with the steps in the description.

**Comment by twowTurtReynolds** [comment] 2024-02-11 15:25
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ed392c52-c90a-421a-a7d8-8db6ebfa1b4c)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d1913067-a425-4728-b1b6-b037889f00d5)
4 threat is generated from: 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/413f54c4-d5b3-4369-ab6b-3843551d21cc)

228 threat is gained from this effect + 3 water shield charges:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/f7d1c22f-a1b3-449c-963b-786b50264089)

All at max mana.

**Comment by ratkosrb** [comment] 2024-02-20 23:19
This should be fixed in the next update.

**Closed** 2024-02-21 02:10 UTC
Labels: Shaman, Spell, Reproduced
