### ISSUE TITLE
NPC bug

### ISSUE THREAD

**Issue by UlukayOutkastov** [slowtorta/turtlewow-bug-tracker#5940] opened 2024-01-08 21:41 UTC
There is a problem with the Grand Magister Rommath NPC in Alah'Thalas. It's not clickable. There is no way to complete the quest.
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/95168076/3e80d8c9-973e-48a0-9456-73e75d07953e)

**Comment by IoSapsai** [comment] 2024-01-08 21:44
Can confirm. Same happened to me. Deleted WDB folder and tried again - nothing. Filed a second ticket. The GM tried resetting thr NPC but that didn't fix him either.

**Comment by twowTurtReynolds** [comment] 2024-01-08 21:50
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5831

**Closed by twowTurtReynolds** 2024-01-08 21:50 UTC
