### ISSUE TITLE
Herbs/Mobs visible or invisible within 3 steps.

### ISSUE THREAD

**Issue by DaddyM0E** [slowtorta/turtlewow-bug-tracker#5546] opened 2023-12-09 19:19 UTC
**Please, provide a clear description what the bug is:**
Account: DaddyM0E
Toon: Saghorn ( Or any toon with herbalism actively looking for nodes.)
Originally thought to be a bug from "Shagu" addons, [Per GM advice. :-) ] I've not only reinstalled from scratch with my Nvidia card, but have purchased a AMD video card with better specs. I once again deleted and reinstalled the game. 
Ver:  1.17.0 (7070) (Release)  Oct. 03 2023 **NO ADDONS!!!** 
What is happening:  My toons from either of my accounts (DaddyM0E2 being the other) *with* herbalism see the nodes on the map just fine everywhere else. But, this spot, this "transition line" of some sort, I can see the herbs on the mini-map AND on my video. However, just two steps closer and the nodes 'fade-OUT' both on-screen and the mini-map and THEN the mobs right next to them 'fade-IN'...

**Steps to reproduce the behavior with as much detail as possible:**

1.  I've parked my DaddyM0E/Saghorn toon at the place of concern and will not move them until this is fixed/verified
2. Please let me know where I can send donations to afford the Aspirin/Ibuprofen for the headaches that this will undoubtedly cause. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-09 19:30
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312

**Closed by twowTurtReynolds** 2023-12-09 19:30 UTC
