### ISSUE TITLE
Deserter debuff when the game crash in a battleground.

### ISSUE THREAD

**Issue by marcus0060** [slowtorta/turtlewow-bug-tracker#5729] opened 2023-12-23 12:05 UTC
**Please, provide a clear description what the bug is:** Sometimes the game client can crash, if this happens inside a battleground you get removed from the BG and applied deserter debuff IMMEDIATELY. This is very annoying when you try to farm honor..

**Steps to reproduce the behavior with as much detail as possible:**

1. Play battlegrounds
2. Client randomly crash
3. Character is removed from the BG and given deserter debuff

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** You should not be removed from a battleground and given deserter debuff upon client crash or disconnection.

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:36
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4266

**Closed by twowTurtReynolds** 2023-12-25 00:36 UTC
