### ISSUE TITLE
BloodRing Title

### ISSUE THREAD

**Issue by Egirlwithrpg** [slowtorta/turtlewow-bug-tracker#5684] opened 2023-12-20 23:22 UTC
Hello, on the website (https://turtle-wow.org/#/achievement-titles)
it says that an exalted blood ring title is available.

I've been at exalted for a long time, but I saw this evening that it was available on the site, in game no one knows how to get it (talk to an npc?)

I DELETED the WTB folder and still nothing.
According to someone on discord it should work... so he told me to file a bug report.

Here are some screenshots

https://image.noelshack.com/fichiers/2023/51/4/1703114345-wow1.jpg
im exalted (but yes im a nerd)

https://image.noelshack.com/fichiers/2023/51/4/1703114401-wow2.jpg
(0 title after a clear wtb/delete wtb folder)

Thank you for your server and above all, thank you for finally starting to pay attention to PVP players with your new updates! Good luck and happy holidays to the turtlewow team

**Comment by twowTurtReynolds** [comment] 2023-12-21 01:57
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5003

**Closed by twowTurtReynolds** 2023-12-21 01:57 UTC
