### ISSUE TITLE
Ravenholdt reputation 

### ISSUE THREAD

**Issue by Rzod** [slowtorta/turtlewow-bug-tracker#5011] opened 2023-11-01 17:38 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.after friendliness, reputation with the faction does not come from killing mobs
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-19 19:17
[https://wowwiki-archive.fandom.com/wiki/Ravenholdt?oldid=333026](The 2006 copy of the wow wiki) says these mobs actually shouldn't grant rep at all.

Please open a suggestion on the suggestion forums if you think this should be changed further. Closing as not a bug

**Closed by twowTurtReynolds** 2023-11-19 19:17 UTC
