### ISSUE TITLE
Breath meter on land

### ISSUE THREAD

**Issue by cyaohiri** [slowtorta/turtlewow-bug-tracker#5798] opened 2023-12-28 09:26 UTC
Breath meter appears on land in Feralas, at around `.go xy -4625 100 1`.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/86041826/c52bf4da-454d-4b04-8f9d-3382bdbbad4d)

**Comment by twowTurtReynolds** [comment] 2023-12-28 19:56
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4568

**Closed by twowTurtReynolds** 2023-12-28 19:56 UTC
