### ISSUE TITLE
Blackstone Island quest progression

### ISSUE THREAD

**Issue by itorch1** [slowtorta/turtlewow-bug-tracker#5957] opened 2024-01-09 23:32 UTC
**Please, provide a clear description what the bug is:**

Later parts of quest chains are available from the start

**Steps to reproduce the behavior with as much detail as possible:**

1. Simply make a goblin character of any class/gender
2. You will see that you are able to pick up later parts of quest chains right away, evidenced by quest text, and reasoning (such as breadcrumb quest to an NPC which you picked a quest up from, but doesn't have any more)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: Too many to list, but the affected quests are all in the initial area, very possibly some in the first town, possibly entire zone?

**Expected behavior. Describe how it should work:**
self explanatory ^^

**Comment by itorch1** [comment] 2024-01-09 23:35
Sorry for duplicate, was not able to see my previous post in the list

**Comment by twowTurtReynolds** [comment] 2024-01-09 23:36
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5955

**Closed by twowTurtReynolds** 2024-01-09 23:36 UTC
