### ISSUE TITLE
Frosbolt gives the "slow" effect, even when resisted

### ISSUE THREAD

**Issue by Pierrolo** [slowtorta/turtlewow-bug-tracker#3464] opened 2023-05-15 10:00 UTC
**Please, provide a clear description what the bug is:**
I have been farming SM Cath for money for a while now, never had an issue until recently. I noticed i got slowed by frosbolt between 7 and 10 times per run. Before,  i would get slowed by frosbolt about once every 10 runs, so quite a difference there. So I though maybe I didn't have enough frost resistance, so i bough frost res gear, now i have 84 frost resistance, and still i get slowed. When i put my ice barrier and my frost ward, i also get slowed (by the way, frost ward never reflect the forstbolt thrown at me, even with 2 talent point in "Frost Warding").

I noticed this behavior also with some mobs in silithius who cast frosbolt, even though i resist some of those, i still get slowed some times, which is new.

Finally, still in SM Cath, the Scarlet Sorcerer, cast a "slow" ability that lasts around 10 seconds, i've never seen them do that, let alone do it as 10-15-20 yard from me... But most of all, Twow database says it's a slow of 1% movement speed, when actually it's more 60%

**Steps to reproduce the behavior with as much detail as possible:**

1. go to SM Cath with a character with very high frost resistance gear
2. Pick a random Scarlet Sorcerer
3. Attack it once (don't kill it)
4. Stand away from it (like 15 yards)
5. Let it cast frosbotl at you
6. Notice how most frosbolt are resisted (due to your gear) but amond the resisted ones, you still get slowed for some reason...

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=4294
Spell: https://database.turtle-wow.org/?spell=9672
Spell: https://database.turtle-wow.org/?spell=6146

**Expected behavior. Describe how it should work:**
When I had just 29 frost res (including the Ice armor buff) i'd never get slowed by frosbotl (maybe once every 10 runs). If i'm not mistaken, when my shield absords a frosbolt i shouldn't get slowed (or at least that's how it worked before) and when i resist a frosbolt i shouldn't get slowed either  (or at least that's how it worked before) .

All I am describing here is very new, it did not happen until last week basically. SM Cath is my money maker and i really enjoy farming it alone, it's quite fun to do, so now, i'm basically broke :)

Thanks in advance for any help or answers :)

**Comment by Pierrolo** [comment] 2023-05-15 11:03
Ho damn !!! So that's on purpose and it's not a bug ? man that's gonna screw quite a few farming places...

**Comment by Pierrolo** [comment] 2023-05-15 16:17
but still that doesn't explain why a resist frostbotl applies the slow effect...

**Comment by balakethelock** [comment] 2023-05-15 16:24
The change was initially made for pvp, it also affected pve, they fixed it to not affect pve but the fix won't be live until wednesday patch.
In other words, this is duplicate of #3428 and can be closed

**Closed** 2023-12-09 04:14 UTC
