### ISSUE TITLE
Guardians of the Altar

### ISSUE THREAD

**Issue by Isarke** [slowtorta/turtlewow-bug-tracker#227] opened 2021-08-04 16:43 UTC
quest name in the title
Cant click on the altar at the end to progress further
https://database.turtle-wow.org/?quest=4901

**Comment by UsernameChad42069IsNotAvailable** [comment] 2021-09-25 18:38
Yep can confirm its bugged

**Comment by hazlema** [comment] 2021-12-23 18:53
Ya, not working

**Comment by slowtorta** [comment] 2022-01-27 02:40
This will be fixed on the next server update, thank you!

**Comment by Tinyfin-github** [comment] 2022-01-31 07:25
Reports of quest still being broken: Unable to interact with the Altar.

![image](https://user-images.githubusercontent.com/83077166/151753903-cf3f5dca-b833-46e6-a086-fddf493e98a7.png)

**Comment by slowtorta** [comment] 2022-02-10 19:43
I cannot reproduce it, it's working for me. Need repro case.

**Comment by slowtorta** [comment] 2022-02-13 23:56
https://github.com/slowtorta/turtlewow-bug-tracker/issues/500

**Comment by geojak** [comment] 2022-03-19 14:00
hello, just wanted to report, still like in the screesht from tinyfin above

**Comment by SabineWren** [comment] 2022-05-04 05:32
Quest works now.
![guardians_of_the_altar_fixed](https://user-images.githubusercontent.com/18298014/166627416-285afb45-4508-49bb-a160-f516c017f3b8.jpg)

**Comment by SabineWren** [comment] 2022-05-07 03:51
Looks like an intermittent bug https://github.com/vmangos/core/issues/756
This whole quest felt pretty jank.

**Closed** 2022-07-16 16:31 UTC
Labels: Quest Scripting
