### ISSUE TITLE
Warlock cannot pickup felhunter quest

### ISSUE THREAD

**Issue by swizzie123** [slowtorta/turtlewow-bug-tracker#4721] opened 2023-10-13 02:17 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by swizzie123** [comment] 2023-10-13 02:17
My warlock cannot, but I see every other warlock with one

**Comment by swizzie123** [comment] 2023-10-13 02:17
Legitthreat

**Comment by luskanek** [comment] 2023-10-13 09:13
Your issue has been resolved by a GM. The questline is working as intended.

**Closed by luskanek** 2023-10-13 09:13 UTC
