### ISSUE TITLE
Draconic for Dummies Wrong Books in Bookpile

### ISSUE THREAD

**Issue by Backtoroots1** [slowtorta/turtlewow-bug-tracker#4448] opened 2023-10-02 12:16 UTC
**Please, provide a clear description what the bug is:**
Hello im Mr. b2r i want to report a bug with Draconic for Dummies since months i tryted to finish it i just missed nr. 7  (VII) what should be normaly  in BWL (Book Pile)  but without Waldt the Friendly Gm i would never had it done now cause the Bookpile is Wrong (Listed done below)
**Steps to reproduce the behavior with as much detail as possible:**

1.  Szepter Quest (Draconic for dummies)
2.  Look the Book in Stormwind Libary (V) https://database.turtle-wow.org/?item=21107
3.  Then you cant Look BWL (VII)https://database.turtle-wow.org/?item=21109  Cause in the Bookpile is (V) also the Stormwind one.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=21107  & 21109
Quest: https://database.turtle-wow.org/?quest=8620
Spell: https://database.turtle-wow.org/?spell=25719
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-06 20:11
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4273

**Closed by twowTurtReynolds** 2023-12-06 20:11 UTC
