### ISSUE TITLE
Invocation of Shattering - cannot apply

### ISSUE THREAD

**Issue by LoooLQoP** [slowtorta/turtlewow-bug-tracker#5541] opened 2023-12-09 10:12 UTC
**Please, provide a clear description what the bug is:**
Hello! I bought today a couple of leg/head enchants from kara for my rogue t0.5, but when I tried using them, I got the message "That item is not a valid target." Got the message regardless of trying to apply to enchant while the item was equipped, or whenever the item was on my bags.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get Darkmantle Pants and/or Cap.
2. Do Contribution to the Church pre-quest.
3. Get the mats for Invocation of Shattering.
4. Apply enchant into Pants/Cap.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61610
Item: https://database.turtle-wow.org/?item=92005
Quest: https://database.turtle-wow.org/?quest=41079
Item to enchant: https://database.turtle-wow.org/?item=22005
Item to enchant: https://database.turtle-wow.org/?item=22007

**Expected behavior. Describe how it should work:**

I should be able to enchant both legs and head, but it is currently not possible. This is happening on Tel'Abim server (PVP one).

**Comment by cyaohiri** [comment] 2023-12-09 10:16
Duplicate of #4788.

**Comment by LoooLQoP** [comment] 2023-12-09 10:43
I did search for the raw name, my bad.

**Comment by twowTurtReynolds** [comment] 2023-12-09 12:11
@LoooLQoP No need to search, just please be aware. :) 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/0b8c6d2d-1195-445c-be9a-2b6bd1b13ca0)

**Closed by twowTurtReynolds** 2023-12-09 12:11 UTC
