### ISSUE TITLE
Field of duty Horde quest is bugged

### ISSUE THREAD

**Issue by pongatheshaman** [slowtorta/turtlewow-bug-tracker#4010] opened 2023-07-22 13:53 UTC
Field of duty Horde quest is bugged and makes it way harder than it use to be. Noone of the npcs attack the elite mob, only Krug (the quest giver) who has 22k hp and the elite mob has almost 400k, this use to be an easy quest you could do alone and get some cenarion reputation but here in the horde, due to the npcs bug the elite kills krug really quick and dissapears And if you heal krug you aggro the elite and you gotta tank a 400k hp elite. Its impossible unless you get a raid team to help you...

**Comment by Niqlo** [comment] 2023-10-19 22:02
Yes, this is also happening to me

Alliance doesn't even have a bug that spawns

**Comment by twowTurtReynolds** [comment] 2023-12-07 04:21
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2405

**Closed by twowTurtReynolds** 2023-12-07 04:21 UTC
