### ISSUE TITLE
Cannot finish quests

### ISSUE THREAD

**Issue by mumusam** [slowtorta/turtlewow-bug-tracker#5316] opened 2023-11-21 13:02 UTC
**Please, provide a clear description what the bug is:

The following quests:
1.https://database.turtle-wow.org/?quest=Gnomes Are Genuine Inventors
2.https://database.turtle-wow.org/?quest=Goblin Engineering At Its Finest
3.https://database.turtle-wow.org/?quest=Race against Time
I can't finish them.The 1st and 2nd quests ask me to find Dolores and start a race.But when I chat with her ,only a dialog with no buttons or choices.The 3rd quest is the same situation:when I chat with Daisy,just a dialog,no buttons, no choices. 
I have tried to delete WDB folders for many times.But it doesn't work at all.
How can I finish the quests? Please help me. Thanks a lot!
![Daisy](https://github.com/slowtorta/turtlewow-bug-tracker/assets/22175624/e35931d8-2665-4b17-ba39-21c1cfb6658e)
![Dolores](https://github.com/slowtorta/turtlewow-bug-tracker/assets/22175624/4e78bd1d-123f-49c9-b518-75298d0f661d)

**Comment by Muigin** [comment] 2023-11-21 13:12
Please edit your report and put the ACTUAL links to the quests on the database that we may more easily review this issue.  The template clearly indicates URLs, so make sure you are providing a valid URL.  Go to the database, look up the name of the quest you want, and get the quest ID, which will be a valid URL.

**Comment by twowTurtReynolds** [comment] 2023-11-21 14:33
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4813

**Closed by twowTurtReynolds** 2023-11-21 14:33 UTC
