### ISSUE TITLE
Possible issue with Darnassus regarding Love is in the Air event

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#6247] opened 2024-02-12 23:27 UTC
**Please, provide a clear description what the bug is:**
It appears that Darnassus NPCs are not getting the heart buff during the Love is in the Air event. The statistics shown by Kwee Q. Peddlefeet (for each faction's favorite leader) seem to indicate that the Alliance has turned in only 14 gift collections in total, whereas the Horde has turned in 101 (though for some reason the individual Horde leaders' points do not add up to 101, despite that being listed as the total for the faction).

Since some people have been able to complete it, I must assume that the hearts have been in place at some point, and that they may even come back after a server restart (or if the NPCs were to respawn, possibly?), but have not returned for one reason or another.

**Steps to reproduce the behavior with as much detail as possible:**

1. Complete the event tasks in Ironforge and Stormwind
2. Travel to Darnassus in order to complete the Alliance Gift Collection
3. Observe the distinct lack of heart buffs on NPCs aside from the patrolling treants near the Cenarion Enclave, but they can not be interacted with

**Expected behavior. Describe how it should work:**
The event should be doable. The hearts should reset on the NPCs after a short delay.

**Comment by ratkosrb** [comment] 2024-02-13 14:04
The issue is caused by High Elf players. When they talk to one of the npcs, they cause the npcs to enter combat for a second, removing all of its Love is in the Air related auras, and preventing further interaction with it. This has already been fixed internally. The servers need to be updated to the new revision.

**Closed by ratkosrb** 2024-02-13 14:04 UTC
