### ISSUE TITLE
Nature's Grace

### ISSUE THREAD

**Issue by Komarac334** [slowtorta/turtlewow-bug-tracker#4096] opened 2023-08-06 06:22 UTC
**Please, provide a clear description what the bug is:**
Nature's Grace global cooldown reduction is not working at all! Instant cast spell such as Moonfire or Insect Swarm don't even consume the buff, while wrath consumes and cast time is reduced but when you try to cast it again instantly it says that spell is not ready yet and then you cast 0.5 sec later wich should never be a thing therefore global cooldown reduction part of the spell is not working. 
**Steps to reproduce the behavior with as much detail as possible:**

1.Cast Spell until you get Nature's Grace buff
2. Consume the buff
3.Global Cooldown of the buff not working
4. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=16880
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Instant cast spells should consume the buff and have their global cooldown reduced, global cooldown should be reduce on every other cast spell also.

**Comment by twowTurtReynolds** [comment] 2023-12-07 00:19
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4118

**Closed by twowTurtReynolds** 2023-12-07 00:19 UTC
