### ISSUE TITLE
Druids entering stealth cannot automatically switch to active scrolling

### ISSUE THREAD

**Issue by nathan16888** [slowtorta/turtlewow-bug-tracker#6060] opened 2024-01-21 00:22 UTC
**Please, provide a clear description what the bug is:**
server name: endless sea 
profession: Druids
ID: 泰勒斯
Druids entering stealth cannot automatically switch to active scrolling

**Steps to reproduce the behavior with as much detail as possible:**
This issue did not occur before, it has occurred since the last server restart
I am trying to solve this problem:
1.New client downloaded from the official website
2. Not using any plugins
3. Game accelerator not enabled
4. computer system is Windows 11

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
<img width="1000" alt="1_副本" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/157255771/42d61235-f499-44d8-a7da-3471940cd39b">
<img width="1000" alt="2_副本" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/157255771/471acd18-8272-4902-b719-ab55bd23ad4a">

**Comment by twowTurtReynolds** [comment] 2024-01-21 00:23
I am not sure what you mean by Active Scrolling?

**Comment by nathan16888** [comment] 2024-01-21 00:28
> I am not sure what you mean by Active Scrolling?
Sorry, my English is not good, so I can only use translation software for conversations.
Druids, like Rogue, actively switch and make active notes after infiltrating.
But this character no longer has this feature, it was normal before.

**Comment by twowTurtReynolds** [comment] 2024-01-21 00:48
Oh, when you say "Active Scrolling" and "Actively Switch", you mean "Actionbar Paging"?

The Actionbar will only switch to the Cat bar when swapping into the form. When you use stealth/prowl, the game does not give you another actionbar like Rouge does.

There may be an addon that adds this feature. We will not help with it.

As this is not a bug, I will be closing this report.

**Closed by twowTurtReynolds** 2024-01-21 00:48 UTC
