### ISSUE TITLE
Beastmaster's Gloves don't give 1% hit chance bonus.

### ISSUE THREAD

**Issue by MenelauGC** [slowtorta/turtlewow-bug-tracker#5615] opened 2023-12-15 19:13 UTC
**Please, provide a clear description what the bug is:**The item have the bonus "Use : Improves your chance to hit by 1%" that don't give any bonus,you can't click to get bonus 1% hit chance which would wierd to be like that,no passive bonus of 1% hit chance

**Steps to reproduce the behavior with as much detail as possible:**
1.The item have the bonus "Use : Improves your chance to hit by 1%" that don't give any bonus,passive or active like the item says.
2. The item have the bonus "Use : Improves your chance to hit by 1%" that don't give any bonus,passive or active like the item says.
3. The item have the bonus "Use : Improves your chance to hit by 1%" that don't give any bonus,passive or active like the item says.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
On the website he don't have displayed this bonus but it is in game.
Item ID : 34650
NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**The item have the bonus "Use : Improves your chance to hit by 1%" and should be a passive bonus.

**Comment by cyaohiri** [comment] 2023-12-15 19:17
Duplicate of #5225.
Did you delete your WDB folder?

**Comment by MenelauGC** [comment] 2023-12-15 19:22
Yes i did like 10 times and still the same.

Sent from Yahoo Mail on Android 
 
  On Fri, 15 Dec 2023 at 19:17, ***@***.***> wrote:   


Duplicate of #5225.
Did you delete your WDB folder?

**Comment by twowTurtReynolds** [comment] 2023-12-15 19:33
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/d9f9ae50-9573-4f75-ae6a-8988968acaf6)
Confirming again that this bug has been long fixed.

Please work with support, and not here with the devs who have already fixed the problem.

**Closed by twowTurtReynolds** 2023-12-15 19:33 UTC

**Comment by MenelauGC** [comment] 2023-12-15 19:48
To me appear "on use" and don't give me that 1 % hit chance,because if would get the benefit of the bonus would be all ok.
    Pe vineri, 15 decembrie 2023 la 19:34:03 GMT, Turt Reynolds ***@***.***> a scris:  
 
 


image.png (view on web)
Confirming again that this bug has been long fixed.

Please work with support, and not here with the devs who have already fixed the problem.

**Comment by MenelauGC** [comment] 2023-12-15 19:54
Hi,sorry its all good now,thank you,i just deleted WDB with game closed empty the bin and log into game,fixed.
    Pe vineri, 15 decembrie 2023 la 19:48:10 GMT, aif ionut ***@***.***> a scris:  
 
  To me appear "on use" and don't give me that 1 % hit chance,because if would get the benefit of the bonus would be all ok.
    Pe vineri, 15 decembrie 2023 la 19:34:03 GMT, Turt Reynolds ***@***.***> a scris:  
 
 


image.png (view on web)
Confirming again that this bug has been long fixed.

Please work with support, and not here with the devs who have already fixed the problem.
