### ISSUE TITLE
Greatfather Winter not counting towards Life comes to the Legend quest

### ISSUE THREAD

**Issue by FaceDownDagon** [slowtorta/turtlewow-bug-tracker#5578] opened 2023-12-13 04:46 UTC
When talking to Greatfather Winter, which is supposed to be one of the objectives for this quest, yellow text will pop up as normal (1/1) but credit is not given in the quest log.

I am aware the Greatfather Winter for the quest is the one that looks like a white statue in the mountains near the Wetlands, and not the one in Ironforge, though I have talked to both after accepting the quest.

NPC: https://database.turtle-wow.org/?npc=61171
Quest: https://database.turtle-wow.org/?quest=40783
Trigger: https://database.turtle-wow.org/?npc=60025

**Comment by FaceDownDagon** [comment] 2023-12-13 04:56
Semi-edit: I am aware some of the database links are linking to garbage, but when you use the search function, those are the URLs you arrive at. Perhaps that is related to the issue.

**Comment by twowTurtReynolds** [comment] 2023-12-13 20:15
I fixed your incorrect database links, you are just meant to add the ID after the url given to you.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a6c14fd2-b227-46b3-941d-6c2d54bb92f8)
I replicated the issue, I didn't even see the yellow quest credit pop up.

**Comment by twowTurtReynolds** [comment] 2023-12-13 20:16
`.go creature id 60025` does not work, probably the problem, the trigger might be gone.

**Comment by twowTurtReynolds** [comment] 2023-12-15 20:19
Confirmed with the staff, he's no longer a trigger discover, but instead you need to talk to him. It looks like it's fixed now, and I was able to complete this chain without issue now. I am not sure if this hit live yet but if not, it will.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e855f856-91b4-48b4-a6e6-0b495044c78f)

**Closed by twowTurtReynolds** 2023-12-15 20:19 UTC
Labels: Quest, NPC, Seasonal, Reproduced
