### ISSUE TITLE
Hair Dye Vendors don't sell new custom hair colors.

### ISSUE THREAD

**Issue by ShiraZen** [slowtorta/turtlewow-bug-tracker#6320] opened 2024-02-21 15:36 UTC
**Please, provide a clear description what the bug is:**

Hair Dye Vendors don't sell new custom hair colors. Seems unintended?

**Comment by twowTurtReynolds** [comment] 2024-02-22 03:49
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6096

**Closed by twowTurtReynolds** 2024-02-22 03:49 UTC
