### ISSUE TITLE
bug when talking to timothy worthington the tailoring trainer, we cannot put the button train, it does nothing

### ISSUE THREAD

**Issue by phili456** [slowtorta/turtlewow-bug-tracker#4847] opened 2023-10-20 17:45 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. go talk to the trainer, click train, tjhe button can be press but nothing happen. 
2. only afftecting my caracter.  i cleared the DBM folder already, no difference
3. i'm warlock level 56  tailoring 252
4. 
5. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148571544/354fe634-45de-4b36-8df9-3388c13ed726)

**Comment by phili456** [comment] 2023-10-20 17:46
name ettya - gnome warlock 56

**Comment by Muigin** [comment] 2023-10-20 22:42
This is caused by an object being between you and Timothy.  Ensure that Line of Sight is not impeded.  We are working to resolve this LOS behavior across all profession spells.

Fix in progress, but spell should be trainable.

**Comment by twowTurtReynolds** [comment] 2023-12-04 23:33
Should be fixed for good now.

**Closed by twowTurtReynolds** 2023-12-04 23:33 UTC
