### ISSUE TITLE
Horde silithus field duty camp

### ISSUE THREAD

**Issue by Luzarus** [slowtorta/turtlewow-bug-tracker#5587] opened 2023-12-13 12:12 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.https://database.turtle-wow.org/?npc=15612 cant really tank the giant bug for the field duty quest
2. i am not sure if it is intended...but why is it that alliance can just go to their camp get their signed papers without killing the giant bug (cuz it doesnt spawn) but horde have to kill it everytime 
3. would be nice if u could do that atleast equal for both faction whether both have to kill the giant bug oder none of them

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-13 19:06
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/2405

**Closed by twowTurtReynolds** 2023-12-13 19:06 UTC
