### ISSUE TITLE
Quest: Aquementas, vanishing quest item from quest bag

### ISSUE THREAD

**Issue by Dalzedur** [slowtorta/turtlewow-bug-tracker#3963] opened 2023-07-17 11:28 UTC
**Please, provide a clear description what the bug is:**

As the quest is started, you are provided with an Eridan's supplies ( https://database.turtle-wow.org/?item=11617 ) quest item. A bag, which contains:
1 Book of Aquor ( https://database.turtle-wow.org/?item=11169 )
11 silver claws ( https://database.turtle-wow.org/?item=11172 )
1 irontree heart. ( https://database.turtle-wow.org/?item=11173 )

I did not loot the items inside, since the bag takes 1 inventory slot unlooted, but if looted, the items inside take 3. I wasn't in a hurry to complete the quest. In fact, I logged out, went to bed. The server experienced a day changing, clock went from 23:59 -> 00:00, presumably. This does things to some dailies at least, could be the cause of the bug here as well.

**Steps to reproduce the behavior with as much detail as possible:**

1. Start the quest, receive the Eridan's supplies bag
2.  Log off, time passes, don't loot the items from the bag
3.  Poof! Irontree heart inside the bag goes missing. The bag doesn't vanish when fully looted by shift clicking it, implying that it is not empty. Yet, it shows as empty - cannot get the irontree heart from it, even through shift clicking the bag.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=4005

Eridan's supplies ( https://database.turtle-wow.org/?item=11617 ) <-- relevant
Book of Aquor ( https://database.turtle-wow.org/?item=11169 )
Silver claw ( https://database.turtle-wow.org/?item=11172 )
Irontree heart. ( https://database.turtle-wow.org/?item=11173 ) <-- relevant

**Expected behavior. Describe how it should work:**

Ideally, you can open the supplies bag and get the book, claws, and the heart from it. Once empty, the bag vanishes from your inventory. In a perfect world, the bag doesn't lose its contents on its own - without player input.

**Comment by Gurky-Turtle** [comment] 2023-07-18 14:37
I suggest disabling all addons and clearing your wdb, let us know if you can see the item inside the bag afterward.

**Comment by Dalzedur** [comment] 2023-07-18 16:48
Unfortunately, that won't be possible, since I have abandoned the quest, picked it up again, and that time the bag worked and I no longer have the faulty bag. :(

**Comment by Gurky-Turtle** [comment] 2023-07-18 19:57
ill go ahead and close this as I was unable to reproduce this problem.

**Closed by Gurky-Turtle** 2023-07-18 19:57 UTC
