### ISSUE TITLE
Face disappearance after using Barber services

### ISSUE THREAD

**Issue by Siachaaton** [slowtorta/turtlewow-bug-tracker#6075] opened 2024-01-23 13:01 UTC
Character's face disappeared

1. I changed the char's face as per instructions given in the NewYear token sent to all Goblins.
2. Rverything went smoothly until I used 'Barber' in Sparkwater port: the face just disppeared.
3. I repeatedly used barber several more times thinking the fine-working model will pop-up, but it never did

Can his face be re-set?

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110936958/15687b8d-238c-4847-8644-00d7f8053d96)

**Comment by twowTurtReynolds** [comment] 2024-01-23 14:24
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5730

**Closed by twowTurtReynolds** 2024-01-23 14:24 UTC
