### ISSUE TITLE
Quest "To Save a Soul" Bugged

### ISSUE THREAD

**Issue by Malkyn21** [slowtorta/turtlewow-bug-tracker#5160] opened 2023-11-10 20:41 UTC
**Please, provide a clear description what the bug is:**
When the first part of the quest was handed in to the totem to "return the bones to the totem", we had text mentioning a spirit/ghost had appeared, but we saw nothing. A GM was contacted and had the same issue, telling me to post about it here.

**Steps to reproduce the behaviour with as much detail as possible:**

1. Myself and my friend both had the issue after each other.
2. A GM was contacted and also had the same issue (Cherrypie)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?object=2010969
Item: https://database.turtle-wow.org/?item=60990
Quest: https://database.turtle-wow.org/?quest=41125

**Expected behavior. Describe how it should work:**
The ghost should appear, giving us the next quest!

**Comment by twowTurtReynolds** [comment] 2023-11-20 05:14
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5160

**Closed by twowTurtReynolds** 2023-11-20 05:14 UTC
Labels: Quest, Needs Replication
