### ISSUE TITLE
Warclocks - Fel Energy bug

### ISSUE THREAD

**Issue by ZorgDarkness** [slowtorta/turtlewow-bug-tracker#2866] opened 2023-02-20 15:33 UTC
Warlocks can cast Fel Energy when they are at demonology spec, than they can respec to other spec and stell have Fel Energy buff on tham as they in anothey spec wich is not have Fel Energy talant learned at thair taland tree
Spell: https://database.turtle-wow.org/?spell=18792

**Comment by balakethelock** [comment] 2023-02-20 22:28
It's not a bug. This discussion was finished a long time ago and they decided they remove succubus sacrifice but not the other sacrifices.

**Comment by redmagejoe** [comment] 2023-02-21 19:40
Duplicate of #2734.

Close this.

**Closed** 2023-02-21 19:46 UTC
