### ISSUE TITLE
Mantle of the Fallen Prophet has 2 Intellect Stats

### ISSUE THREAD

**Issue by ILostMyPants** [slowtorta/turtlewow-bug-tracker#5941] opened 2024-01-08 21:47 UTC
**Please, provide a clear description what the bug is:**

2 of the stats on Mantle of the Fallen Prophet are Intellect. Assuming it should be stated similarly to the other 2 pieces of the set, one of them should be Strength.

![Screenshot_20240108_134053](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90161901/2444e24d-b29a-4c2c-b08f-9978bbbc6ab6)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=21684

**Comment by twowTurtReynolds** [comment] 2024-01-08 22:45
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3695

**Closed by twowTurtReynolds** 2024-01-08 22:45 UTC
