### ISSUE TITLE
The chimney in Caer Darrow is a trap, no escape

### ISSUE THREAD

**Issue by Slimthegrim** [slowtorta/turtlewow-bug-tracker#6261] opened 2024-02-14 03:17 UTC
**Please, provide a clear description what the bug is:**
The chimney in Caer Darrow is inescapable.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/54cb7bb0-2b30-4b0c-a44b-dace88a05cc1)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/4665b3ff-acd3-4385-81eb-e2a38b1e3c1a)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to WPL, 69.5, 77
2. Jump on chimney
3. Fall in!
4. Uh oh stuck

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Characters 

**Expected behavior. Describe how it should work:**
The chimney has a huge opening yet LOS traps players. Should be able to walk out. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/110629519/50c53f54-914d-4a12-875b-bbade07eca25)

**Comment by twowTurtReynolds** [comment] 2024-02-14 03:18
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5623

**Closed by twowTurtReynolds** 2024-02-14 03:18 UTC
