### ISSUE TITLE
Lighting shield (shaman)

### ISSUE THREAD

**Issue by d-u-b** [slowtorta/turtlewow-bug-tracker#2929] opened 2023-03-03 08:34 UTC
Shamans spell https://database.turtle-wow.org/?spell=10434 deals damage when attacked with spells and grenade 
![bug](https://user-images.githubusercontent.com/6154054/222671271-b17cd75b-dc5a-4204-83bf-c9ad38691a73.jpg)
Should only work on physical damage

**Comment by Zeyla-TW** [comment] 2023-03-03 10:52
Lightning Shield has always procced off of all melee attacks, ranged attacks, and spells (grenades are technically a spell). It just has a proc interval/cooldown so you may not realize it right away. Working as intended.

**Comment by d-u-b** [comment] 2023-03-03 11:18
yes it must work on spells, but not grenade
https://youtu.be/PDphBIH09_E?t=106

**Comment by Zeyla-TW** [comment] 2023-03-03 11:25
If you look carefully you'll see that the video you linked gives a good example of the "proc interval/cooldown" on lightning shield. Because the grenade hit just after the frostbolt landed, and the frostbolt triggered a charge of lightning shield, the grenade was not yet able to trigger the next charge. I don't have the exact details in front of me atm, but I believe the proc interval on lightning shield charges is somewhere around a 2 or 3 second cooldown, or possibly longer.

**Comment by redmagejoe** [comment] 2023-03-04 11:18
This is working as intended and can be closed.

**Closed** 2023-03-04 11:19 UTC
