### ISSUE TITLE
Karazan enchanting bug

### ISSUE THREAD

**Issue by yebingfen** [slowtorta/turtlewow-bug-tracker#5405] opened 2023-11-28 03:02 UTC
**Please, provide a clear description what the bug is:**
Karazan enchantment leg item tips "that item is not a valid target"

**Steps to reproduce the behavior with as much detail as possible:**

1. I was exchange my Karazan enchantment item [Invocation of Greater Protection]
2. when i was used this enchantment item for my leg
3. game reminded me that my leg item is invalid "that item is not a valid target"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=

this is enchantment item:
Item: https://database.turtle-wow.org/?item=92006

this is my leg:
Item: https://database.turtle-wow.org/?item=65025

Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Karazan enchantment item [Invocation of Greater Protection],this item should be correct
![2023-11-28 10 58 05](https://github.com/slowtorta/turtlewow-bug-tracker/assets/67049386/83a1c12d-f4eb-44fa-86ad-dbfb7a4cb085)
![2023-11-28 11 02 08](https://github.com/slowtorta/turtlewow-bug-tracker/assets/67049386/72083a37-e619-4f18-8989-f3cd038525e9)
 adds 2% dodge chance to a leg or head slot item.

**Comment by Muigin** [comment] 2023-11-28 03:26
Duplicate of #4788

**Closed by Muigin** 2023-11-28 03:26 UTC

**Comment by yebingfen** [comment] 2023-11-28 03:35
OK iam fix this bug ,thank you very much~
