### ISSUE TITLE
Item: Invocation of Expansive Mind can not be applied as describe 

### ISSUE THREAD

**Issue by iyuorcan** [slowtorta/turtlewow-bug-tracker#5289] opened 2023-11-20 04:30 UTC
**Please, provide a clear description what the bug is:**
Item: Invocation of Expansive Mind can not be applied on may helmet and legplate as it describes 
**Steps to reproduce the behavior with as much detail as possible:**

1.  when i right click the item "Invocation of Expansive Mind"
2.  move to my helmet and left click
3. it shows on screen that:  that item is not  a valid target.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=92007

**Expected behavior. Describe how it should work:**

It should work as it describes, add a 20 SP to a leg or head item.

**Comment by twowTurtReynolds** [comment] 2023-11-20 04:34
Read the pinned issues please. Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4788

**Closed by twowTurtReynolds** 2023-11-20 04:34 UTC
