### ISSUE TITLE
weapon buff not stacking with juju power

### ISSUE THREAD

**Issue by Belugaga90** [slowtorta/turtlewow-bug-tracker#5741] opened 2023-12-24 02:17 UTC
Hi hello,

I think i found a issue with buffs not stacking properly.

The weapon "Fist of the Forgotten Order" has a chance on hit buff called "Order". that buff gives 50 strength for 15 secs. Right now, i have found that this buff will not stack with Juju power  which seems weird since they are from different source types.

Screenshots:

233 Strength with Juju Power (203 without):

![Screenshot from 2023-12-23 23-04-07](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152714032/f4cba81f-4bbc-4d89-8b85-b51ea109045c)

253 Strength with Order (203 without):

![Screenshot from 2023-12-23 23-12-19](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152714032/049e9720-74cc-4fb0-9772-459d7f1012a2)

253 Strength with Order and Juju Power (should be 283 if they stacked together)
![Screenshot from 2023-12-23 23-04-27](https://github.com/slowtorta/turtlewow-bug-tracker/assets/152714032/b50cac7f-34d2-4af3-beaa-4655279123b3)

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:37
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3994

**Closed by twowTurtReynolds** 2023-12-25 00:37 UTC
