### ISSUE TITLE
icy

### ISSUE THREAD

**Issue by muse518** [slowtorta/turtlewow-bug-tracker#5954] opened 2024-01-09 18:39 UTC
![20240109193854](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149399080/ff02a16d-c5b5-4263-a004-81cb6b63d8e4)
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2024-01-09 18:40
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5818

**Closed by twowTurtReynolds** 2024-01-09 18:40 UTC
