### ISSUE TITLE
Whipper Root Tuber pick up Bug 22.11.23

### ISSUE THREAD

**Issue by Matsubay** [slowtorta/turtlewow-bug-tracker#5339] opened 2023-11-22 14:29 UTC
**Please, provide a clear description what the bug is:**

Nothing being added to inventory after interaction with cleansed whipper root tuber.
Character nick is Matsubayashi

**Steps to reproduce the behavior with as much detail as possible:**

Im trying to complete Whipper root tuber cleansing in felwood. Plant is sucsessfuly cleansed. Cleansed plant appears. Im trying to interact with it. Character interacts, but nothing happens. Plant dissappears and nothing being added to inventory.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=11951
https://database.turtle-wow.org/?quest=4117

**Expected behavior. Describe how it should work:**

3-10 items should be obtained from each plant

**Comment by Matsubay** [comment] 2023-11-22 14:42
Asked couple players about this quest. They said that all works fine for them. And they getting the items.

**Comment by Length123** [comment] 2023-11-25 08:52
Did you get this to work?

**Comment by Matsubay** [comment] 2023-11-25 09:50
No, it didnt work. It got even worse. Now plant just disappears after quest for cleansing done. And cleansed plant not even appears at all.

Checked today.

**Comment by Length123** [comment] 2023-11-25 12:49
Yea same issue here. I made a bug post on it too, before I searched to see if others had the same trouble. There are 5 posts with this bug so far...

Gonna be alot of frustrated shamans, rogues, warriors, hunters, druids and paladins XD

**Comment by Muigin** [comment] 2023-11-25 16:09
Duplicate of #5332

**Closed by Muigin** 2023-11-25 16:09 UTC
