### ISSUE TITLE
Priest's Meditation Talent will render all equipments with meditation effect ineffective,

### ISSUE THREAD

**Issue by darkmoko** [slowtorta/turtlewow-bug-tracker#5929] opened 2024-01-07 18:45 UTC
Dear developers, i found a bug with Priest's Meditation Talent. The talent will render all equipments with meditation effect ineffective except the sets effect of Priest T2. It means if I use this talent, i can only gain up to 30%(T2 sets 15% + talent 15%).But if i won't use it, i can gain over 30%(T2 sets 15% + 5% * number of equipments). I came to this conclusion after conducting many tests. I think they should be able to stack(T2 sets 15% + talent 15% + 5% * number of equipments). Please check if the code has this bug. thanks.

**Comment by twowTurtReynolds** [comment] 2024-01-07 18:46
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1750

**Closed by twowTurtReynolds** 2024-01-07 18:46 UTC
