### ISSUE TITLE
No Guild Bank Access in Ironforge

### ISSUE THREAD

**Issue by CosmicCleric** [slowtorta/turtlewow-bug-tracker#4072] opened 2023-08-03 07:22 UTC
There is no guild bank access in Ironforge. There is no retail-like safes on the walls. There is one NPC as you first enter the bank, on the left side.

There is a NPC named Dinita Stonemantle who is a 'Vault Administrator', but clicking on her does nothing.

Her counterpart in Stormwind, at the Stormwind bank, is a "Guild Vault Administrator" (different guild name).

Perhaps there is a naming convention bug that prevents the Ironforge NPC to work properly to access a guild bank?

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the bank in Ironforge.
2. Click (either left or right) on Dinita Stonemantle, to try and gain access to a guild bank.
3. Nothing happens, no error message is generated.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7292

**Expected behavior. Describe how it should work:**

Would expect either a direct opening of the guild bank window, or a NPC window that would have an option to inspect the guild bank, which would then open the guild bank window.

**Comment by twowTurtReynolds** [comment] 2023-11-17 20:41
Yeah I understand how this is a bit confusing: Turtle has added the gbank feature to SW and Org only. Dinita Stonemantle is a 1.12 NPC that was just put there for some one off quest. It is entirely unrelated to the gbank feature.

I would suggest that you put in a suggestion on the forums for adding the gbank elsewhere and turning this NPC into ironforge's.

Closing as not a bug

**Closed by twowTurtReynolds** 2023-11-17 20:41 UTC
