### ISSUE TITLE
Dustwind Cave - Mobs stuck in place

### ISSUE THREAD

**Issue by rfelleto** [slowtorta/turtlewow-bug-tracker#4253] opened 2023-09-01 20:29 UTC
**Please, provide a clear description what the bug is:**
In the Cave located above Drygulch ravine in Durotar, the mobs aggro but are stuck in place. They can't move, and when attacked by ranged attacks they keep evading them. The only way to kill them is to go near melee range and attack because they won't move. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Agro any mob inside the cave
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Burning Blade Cultist] - (https://wowpedia.fandom.com/wiki/Burning_Blade_Cultist) and voidwalker
         [Burning Blade Thug](https://wowpedia.fandom.com/wiki/Burning_Blade_Thug)
         [Burning Blade Neophyte](https://wowpedia.fandom.com/wiki/Burning_Blade_Neophyte)

**Expected behavior. Describe how it should work:**
Mobs should aggro and chase you and probably kill you and then you die and start another character...

**Comment by rfelleto** [comment] 2023-09-02 16:30
I would like to add that the pathing of some of the mobs on the docks of Anchor Point are also behaving in the same manner.

**Comment by Muigin** [comment] 2023-10-20 09:50
Duplicate of #3659

**Closed by Muigin** 2023-10-20 09:50 UTC
