### ISSUE TITLE
Blood Ring Arena Mark of Honor not in Mail when inventory full

### ISSUE THREAD

**Issue by Artalos330** [slowtorta/turtlewow-bug-tracker#5043] opened 2023-11-03 11:44 UTC
**Please, provide a clear description what the bug is:**
Unlike the other battlegrounds, the Arena Mark of Honor from Blood Ring you would get don't get send in the mail when the inventory is full

**Steps to reproduce the behavior with as much detail as possible:**
Win or lose Blood Ring with full inventory

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61793

**Comment by twowTurtReynolds** [comment] 2023-11-20 05:01
dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5043

**Closed by twowTurtReynolds** 2023-11-20 05:01 UTC
Labels: PvP, Needs Replication
