### ISSUE TITLE
suffocates standing on the surface

### ISSUE THREAD

**Issue by UlukayOutkastov** [slowtorta/turtlewow-bug-tracker#5939] opened 2024-01-08 21:38 UTC
The character suffocates while standing in this place, standing on the surface. ~78.0, 46.0

![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/95168076/01f96916-484e-4090-af62-85f3c0d2e377)

**Comment by twowTurtReynolds** [comment] 2024-01-08 21:43
This is a duplicate of a pinned issue, please look there.

**Closed by twowTurtReynolds** 2024-01-08 21:43 UTC
