### ISSUE TITLE
Eye of the Dead bugs with Flash of Light

### ISSUE THREAD

**Issue by SavchenkoBogdan** [slowtorta/turtlewow-bug-tracker#6112] opened 2024-01-26 21:46 UTC
**Please, provide a clear description what the bug is:**
On use effect of trinket "Eye of the Dead" has 5 charges, which are supposed to be used on healing spells, Holy Light consumes 1 charge, but Flash of Light consumes 2 charges per use
**Steps to reproduce the behavior with as much detail as possible:**
1. Activate Eye of the Dead trinket effect - you have 5 charges 
2. Cast Flash of Light - you have 3 charges now (2 used)
3. Cast Flash of Light again - you are down to 1 charge (2 used again)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item (Eye of the Dead): https://database.turtle-wow.org/?item=23047
Spell (The Eye of the Dead on use effect): https://database.turtle-wow.org/?spell=28780
Spell (Flash of Light rank 6): https://database.turtle-wow.org/?spell=19943
**Expected behavior. Describe how it should work:**
Only 1 charge should be consumes by Flash of Light while Eye of the Dead trinket is active

**Comment by twowTurtReynolds** [comment] 2024-02-09 02:03
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5137

**Closed by twowTurtReynolds** 2024-02-09 02:03 UTC
