### ISSUE TITLE
Breath bar while not under water in Feralas.

### ISSUE THREAD

**Issue by nikitazoshchuk** [slowtorta/turtlewow-bug-tracker#5270] opened 2023-11-18 13:17 UTC
**Please, provide a clear description what the bug is:**
I was travelling through Feralas and breath bar suddenly appeared at the top of the screen. There are couple of spots in the area. I attached 3 screenshots.

**Steps to reproduce the behavior with as much detail as possible:**

1. Stand in Feralas at 78.5 46.4 
2. Breath bar should appear.
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
![Screenshot_20231118_160852](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85698173/bc535859-e802-4c98-8f55-4b3541440d73)
![Screenshot_20231118_160857](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85698173/e48c95ce-c038-4e89-bbbb-4ffa95d7f583)
![Screenshot_20231118_161551](https://github.com/slowtorta/turtlewow-bug-tracker/assets/85698173/d2368f40-ccc0-4464-8896-95fc17a2438f)

**Comment by cyaohiri** [comment] 2023-11-18 14:18
Looks like a duplicate of #4568.

**Comment by twowTurtReynolds** [comment] 2023-11-19 21:04
Yep. Thanks @nikitazoshchuk for the better pics.

**Closed by twowTurtReynolds** 2023-11-19 21:04 UTC
Labels: Client
