### ISSUE TITLE
Whipper Root Tubers Bugged

### ISSUE THREAD

**Issue by scheminpete** [slowtorta/turtlewow-bug-tracker#5360] opened 2023-11-23 20:24 UTC
I cannot loot Whipper Root Tubers in Felwood. The "Cleansed Whipper Root" is bugged.

**Steps to reproduce the behavior with as much detail as possible:**

1. I first cleanse a Corrupted Whipper Root using Cenarian Plant Salve x3.
2. I then try to loot the Cleansed Whipper Root, which should provide me with a couple Whipper Root Tubers.
3. Nothing is looted. I've done this over 20 times.

**Comment by Length123** [comment] 2023-11-25 08:52
Did you get this to work?

**Comment by Muigin** [comment] 2023-11-25 16:09
Duplicate of #5332

**Closed by Muigin** 2023-11-25 16:09 UTC
