### ISSUE TITLE
Still can't queue all 5 bgs simultaneously

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#3227] opened 2023-04-10 15:52 UTC
See #1648.

**Comment by afizzler** [comment] 2023-06-16 22:07
That is a different bug that is already fixed. The bug that needs to be fixed is when you can't queue for more than 3 BGs simultaneously

**Comment by twowTurtReynolds** [comment] 2023-12-09 04:42
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1648

**Closed by twowTurtReynolds** 2023-12-09 04:42 UTC
