### ISSUE TITLE
Southern Greater Wind Stone in Silithus is uninteractable 

### ISSUE THREAD

**Issue by OonaFae** [slowtorta/turtlewow-bug-tracker#5590] opened 2023-12-13 23:21 UTC
**Please, provide a clear descwription what the bug is:**
The south Wind Stone in Silithus can't be interacted with.
**Steps to reproduce the behavior with as much detail as possible:**

1. Go to southern greater wind stone
2. Mouseover it
3. Cursor does not change and cannot be interacted with

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Object: https://database.turtle-wow.org/?object=180466

**Expected behavior. Describe how it should work:**

Should be able to interact with it to summon the lord or damage yourself if youre not wearing the correct items.

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/105398809/8a627142-67f2-4af7-8358-c3ea65a119bc)

**Comment by twowTurtReynolds** [comment] 2023-12-13 23:39
There should have been a fix recently: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1988

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c4389caa-7039-46d6-a633-ea9d82d21e7b)

Blizzlike, there is a 3-4 hour respawn window on the stones. I will check back in 4 on the PTR.

**Comment by OonaFae** [comment] 2023-12-13 23:41
The stone respawns just fine on live. It just cant be interacted with

**Comment by twowTurtReynolds** [comment] 2023-12-13 23:53
Hmmm, yeah they are supposed to dissapear once you use them? And only reappear when ready to be used again?

The PTR one is still there but used and uninteractable.

**Comment by OonaFae** [comment] 2023-12-14 06:33
Yep Thats exactly correct. It should vanish once used. 
unsure if this one sticking around prevents respawns or if it just lingers and eventually becomes usable again. But its abnormal for sure, the others in the 2 north camps behave as expected

**Comment by twowTurtReynolds** [comment] 2023-12-14 12:33
Still uninteractable. It does prevent respawns.

**Comment by Muigin** [comment] 2024-02-25 21:52
This should now be fixed with the recent recoding of all Wind Stones in Silithus.

**Closed by Muigin** 2024-02-25 21:52 UTC
Labels: Object, Reproduced

**Comment by Darthblaider** [comment] 2024-03-02 01:05
Just ran through all the twilight camps in Silithus and none of the lesser windstones are interactable, but most of the regular and greater ones are. If this is fixed, its certainly not implemented as intended.

**Comment by twowTurtReynolds** [comment] 2024-03-03 05:38
We have another ticket open to take another look at this.
