### ISSUE TITLE
Captain Ironhill in Dun Garok seems to ignore Vanish's stealth dropping aggro

### ISSUE THREAD

**Issue by Reiiama** [slowtorta/turtlewow-bug-tracker#4091] opened 2023-08-05 12:42 UTC
**Please, provide a clear description what the bug is:** I was running through Dun Garok as a HC rogue in a small group. Shit hit the fan at Captain Ironhill and I decided to Vanish, with no enemies nearby. Captain Ironhill along with several other Dun Garok NPCs kept chasing after my allies and, after killing them, returned directly to me as all the other enemies were resetting and attacked me, breaking me out of stealth. This led to my death.

**Steps to reproduce the behavior with as much detail as possible:**

1. As a Rogue, pull Captain Ironhill and associates
2. Have someone else take aggro and run Captain Ironhill away
3. Vanish
4. Watch Captain Ironhill return after supposedly resetting and kill you.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2304
Spell: https://database.turtle-wow.org/?spell=1856

**Expected behavior. Describe how it should work:** Captain Ironhill and associates should properly flush you from their threat table if you are a Rogue using Vanish.

**Comment by Dalzedur** [comment] 2023-08-13 04:23
The story doesn't mention what actions you did after vanishing. I might be confusing vanish mechanics with feign death, but at least with one of them there is a resist check that can fail if the enemy is higher level than you and there isn't a wall or some obstacle that breaks line of effect ( as in, you cannot cast spells through it ). But it did sound like it wasn't resisted if the enemies did change their target to your party members after you vanished... maybe one of them resisted the effect but you weren't their primary threat target, so once they got done with the party members, this one was still aggro at you and dragged his mates into the battle against you again.

Since they returned and attacked you and only then your broke out of stealth, it wasn't clearly a case of dot ending your stealth too soon. Did you get messages for 'leaving battle' and 'entering battle' in this scenario? And you probably didn't heal yourself if you were still in vanish stealth, so it can't be healing related threat that made you a target again. Did someone/you place down an engineer's target dummy or a ghost saber summon or something along those lines? Those are considered to be pets under the player's control, and even if they are stealthed and the target dummy / pet is in battle, once they die the enemies stay mad at the owner maybe?

**Comment by Reiiama** [comment] 2023-09-04 23:44
> The story doesn't mention what actions you did after vanishing. I might be confusing vanish mechanics with feign death, but at least with one of them there is a resist check that can fail if the enemy is higher level than you and there isn't a wall or some obstacle that breaks line of effect ( as in, you cannot cast spells through it ). But it did sound like it wasn't resisted if the enemies did change their target to your party members after you vanished... maybe one of them resisted the effect but you weren't their primary threat target, so once they got done with the party members, this one was still aggro at you and dragged his mates into the battle against you again.
> 
> Since they returned and attacked you and only then your broke out of stealth, it wasn't clearly a case of dot ending your stealth too soon. Did you get messages for 'leaving battle' and 'entering battle' in this scenario? And you probably didn't heal yourself if you were still in vanish stealth, so it can't be healing related threat that made you a target again. Did someone/you place down an engineer's target dummy or a ghost saber summon or something along those lines? Those are considered to be pets under the player's control, and even if they are stealthed and the target dummy / pet is in battle, once they die the enemies stay mad at the owner maybe?

I don't remember whether I got messages for ending battle, but I definitely was not dotted. All I did once I vanished was find a corner to stand in while stealthed and wait for enemies to reset so I could attempt to sneak out. I put down an Engineering dummy a ways back, but it was destroyed well before I Vanished.

**Comment by twowTurtReynolds** [comment] 2023-12-04 14:57
This looks to be a dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3421

**Closed by twowTurtReynolds** 2023-12-04 14:57 UTC
