### ISSUE TITLE
Gilneas horde quest giver bugged - Orvan Darkeye

### ISSUE THREAD

**Issue by Tlaklife** [slowtorta/turtlewow-bug-tracker#4647] opened 2023-10-08 21:11 UTC
After I finished first quest,  i was able to take another quest but the quest giver runed into aliance player and after that i was no able to pick up quest again, so im stuck without other chain quests.

I guess the best way to avoid this is make the npc non agressive to alliance.

**Comment by Gobwlin** [comment] 2023-10-10 16:54
Hello, can't you pick up quest that is part of chain quest? Does your issue sound like my?
[](https://github.com/slowtorta/turtlewow-bug-tracker/issues/4672)

**Comment by Muigin** [comment] 2023-10-20 09:36
Duplicate of #4498

**Closed by Muigin** 2023-10-20 09:36 UTC
