### ISSUE TITLE
Improved ghost wolf talent did not affect on ghost wolf spell. 

### ISSUE THREAD

**Issue by chavey1** [slowtorta/turtlewow-bug-tracker#1972] opened 2022-08-19 23:26 UTC
**Please, provide a clear description what the bug is:**

Improved ghost wolf talent did not affect on ghost wolf spell. 

**Steps to reproduce the behavior with as much detail as possible:**

During leveling at my HC shaman i face a bug. I was learned first of two skillpoint of improved ghost wolf at 17 lvl, at 20 level i throw second one to improved ghost wolf and noticed that my ghost wolf spell casting 1 second instead of beign instant. 
Here is the video https://youtu.be/61DzTwRk1Qs

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

ghost wolf - https://database.turtle-wow.org/?spell=3691

improved ghost wolf - https://database.turtle-wow.org/?spell=16287

**Expected behavior. Describe how it should work:**

I guess somehowe my first learn at 17 lvl did not count for unknown for me reason.

Thanks!

**Comment by Tormund** [comment] 2022-10-03 21:17
So I have same issue. Here is screenshot 
![image](https://user-images.githubusercontent.com/3950336/193684310-b42446de-cfff-4e63-b2f1-793f2f393934.png)

**Comment by cyaohiri** [comment] 2022-10-04 10:47
Duplicate of #1836. See my comment there.

**Comment by Velite12** [comment] 2022-10-04 19:14
Closing this as duplicate, Ghost Wolf should be 1 second cast as intended.

**Closed by Velite12** 2022-10-04 19:14 UTC
