### ISSUE TITLE
Invocation of Shattering enchant 

### ISSUE THREAD

**Issue by Genkii2** [slowtorta/turtlewow-bug-tracker#5001] opened 2023-11-01 04:01 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Invocation of shattering ARP enchant for head and leg, when attempting to enchant my Darkflame helm Just says "item is not a valid target 

![image_2023-11-01_000109831](https://github.com/slowtorta/turtlewow-bug-tracker/assets/149554863/4bfaee6f-b606-4de1-83eb-71d406c45e32)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Muigin** [comment] 2023-11-01 05:02
Duplicate of #4788

**Closed by Muigin** 2023-11-01 05:02 UTC
