### ISSUE TITLE
I cant use the blood belt buckle to other player

### ISSUE THREAD

**Issue by ddhhxx** [slowtorta/turtlewow-bug-tracker#4580] opened 2023-10-06 13:27 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

I cant use the blood belt buckle to other player, but buckles can use like enchant, and i try to delete the WDB, but of no avail.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment] 2023-10-06 19:52
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4583

**Closed by ratkosrb** 2023-10-06 19:52 UTC
