### ISSUE TITLE
Nightmare Dreamrunner no mountspecial animation

### ISSUE THREAD

**Issue by Vim-Karene** [slowtorta/turtlewow-bug-tracker#4236] opened 2023-08-30 16:08 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Spacebar to activate mountspecial animation on mounts
2. The Nightmare Dreamrunner does nothing.
3.  Guessing it's overlooked and or just forgotten. 
4. I want my emo unicorn to rear D;

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-12-09 02:29
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5449

**Closed by twowTurtReynolds** 2023-12-09 02:29 UTC
Labels: Client
