### ISSUE TITLE
Quest Thandol Span is bugged and cannot be completed

### ISSUE THREAD

**Issue by RDK83** [slowtorta/turtlewow-bug-tracker#6231] opened 2024-02-11 21:57 UTC
**Please, provide a clear description what the bug is:**
The NPC Vladeus Springriver despawns when you transition zones on the quest Thandol Span

**Steps to reproduce the behavior with as much detail as possible:**

1. Be on the quest Thandol Span
2. Defeat the scarlet recruits and Vladeus
3. Talk to Vladeus and get him to come with you
4. Move towards Menethil harbour
5. Notice Vladeus disappears when changing zones and doesn't re-appear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50674
Quest: https://database.turtle-wow.org/?quest=80703

**Expected behavior. Describe how it should work:**
The NPC respawns when you transition zones, like pets do

**Comment by twowTurtReynolds** [comment] 2024-02-12 03:42
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5352

**Closed by twowTurtReynolds** 2024-02-12 03:42 UTC
