### ISSUE TITLE
Spirecrest Naga's in Gilneas stuck in ground, cant move/be charged/evade when you move out of range

### ISSUE THREAD

**Issue by JohnBradley01** [slowtorta/turtlewow-bug-tracker#5390] opened 2023-11-26 10:05 UTC
**Please, provide a clear description what the bug is:**

Several mobs in the area are stuck in the ground, cant move. Around 32.8 / 80.1

**Steps to reproduce the behavior with as much detail as possible:**

Just try and target/attack any mob.

1. Use charge, will say "no path can be found" 
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61408
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Not stuck in the ground.

**Comment by twowTurtReynolds** [comment] 2023-11-29 18:18
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5040

**Closed by twowTurtReynolds** 2023-11-29 18:18 UTC
Labels: NPC, Needs Replication
