### ISSUE TITLE
Fishing Bug No Nightfin for almost a year

### ISSUE THREAD

**Issue by Skiddles88** [slowtorta/turtlewow-bug-tracker#4904] opened 2023-10-25 15:37 UTC
Fishing at night produces no Nightfin with all addons disabled and WDB deleted
A blank loot bag opens with nothing inside.
I have traveled to all areas during night for a year now and nothing even with maxed fishing nat pagler's pole and lures.
Upon further investigation there is plenty of people reporting the same thing on forums. 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/148993201/74716f92-1469-4453-b21d-6c71097f1839)

**Comment by XandyCode** [comment] 2023-10-28 02:57
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4530

**Comment by Muigin** [comment] 2023-10-28 03:21
Please do not make duplicate tickets.  I can assure you this has not been an issue for a year, and has only recently come up.

**Closed** 2023-10-28 03:20 UTC
