### ISSUE TITLE
scholo  last  boss

### ISSUE THREAD

**Issue by fengziya000** [slowtorta/turtlewow-bug-tracker#5351] opened 2023-11-23 08:57 UTC
I have a bug to submit. In the battle of Scholo's final boss, when a person was teleported and didn't finish fighting the monsters, the boss died. The teleported person did not have equipment to drop. My mage appeared once yesterday, and the pastor in the team also appeared once today

**Comment by fengziya000** [comment] 2023-11-23 09:08
My mage was teleported 3 times, and the last time there was no blue to clear the monster out

**Comment by twowTurtReynolds** [comment] 2023-12-04 20:37
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3896

**Closed by twowTurtReynolds** 2023-12-04 20:37 UTC
