### ISSUE TITLE
Crystal Sword o f the Blossom not showing when sheathed, even after transmog

### ISSUE THREAD

**Issue by LWildschut** [slowtorta/turtlewow-bug-tracker#5677] opened 2023-12-20 21:55 UTC
**Please, provide a clear description what the bug is:**
Crystal Sword of the Blossom is not visible on my character when sheathed. Even when transmogged, the sword is still not visible. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire Crystal Sword of the Blossom
2. Equip Crystal Sword of the Blossom
3. Wonder what happened to Crystal Sword of the Blossom, as it disappeared
4. Unsheathe and discover you do indeed own a Crystal Sword of the Blossom
5. Sheathe it again, and once again despair
6. Transmog it for the same result, but now being a Fashion Coin down

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=61523

**Expected behavior. Describe how it should work:**

I presume the sword should indeed be visible. At the very least it should be after getting transmogged.

**Comment by twowTurtReynolds** [comment] 2023-12-21 04:07
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5153

**Closed by twowTurtReynolds** 2023-12-21 04:07 UTC
