### ISSUE TITLE
Infinite Hunt Quest

### ISSUE THREAD

**Issue by thesm0kem0n5ter** [slowtorta/turtlewow-bug-tracker#4928] opened 2023-10-27 15:04 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The quest Infinite Hunt in Seradane is bugged. This quest starts with Chromie in WP. You cannot interact with the crystal 
2. https://database.turtle-wow.org/?quest=80411
3. I think its supposed to summon a mob to kill

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Anstan2023** [comment] 2023-10-27 19:06
Yes, this quest is bugged. I also can't click the crystal when doing the quest.

**Comment by curseless123** [comment] 2023-10-28 10:48
bugged

**Comment by Muigin** [comment] 2023-10-30 07:04
Duplicate of #3650

**Closed by Muigin** 2023-10-30 07:04 UTC
