### ISSUE TITLE
Wrong tooltip for Abyssal Wave / Unmelting Ice

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#6170] opened 2024-02-04 18:28 UTC
These items have the same tooltip as Abyssal Wind + Unyielding Gust. Tooltip should be: `Combine the Abyssal Wave with the Unmelting Ice.`

https://database.turtle-wow.org/?item=83557
https://database.turtle-wow.org/?item=83552

**Comment by byvide** [comment] 2024-02-06 22:55
duplicate of #6033

**Comment by twowTurtReynolds** [comment] 2024-02-08 09:19
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/6033

**Closed by twowTurtReynolds** 2024-02-08 09:19 UTC
