### ISSUE TITLE
Sillithus Hive Scout Reports tactical assignments cant be completed

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2039] opened 2022-08-30 15:38 UTC
**Please, provide a clear description what the bug is:**

![WoWScrnShot_083022_170922](https://user-images.githubusercontent.com/25199983/187479721-0ac4118c-e0c9-44d4-9f08-ad7dfe309bc3.jpg)

![WoWScrnShot_083022_170919](https://user-images.githubusercontent.com/25199983/187479728-4c145b90-4ef7-4927-83bd-456838f4cbca.jpg)

this qeust can not be compelted, the npc does not give the report that was asked for
i assume the other 2 hives quests are also bugged

https://database.turtle-wow.org/?search=cenarion+scout
https://database.turtle-wow.org/?search=scout+report#quests
https://database.turtle-wow.org/?search=scout+report#items

**Expected behavior. Describe how it should work:**

not sure how it works on calssic,  i assume the scout have a dialog option that gives the player a report item

**Comment by Tinyfin-github** [comment] 2022-09-02 09:49
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1552

**Closed by Tinyfin-github** 2022-09-02 09:49 UTC
