### ISSUE TITLE
The powerful poison bottle cannot increase BUFF normally!

### ISSUE THREAD

**Issue by 13972355599** [slowtorta/turtlewow-bug-tracker#5229] opened 2023-11-15 18:19 UTC
**Please, provide a clear description what the bug is:**
   Karazan's powerful poison bottle ornament has only added 2 layers of BUFF, which does not match the description and has caused serious bugs!
**Steps to reproduce the behavior with as much detail as possible:**
1.Regardless of any monster, you should add 2 layers of BUFF, and the correct one is 5 layers!
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= Strong Poison Bottle    61243
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
   It should stack 5 layers of BUFF normally!

**Comment by Muigin** [comment] 2023-11-15 18:26
Duplicate of #5152

**Closed by Muigin** 2023-11-15 18:26 UTC

**Comment by 13972355599** [comment] 2023-11-15 18:28
关键没有人回复啊！
