### ISSUE TITLE
Winterveil quest issues

### ISSUE THREAD

**Issue by LordSpank** [slowtorta/turtlewow-bug-tracker#5602] opened 2023-12-14 19:21 UTC
Winterveil quest "Life comes to the Legend" , the dwarf NPC does not seem to spawn. Then unable to complete and turn in quest. I have run around the mountains surrounding IF as much as possible. (I even found a little mage on top of IF, who will talk to you but had no quests). could not find this NPC. I checked the mountainous area around the airfield. No NPC :(

**Steps to reproduce the behavior with as much detail as possible:**

1. go to area NPC was last seen at (last year's event)
2. ask in guild and world chat
3. check on forum for same issue

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

quest_40781_dummy_triger ?

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

an NPC - the dwarf winterfather - should be standing in a place you can reach, so that your toon might interact with the NPC. completing a requirement for the quest - in this case, the lst requirement i need to complete the quest.

**Comment by LordSpank** [comment] 2023-12-14 19:25
in game toon name - Rin game toon name - Redbardedbard

**Comment by twowTurtReynolds** [comment] 2023-12-15 20:28
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5605

**Closed by twowTurtReynolds** 2023-12-15 20:28 UTC
