### ISSUE TITLE
Quest bug: Secret of the Circle

### ISSUE THREAD

**Issue by Tomagazda** [slowtorta/turtlewow-bug-tracker#5438] opened 2023-11-30 00:31 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The The Stone Circle quest should unlock Into the Depths AND Secret of the Circle quests. In turtleWow Secret of the Circle can be unlocked ONLY by finishing Into the Depths. In this way was one need to go Sunken Temple twice, and it differs from wowhead

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

TQuest: https://database.turtle-wow.org/?quest=3446
https://database.turtle-wow.org/?quest=3447
https://database.turtle-wow.org/?quest=3444

Wowhead:
https://www.wowhead.com/classic/quest=3446/into-the-depths
https://www.wowhead.com/classic/quest=3444/the-stone-circle
https://www.wowhead.com/classic/quest=3447/secret-of-the-circle

**Expected behavior. Describe how it should work:**
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/83549873/ea11bbe9-9b19-4b46-8602-1784dbb1789a)

**Comment by cyaohiri** [comment] 2023-11-30 00:36
Duplicate of #4766.

Currently it's not required to go there twice, because the altar both finishes the first quest and starts the next one.

**Closed** 2023-11-30 01:23 UTC
