### ISSUE TITLE
Zandalarian Hero Medallion and Tiger's Fury not stacking

### ISSUE THREAD

**Issue by Tephus** [slowtorta/turtlewow-bug-tracker#3437] opened 2023-05-11 16:28 UTC
**Please, provide a clear description what the bug is:**
Druid's Tiger Fury buff is not stacking with Zandalarian Hero Medallion

**Steps to reproduce the behavior with as much detail as possible:**

1. Be in Cat Form as a druid. Look at Damage in character sheet (or check damage via target dummies)
2.  Cast Tiger's Fury
3. Use ZHM
4. Check damage in character sheet. Only up 40 instead of 80 as it should be. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=19949
Spell: https://database.turtle-wow.org/?spell=9846

**Expected behavior. Describe how it should work:**
These should stack. They stacked on Vanilla and Classic Vanilla wow. Using both should result in +80 damage.

**Comment by twowTurtReynolds** [comment] 2023-12-09 04:21
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3994

**Closed by twowTurtReynolds** 2023-12-09 04:21 UTC
