### ISSUE TITLE
No item pick-up tips ~help ps~

### ISSUE THREAD

**Issue by Weitian0620** [slowtorta/turtlewow-bug-tracker#4990] opened 2023-10-31 18:12 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.ID:Himula
2. pick-up rights after Boss's death in a fight with psychic college's Gardiner Boss, for non-display status, so it should belong to my courage kit head, no hint of need or greed options, the system helped me default to greed, so I didn't get the equipment I should have needed
3. Helm of valar

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-19 20:12
dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5000

**Closed by twowTurtReynolds** 2023-11-19 20:12 UTC
