### ISSUE TITLE
 E'ko

### ISSUE THREAD

**Issue by krasurka** [slowtorta/turtlewow-bug-tracker#3402] opened 2023-05-06 11:33 UTC
E'ko No longer drops for every party member.

When killing monsters in winterspring, find with the composition of the group, monsters should drop E'ko for each member of the group. After the last update, E'ko stopped dropping for everyone. and now only drops to one member of the group.

NPC: 
https://database.turtle-wow.org/?npc=7428
https://database.turtle-wow.org/?npc=7429
https://database.turtle-wow.org/?npc=7438
https://database.turtle-wow.org/?npc=7440
https://database.turtle-wow.org/?npc=7442
https://database.turtle-wow.org/?npc=7441
https://database.turtle-wow.org/?npc=10916
https://database.turtle-wow.org/?npc=10738
https://database.turtle-wow.org/?npc=7439

Item: https://database.turtle-wow.org/?item=12431
https://database.turtle-wow.org/?item=12436

All of the monsters listed above must drop E'ko for each party member.

**Comment by Haaxor1689** [comment] 2023-05-06 15:08
DUplicate of #3391

**Closed by Haaxor1689** 2023-05-06 15:08 UTC
