### ISSUE TITLE
Warlock summons drop people into the ground in front of Kara now

### ISSUE THREAD

**Issue by User456789321** [slowtorta/turtlewow-bug-tracker#5899] opened 2024-01-05 04:22 UTC
**Please, provide a clear description what the bug is:**

Ever since the new underground area below kara was opened up, getting warlock summoned in front of the steps for Karazhan will drop you through the ground.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a warlock portal summoned roughly in front of the steps at the Karazhan entrance
2.  The person who gets summoned will drop through the ground into the tunnel below 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=698

**Expected behavior. Describe how it should work:**

Getting summoned should not drop you through ground terrain.

**Comment by twowTurtReynolds** [comment] 2024-01-05 14:02
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5368

**Closed by twowTurtReynolds** 2024-01-05 14:02 UTC
