### ISSUE TITLE
Warlock pets dissapears on BGs after respawned by Spirit Healers

### ISSUE THREAD

**Issue by istrizhakov** [slowtorta/turtlewow-bug-tracker#5743] opened 2023-12-24 07:51 UTC
**Please, provide a clear description what the bug is:**

In 50% of times when you are respawning on BG graveyard your last pet aren't respawning with you which is annoying issue.

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to battleground as warlock and play it for 10-15 minutes.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?spell=691
https://database.turtle-wow.org/?spell=688
https://database.turtle-wow.org/?spell=712
https://database.turtle-wow.org/?spell=697

**Expected behavior. Describe how it should work:**

Keep the last pet and respawn it when warlock respawned if zone is battleground.

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:38
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3279

**Closed by twowTurtReynolds** 2023-12-25 00:38 UTC
