### ISSUE TITLE
Dustwind Cave 

### ISSUE THREAD

**Issue by AnasterianSunstrider** [slowtorta/turtlewow-bug-tracker#3886] opened 2023-07-06 15:54 UTC
The mobs in Dustwind Cave are stuck and can only be attacked when you get really close to them. They will evade any ranged attacks and pets (at least my voidwalker) dont seem to be able to find a path to them.

**Comment by Muigin** [comment] 2023-10-20 09:51
Duplicate of #3659

**Closed by Muigin** 2023-10-20 09:51 UTC
