### ISSUE TITLE
deserter debuff when client crashes

### ISSUE THREAD

**Issue by elboaf** [slowtorta/turtlewow-bug-tracker#5748] opened 2023-12-24 12:06 UTC
**Please, provide a clear description what the bug is:**
when in a battleground, if the client crashes and you have to restart the client, sometimes you will get kicked from the battleground and gain the deserter debuff for 15 minutes

**Steps to reproduce the behavior with as much detail as possible:**

1. queue for and join a battleground
2. play the game normally, in the battleground, until the client crashes
3. restart the client, log in, select character, find that you are no longer in the battleground and now have the deserter debuff

**Expected behavior. Describe how it should work:**
if client crashes while in the battleground there should be a grace period, maybe 60-90 seconds, to allow you to log back in and remain in the battleground.

**Comment by twowTurtReynolds** [comment] 2023-12-25 00:36
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4266

**Closed by twowTurtReynolds** 2023-12-25 00:36 UTC
