### ISSUE TITLE
Precious the devourer respawns after killing it and feigning death

### ISSUE THREAD

**Issue by ArthurusMenks** [slowtorta/turtlewow-bug-tracker#3214] opened 2023-04-09 03:26 UTC
**Please, provide a clear description what the bug is:**
When you kill Simone's pet before her and feign death she resets and the dog respawns next to her making the whole process useless and making you obliged to kill her before.
**Steps to reproduce the behavior with as much detail as possible:**

1. Aggro Simone
2.  Kill Precious
3. Feign Death

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=14533
NPC: https://database.turtle-wow.org/?npc=14538

**Expected behavior. Describe how it should work:**
The add should not respawn after getting killed even after feign death

**Comment by twowTurtReynolds** [comment] 2023-12-12 03:32
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/3177

**Closed by twowTurtReynolds** 2023-12-12 03:32 UTC
