### ISSUE TITLE
Lvl 36 player can't open Large Solid Chest in Desolace

### ISSUE THREAD

**Issue by Spectronum3** [slowtorta/turtlewow-bug-tracker#4832] opened 2023-10-19 15:04 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Be lvl 36 Horde Shaman in Desolace
2. Try to open a Large Solid Chest
3. Can't open, because *red text* - "Not high enough level to open"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item= Database doesn't work
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

I'm almost certain that as a lvl 36 in Desolace I should be able to open anything that isn't locked.

**Comment by slowtorta** [comment] 2023-10-20 10:30
Imposible to fix without knowing the chest location.

**Comment by Spectronum3** [comment] 2023-10-20 12:19
If I'll ever go there again, i'll make one or two pictures. Sadly i've got only one with the red text, and not the map location.

**Comment by twowTurtReynolds** [comment] 2023-12-30 02:25
Closing as duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5674

**Closed by twowTurtReynolds** 2023-12-30 02:25 UTC
Labels: Further informations required
