### ISSUE TITLE
[Quest Giver Bugged]The Northeast Passage - Inunquaq NPC

### ISSUE THREAD

**Issue by kravis** [slowtorta/turtlewow-bug-tracker#5174] opened 2023-11-11 18:03 UTC
**Please, provide a clear description what the bug is:**
You used to be able to speak with the quest giver Inunquaq who would provide two quests to complete to head to Northrend. First Crawling for Meat which would lead into The Northeast Passage. I've done these quests before and have pictures below for the ending chain reward.

**Steps to reproduce the behavior with as much detail as possible:**

1. Speak with Inunquaq: https://database.turtle-wow.org/?npc=81046
2. Complete Crawling for Meat: https://database.turtle-wow.org/?quest=80391
3. Leads into The Northeast Passage: https://database.turtle-wow.org/?quest=40321

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=81046

Quest: https://database.turtle-wow.org/?quest=80391

**Expected behavior. Describe how it should work:**

The initial Crawling for Meat quest is missing. Pictures below to show its been doable before and what the quest giver says now.

![ice](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/dda95f14-8b55-46d1-9db0-dd4aa01639f0)
![inunquaq](https://github.com/slowtorta/turtlewow-bug-tracker/assets/2722656/1b234b59-5eda-4701-91ed-33bfee688ad8)

**Comment by ratkosrb** [comment] 2023-11-12 06:41
I can't reproduce the problem. I can see the quest.

![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/d1c2c601-0554-4039-ba5d-013627479ea2)

**Comment by Muigin** [comment] 2023-11-21 15:06
This has been fixed as of a recent patch to allow Horde to take this quest.

**Closed by Muigin** 2023-11-21 15:06 UTC
Labels: Couldn't reproduce
