### ISSUE TITLE
Starfire randomly loses talent effect for reduced casting speed.

### ISSUE THREAD

**Issue by DraxerTABC** [slowtorta/turtlewow-bug-tracker#2454] opened 2022-11-12 15:34 UTC
**Please, provide a clear description what the bug is:**
It keeps happening for month, in raids in dungeons, even after sending screenshots been told "How can you prove it's happening"

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Spell: https://database.turtle-wow.org/?spell=25298

**Expected behavior. Describe how it should work:**
The cast time should be 3 secs, not 3.5. EVEN sent screenshots to Jamey but he still went "CANT PROVE IT" well it is happening and it must be the talent being fucked up, because Wrath still has its cast time reduction, but Starfire gets randomly fucked.

**Comment by DraxerTABC** [comment] 2022-11-12 15:39
Only way that I found that fixes it temporary  is respecing talents.

**Comment by jameyboor** [comment] 2022-11-14 20:25
Please don't make extra issue threads on the same bug. I didn't close your old one https://github.com/slowtorta/turtlewow-bug-tracker/issues/2393

I asked for some kind of proof in the form of a video or some steps to take to reproduce the bug because I can't reproduce it. Giving attitude doesn't work for anyone involved. We're trying to help you but we need verification that it even happens in the first place. Closing this, use the old thread.

**Closed by jameyboor** 2022-11-14 20:25 UTC
