### ISSUE TITLE
Rogue stuns spins hitbox 180

### ISSUE THREAD

**Issue by PickledPoe** [slowtorta/turtlewow-bug-tracker#44] opened 2021-06-14 14:05 UTC
By opening this Issue, I admit to having done the pertinent research using sources from Vanilla (preferably) or Classic. I also understand that sources from other private servers are not acceptable.

**Current behavior**: 
Occasionally Kidney shot and gouge spin the hitbox of a mob 180 degrees, sometimes the mob moves with the hit box other times it doesn't. Sometimes its just the model spinning. so its very hard to know where the backside is for backstabbing. Haven't noticed this with cheap shot but kidney does it almost every time.

**Expected behavior**: 
That a mob gets stunned in the same position.

**Steps to reproduce**:

1.  Normal rotation

**Comment by Snufflenose** [comment] 2021-09-21 08:20
I can confirm this bug.

Gouge (my rogue is only level 11, so I can't comment about other stun abilities) often turns the mob sideways or even makes it do a 180°.

In order to backstab the gouged mob you have to remember where you initially stood - even if that means you're (visually) doing a frontstab.

Quite confusing and annoying.

**Comment by Nolin7777** [comment] 2021-10-02 13:56
Should have been fixed with a fix which prevents front stabbing, which were reverted. Means this is working as intended on this server.

**Closed by Nolin7777** 2021-10-02 13:56 UTC
