### ISSUE TITLE
Wickerman Not Giving Buff

### ISSUE THREAD

**Issue by Oolaatris** [slowtorta/turtlewow-bug-tracker#4848] opened 2023-10-20 20:17 UTC
**Please, provide a clear description what the bug is:**
After the speech and burning of the Wickerman outside of Under City, clicking on the Wickerman Embers does not give the anticipated buff (Invocation of the Wickerman).

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to the Wickerman outside of UC around 8:00 PM
2.  Wait for the Wickerman to be burned
3.  Click on the piles of ash "Wickerman Ember" and see that no buff is given

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Cannot provide ID's from turtle database due to database being down, here is the Classic page for the buff (https://www.wowhead.com/classic/spell=24705/invocation-of-the-wickerman)

**Expected behavior. Describe how it should work:**
While the Wickerman is burning, players should be able to click on Wickerman Ember and get the Invocation of the Wickerman buff

**Comment by cyaohiri** [comment] 2023-10-20 20:33
Duplicate of #2303.

**Closed** 2023-10-20 22:40 UTC
