### ISSUE TITLE
There is a bug in the Mage's T0.5 leggings

### ISSUE THREAD

**Issue by whatoutlima** [slowtorta/turtlewow-bug-tracker#5274] opened 2023-11-19 03:50 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The 23 spell damage on the T.05 leggings should be the equipment active, but it is currently shown to be using the zodiac, and it cannot be used
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment] 2023-11-19 03:57
Dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/4908

**Closed by twowTurtReynolds** 2023-11-19 03:57 UTC

**Comment by whatoutlima** [comment] 2023-11-19 05:07
How can I solve this problem?

**Comment by whatoutlima** [comment] 2023-11-19 05:07
> #4908 的骗局

How can I solve this problem?

**Comment by twowTurtReynolds** [comment] 2023-11-19 13:40
https://github.com/slowtorta/turtlewow-bug-tracker/issues/4908#issuecomment-1815549498
