### ISSUE TITLE
"Allows 5% of your mana regeneration to continue while casting" from items doesn't work with more than 1 point in priest "Meditation" talent.

### ISSUE THREAD

**Issue by NochuWade** [slowtorta/turtlewow-bug-tracker#5586] opened 2023-12-13 11:46 UTC
I'm a lvl 60 holy priest.

1. got 3/3 points in Meditation
2. don't have any cloak, rings or amulet equipped.
3. Get 21 mana every 2 seconds while casting (as per BetterCharacterStats description - spirit regen 61mp2 when not casting, 15% of that is 9; got 30mp5 from gear so 12mp2, 9+12=21, that's 21 mana every 2 seconds, all checks out).
4. I equip 2 rings, amulet and cloak which all combined give me 20% mana regen while casting, 5mp5 and 23 spirit.
5. BetterCharacterStats now reports I have 68mp2 spirit regen when not casting, 35% mana regen while casting total, 35 mp5 regen and 14 mp2 regen and should be getting 37 mana every 2 seconds now (68x0.35 + 14 = 37).
Yet I only get 24 mana every 2 seconds so only 3 more than before equipping all those items (1mp2 from 23 spirit from Meditation's 15% and 2mp2 from 5mp5). Adding items 1 by 1 didn't help anything, 5% didn't kick in at any step.

First Impression - % regen while casting stat from all those items straight up doesn't work.

Items I equipped:

https://database.turtle-wow.org/?item=2043
https://database.turtle-wow.org/?item=60798
https://database.turtle-wow.org/?item=60564
https://database.turtle-wow.org/?item=83465

But I tried reseting talents:

6. 0/0 points in Meditation, all my gear equipped except for those 4 items.
7. Should have 12mp2 while casting now as per BCS report (from mp5 gear pieces) - checks out.
8. Adding 7spi/5% ring - reported mp2 goes from 12 to 15 - checks out.
9. Adding 16spi/5%ring - reported mp2 goes from 15 to 18 - checks out.
10. Adding 5mp5/5% neck - reported mp2 goes from 18 to 24 - checks out (15% regen from gear now, 0% from Meditation)
11. Adding 5% cloak - reported mp2 goes from 24 to 27 - checks out (20% regen from gear now, 0% from Meditation) - got 3 more mp2 now than I had at the begining with 3/3 Meditation and 4/4 gear.

Conclusion - gear % regen works, something not right with Meditation.

12. Adding 1/3 Meditation - BCS reports 35% regen! (should 25%) and 37 mp2 when casting (as much as it was reporting with 3/3 Meditation in the begining), but actual regen I have is 31mp2 (from 27mp2 so +4), looks like first 1st point in Meditation works although BCS reports wrong, as if 3/3 Med). 

13. Adding 2/3 Meditation - BCS reports 45% regen! (should 30%) and 44 mp2 when casting - actual regen I have 20mp2 when casting (-11). looks like 2nd Med point is working but breaks gear benefits (losing 15 mp2 from gear but gaining 4mp2 from 2nd Med point = net loss 11).

14. Removed all +5% gear - only lost 2mp2 (from neck's 5mp5) (18mp2 now). Looks like % regen from gear not working indeed.

15. Equipped all gear back - went back to 20mp2 (as much as in step 13)

16. Adding 3/3 Meditation - BCS reports 35% now (as it should) and 37mp2 (as at the very beginning) but only have 24mp2 actually (as in the beginning).

17. Removing 4 pieces - gets me back to 21mp2 (as in the begining before equipping pieces - at step 3).

At first I thought maybe 20% is cap but with 3/3 Meditation, adding a single gear piece doesn't increase mp2 as it should. It looks like Meditation points work as they should on their own, it's just that 2nd point breaks benefits from gear.

**Comment by twowTurtReynolds** [comment] 2023-12-13 18:48
Thank you for the detailed write up. I will be closing this as a duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1750

**Closed by twowTurtReynolds** 2023-12-13 18:48 UTC
