### ISSUE TITLE
Alterac Valley Alliance archers range and towers have unfair advantage

### ISSUE THREAD

**Issue by discslack** [slowtorta/turtlewow-bug-tracker#537] opened 2021-12-16 19:21 UTC
**Please, provide a clear description what the bug is:**
Alliance tower archers attack from halfway across the bridge near the alliance base and continue to attack you from inside the towers. Horde towers are blocked from 4/5 sides while giving a free capture to any ally inside
**Steps to reproduce the behavior with as much detail as possible:**

1. Attempt to capture an alliance tower and get pelted with arrows
2. Attempt to capture a horde tower and get a free cap once inside the tower
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Horde archers should be able to shoot those inside the tower to make it consistent for both sides

**Comment by geojak** [comment] 2021-12-17 09:57
How is this a bug? Isnt this blizzlike. horde can still use the infamous backdoor here on this server to my knownledge that has been patched out on classic.

classic has prooven how biased in horde favour vanilla alterac is with the closer start.

just close this issue in my opinion since its a chance request and not a bug

**Comment by slowtorta** [comment] 2022-01-11 00:45
Sorry, this one is working as intended, we don't plan to change the design of Alterac Valey any time soon!

**Closed by slowtorta** 2022-01-11 00:45 UTC
