### ISSUE TITLE
Black guard sentry immediately use their shadow shock

### ISSUE THREAD

**Issue by Kangaroux** [slowtorta/turtlewow-bug-tracker#6266] opened 2024-02-14 17:12 UTC
https://database.turtle-wow.org/?npc=10394

These spawn in strath when the door to rivendare opens. They will immediately use their shadow shock when aggroed and can easily one-shot a tank. 

In classic, they are far less aggressive. I'm not certain on the exact timing, but in this clip the first shadow shock doesn't seem to be used until 10 seconds after the pull: https://youtu.be/YsFmsuBGQak?t=4103

**Comment by twowTurtReynolds** [comment] 2024-02-14 21:21
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/1142

**Closed by twowTurtReynolds** 2024-02-14 21:21 UTC
