### ISSUE TITLE
a bug I just came across

### ISSUE THREAD

**Issue by vdogmguy** [slowtorta/turtlewow-bug-tracker#5812] opened 2023-12-28 23:56 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. run along the noticeable path leading up the mountain, which will be south of Camp Mojache in Feralas.
2. you will see the breath meter activate even though you are on solid ground and above water.
3. you will see a small tent, which seems to be unoccupied with a bonfire next to it, and the ancient spirit wolf across the water.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by vdogmguy** [comment] 2023-12-28 23:58
adding this in as well, Go across the river, past the spirit wolf, next to the tree and there is the same issue in a few small spots.

**Comment by twowTurtReynolds** [comment] 2023-12-29 00:58
Duplicate of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5811

**Closed by twowTurtReynolds** 2023-12-29 00:58 UTC
