### ISSUE TITLE
Player formHogger 

### ISSUE THREAD

**Issue by yanhansome** [slowtorta/turtlewow-bug-tracker#5032] opened 2023-11-03 02:49 UTC
**Please, provide a clear description what the bug is:**
item disapperd 
**Steps to reproduce the behavior with as much detail as possible:**

1.Hogger；my item disappeard，please help 。 my account：kk50255244
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=

**Comment by twowTurtReynolds** [comment] 2023-11-19 18:38
dupe of https://github.com/slowtorta/turtlewow-bug-tracker/issues/5033

**Closed by twowTurtReynolds** 2023-11-19 18:38 UTC
