### ISSUE TITLE
rogue qeust bug

### ISSUE THREAD

**Issue by maxcodk** [slowtorta/turtlewow-bug-tracker#5241] opened 2023-11-16 21:45 UTC
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. rogue yolorogue, accepted qust at about 20 lvl, tried to do then abandonded it 
2. tried to get this quest from npc, there was no quest flag above him and no quest
3. asked gm for help, he added quest to quest log

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://www.wowhead.com/classic/npc=332/master-mathias-shaw
Quest: https://www.wowhead.com/classic/quest=2360/mathias-and-the-defias

you should be able to pick it up at any lvl

**Comment by maxcodk** [comment] 2023-11-16 21:51
found out the problem, probably needed just to get next quest from https://www.wowhead.com/classic/npc=7024/agent-kearnen

**Comment by twowTurtReynolds** [comment] 2023-11-18 14:34
So was it the fact that you had done Mathias and the Defias, tried to do Klaven's but then failed it, and forgot you had to go back to westfall and not stormwind to pick it back up?

Thats all good, easy mistake to make. I'm closing as not a bug, Let me know if there still is something weird here.

**Closed by twowTurtReynolds** 2023-11-18 14:34 UTC
